### ISSUE TITLE
Unknown option: :hdr

### ISSUE THREAD

**Issue by Zeid164** [cdgriffith/FastFlix#103]
with v3.3.1 i got that ffmpeg command : 

"C:\Users\X\AppData\Roaming\FFmpeg\bin\ffmpeg.exe" -y -i "E:/tmp/my_file.mkv" -max_muxing_queue_size 4096 -filter_complex "[0:1][0:4]overlay[subbed];[subbed]scale=1920:-1:flags=lanczos[v]" -map "[v]" -c:v libx265 -pix_fmt yuv420p10le -profile main10 -x265-params ":hdr=1:hdr10=1:hdr-opt=1:hdr10-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,50):max-cll=1000,530" -crf 20 -preset medium -map_chapters 0 -map 0:0 -metadata:s:1 title="" -metadata:s:1 handler="" -metadata:s:1 language=fre -c:1 copy -map 0:2 -metadata:s:2 title="" -metadata:s:2 handler="" -metadata:s:2 language=eng -c:2 copy -map 0:3 -c:3 copy -disposition:s:3 0 -metadata:s:3 language=fre "E:/tmp/my_file-fastflix-682f.mkv"

**Comment by cdgriffith** [comment]
You might have a blank space in the `Additional x265 params` field on the Quality panel. It looks like I am not properly removing white space from there, and will work on handling that better.

**Comment by cdgriffith** [comment]
Actually just tried it on my end, seems that it always has a leading `:`, need to fix that.

**Comment by cdgriffith** [comment]
Issue should be fixed in [3.4.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.4.0)
