### ISSUE TITLE
crash opening mkv

### ISSUE THREAD

**Issue by Zeid164** [cdgriffith/FastFlix#108]
crash occuring while opening a file : 

fastflix[5696] ERROR Exception in 'open_file': list index out of range - args: (<fastflix.widgets.main.Main object at 0x0000029CD4A9D940>,)
Traceback (most recent call last):
  File "fastflix\widgets\main.py", line 245, in <lambda>
  File "reusables\wrappers.py", line 293, in wrapper
  File "reusables\wrappers.py", line 285, in wrapper
  File "fastflix\widgets\main.py", line 612, in open_file
  File "fastflix\widgets\main.py", line 1139, in page_update
  File "fastflix\widgets\main.py", line 1127, in build_commands
  File "fastflix\encoders\hevc_x265\command_builder.py", line 73, in build
  File "box\box_list.py", line 69, in __getitem__
IndexError: list index out of range

the movie is playable without any problem

media info : 
General
Unique ID                      : 233111167120356204975233896123681830868 (0xAF5F93E4FCAF7335120FD0E757C177D4)
Complete name                  : E:\X.mkv
Format                         : Matroska
Format version                 : Version 4
File size                      : 45.3 GiB
Duration                       : 1 h 56 min
Overall bit rate mode          : Variable
Overall bit rate               : 55.7 Mb/s
Encoded date                   : UTC 2018-09-08 10:36:54
Writing application            : mkvmerge v26.0.0 ('In The Game') 64-bit
Writing library                : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                             : 2
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@High
HDR format                     : SMPTE ST 2086, HDR10 compatible
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 1 h 56 min
Bit rate                       : 51.1 Mb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.257
Stream size                    : 41.6 GiB (92%)
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : Display P3
Mastering display luminance    : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level    : 9977 cd/m2
Maximum Frame-Average Light Le : 240 cd/m2

Audio #1
ID                             : 1
Format                         : DTS XLL
Format/Info                    : Digital Theater Systems
Commercial name                : DTS-HD Master Audio
Codec ID                       : A_DTS
Duration                       : 1 h 56 min
Bit rate mode                  : Variable
Bit rate                       : 2 123 kb/s
Channel(s)                     : 6 channels
Channel layout                 : C L R Ls Rs LFE
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossless
Delay relative to video        : 4 s 497 ms
Stream size                    : 1.73 GiB (4%)
Title                          : VFF DTS-HDMA
Language                       : French
Default                        : Yes
Forced                         : Yes

Audio #2
ID                             : 3
Format                         : DTS XLL
Format/Info                    : Digital Theater Systems
Commercial name                : DTS-HD Master Audio
Codec ID                       : A_DTS
Duration                       : 1 h 56 min
Bit rate mode                  : Variable
Bit rate                       : 2 525 kb/s
Channel(s)                     : 8 channels
Channel layout                 : C L R LFE Lb Rb Lss Rss
Sampling rate                  : 48.0 kHz
Frame rate                     : 93.750 FPS (512 SPF)
Bit depth                      : 16 bits
Compression mode               : Lossless
Stream size                    : 2.06 GiB (5%)
Title                          : VO DTS-HDMA
Language                       : English
Default                        : No
Forced                         : No

Text
ID                             : 4
Format                         : PGS
Muxing mode                    : zlib
Codec ID                       : S_HDMV/PGS
Codec ID/Info                  : Picture based subtitle format used on BDs/HD-DVDs
Duration                       : 1 h 54 min
Bit rate                       : 24.2 kb/s
Count of elements              : 1961
Stream size                    : 19.9 MiB (0%)
Language                       : French
Default                        : No
Forced                         : No

Menu
00:00:00.000                   : :Chapter 01
00:09:54.385                   : :Chapter 02
00:17:38.015                   : :Chapter 03
00:24:31.595                   : :Chapter 04
00:33:58.619                   : :Chapter 05
00:43:51.211                   : :Chapter 06
00:52:30.564                   : :Chapter 07
00:57:39.038                   : :Chapter 08
01:03:10.912                   : :Chapter 09
01:09:33.669                   : :Chapter 10
01:17:23.680                   : :Chapter 11
01:25:26.287                   : :Chapter 12
01:35:41.527                   : :Chapter 13
01:41:00.429                   : :Chapter 14
01:43:42.966                   : :Chapter 15
01:45:38.206                   : :Chapter 16

**Comment by cdgriffith** [comment]
Darn, was hoping to sneak out that fix with 3.4.2 without anyone running into it 😉 

It has to due with the video track not being the first ID value, will be with 3.4.2 release later today. Doing testing on it now.

**Comment by cdgriffith** [comment]
Fixed in [3.4.2](https://github.com/cdgriffith/FastFlix/releases/tag/3.4.2)
