### ISSUE TITLE
dhdr10-opt optimizing HDR10+

### ISSUE THREAD

**Issue by SlashX** [cdgriffith/FastFlix#111]
Hello again,

I found that in x265 if you encode using metadata for HDR10+ you have another option called --dhdr10-opt.
`--dhdr10-opt reduces SEI overhead by only putting the HDR10+ dynamic metadata in only the IDR and frames where the values have changed. It saves a few bits and can help performance in the client's tonemapper.`
It is an option for optimizing HDR10+

If you can add an option for that.
An example of this in screenshot.
![Test](https://user-images.githubusercontent.com/29688/97454958-fe98e880-193f-11eb-852a-de71b199c99b.jpg)

Thank You!

I have a question, because I don't know if you have a forum where we can talk.
I want to ask you what do you think of setting the vbv on a video for a specific level. Is it worth for the video, or if it helps with something. This question has nothing to do with the gui. Just wander if I should use it with CRF or not.
Thank you.

**Comment by cdgriffith** [comment]
I haven't even thought about creating a forum to be honest. I set up a quick discord server if you use that: https://discord.gg/GUBFP6f

dhdr10-opt is a good thing to add! Will be clear to add on that line as well, so good thinking. 

I honestly haven't touched vbv settings myself. I don't stray far from the standard settings TBH.

**Comment by cdgriffith** [comment]
Added in 4.0.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0
