### ISSUE TITLE
Copy video stream

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#113]
so that we can transcode audio only, or repackage/split video clip.

**Comment by cdgriffith** [comment]
Sorry for delay in response, I have been thinking about this one. 

I don't think that will be a feature I implement anytime soon. FastFlix currently has no way of muxing together or extracting a single type of stream. When it is more full featured and possible to maybe just encode /extract an audio track, or add external audio / subtitles it will be a feature that makes more sense to compliment those with.

**Comment by cdgriffith** [comment]
Added in https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0
