### ISSUE TITLE
Add a panel to show details about source video?

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#114]
so we can learn the source bitrate, format as well as if there's any HDR and so on, without manually running ffprobe. It will be much more convenient.
It might be simply ffprobe output or in some more organized format.

**Comment by cdgriffith** [comment]
Great idea, thanks for this report! Added in  https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0 

It's a little rough but at least shows some basic info for now.  

You can also enable the "secret" DEVMODE=1 env variable when launching it for a "Debug" panel that will have more introspective into the program as its running.
