### ISSUE TITLE
[SUGGESTION] Image sequence as source

### ISSUE THREAD

**Issue by forart** [cdgriffith/FastFlix#115]
Hi there, this is a really great piece of software !

I have a set of 10000+ HDR images (or, better, frames 'cause it's a time lapse) shotted with my camera that i want to encode into x265 HDR.

It would be very useful (and quite unique, at least between open projects: afaik only [AnotherGUI](https://www.stuudio.ee/anothergui/) - which is free but closed source - have this feature) to input a set of images (frames) to encode.

Here's some - maybe - interesting links to implement it:
- https://gist.github.com/bpholt/465b64b20faf6bea3579abea5c047915
- https://medium.com/@sekhar.rahul/creating-a-time-lapse-video-on-the-command-line-with-ffmpeg-1a7566caf877
- https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence
- https://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/

Hope that inspires !

**Comment by cdgriffith** [comment]
Definitely not a use case I imagined, but is something that would be very cool to add. 

A few different ways to implement this would be: 

* Separate panel that would be a list of files (importable by folder) that can be reordered. Then auto-create / use concat.txt file (most work, probably most user friendly)
* Support glob / pattern matching for source input, as well as setting frame rate
* Take a `concat.txt` file as input, and automatically add the concat type when detected. Then need some way to set frame rate. Could also have a "generate concat.txt by folder" option in menu.  (easiest, but less user friendly)

**Comment by L0Lock** [comment]
I'm 100% on this request!

I'm a CG animator, whenever I render an animation it's 99% of the time as an image sequence, and I use custom windows batch scripts to convert them as video files (see [L0Lock/FFmpeg-bat-collection](https://github.com/L0Lock/FFmpeg-bat-collection)).

And there are a lot of animators (pretty much all of them), or globally any kind of graphics artists, in need of a fast and friendly too to convert image sequences to videos. I happen to be nerdy enough to dive into CLI tools, but you can guess most graphics people can't do that.  
Adding this feature to Fastflix would make a lot of people's like easier. And my repo useless, but that's not a big loss.

**Comment by cdgriffith** [comment]
Hi @1983lynx  it sounds like you may be using the standard source load, need to use the Concatenation builder. 

I just wrote some details in the wiki to help as a guide! https://github.com/cdgriffith/FastFlix/wiki/Turning-images-into-a-video
