### ISSUE TITLE
Option "Force signaling of HDR10 parameters" seems not operational

### ISSUE THREAD

**Issue by HannesJo0139** [cdgriffith/FastFlix#116]
The new added option "Force signaling of HDR10 parameters" seems activated automatically as soon as Bit Depth is set to 10 Bit. I am not sure if that behavior is practical. 

In x265, the option is deactivated per default and auto activated as soon as master-display or max-cll are specified. Fastflix will set max-cll for every HDR encode anyway, so there seems to be no need to touch it anymore. Furthermore, if one encodes 8bit material using the 10bit encoder (in order to achieve better compression / less banding artifacts) the option gets auto activated contrary to the default x265 behavior.

However, the box seems not operational anyway. Ticking or unticking it is not changing anything in the command line.

**Comment by cdgriffith** [comment]
Ah yeah, not very clear as it is becasuse if the script that builds the commands for x265 detects master-display or cll data, it auto enables it no matter what the frontend says. (It's really only an "option" if you have a 10-bit bt2020 video without HDR10 metadata currently). 

Will also need to make it so in the case of 8 -> 10 bit those options are disabled, as that won't change the colorspace to be HDR10 compatable. 

The front end act better in next major release, thanks for the report!

**Comment by cdgriffith** [comment]
Fixed (hopefully) in https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0
