### ISSUE TITLE
User Selectable Tone Map for HDR to SDR

### ISSUE THREAD

**Issue by remlap** [cdgriffith/FastFlix#118]
Hi just discovered FastFlix its great for HDR to HDR conversion :)

I thought I'd give HDR to SDR a try and well I don't think hable cuts it for tonemapping I like to use mobius normally in mpv, could there in future be an option to select the other tone mapping options?

Thank you.

**Comment by cdgriffith** [comment]
Updating with discord info.

Current command is: 
```
zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p
```
want is to be able to change change `hable` to `mobius`, and possible provide params as specificed http://underpop.online.fr/f/ffmpeg/help/tonemap.htm.gz

**Comment by cdgriffith** [comment]
Added in advanced panel, thanks for the suggestion!  https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0
