### ISSUE TITLE
Re-encode audio to DD+?

### ISSUE THREAD

**Issue by schlotkins** [cdgriffith/FastFlix#122]
Not an issue, but in general, it would be really cool if this could re-encode audio to DD+. Handbrake just does passthrough of LPCM TrueHD DTS HD etc. I would love to able to re-encode to DD+.

Thanks!
Chris

**Comment by cdgriffith** [comment]
Should be able to do that now by selecting the conversion of "eac3", from [wikipedia](https://en.wikipedia.org/wiki/Dolby_Digital_Plus)

> Dolby Digital Plus, also known as Enhanced AC-3 (and commonly abbreviated as DD+ or E-AC-3, or EC-3) is a digital audio compression scheme

If you mean to also convert it to stereo in a non standard manor, there is also [ongoing discussion](https://github.com/cdgriffith/FastFlix/issues/45) about adding more advanced downmix filters.

**Comment by cdgriffith** [comment]
If that didn't answer your question, let me know and we can re-open this! Closing for now
