### ISSUE TITLE
Bug report: first subtitle on the list has default flag set, no option to change this behaviour

### ISSUE THREAD

**Issue by ftpmorph** [cdgriffith/FastFlix#129]
Just found this project after trying to transcode some HDR content and learning HB doesn't support it yet.

So far so good with this, it does what it says on the tin and works very well. Thanks for making it!

I do have one small bug report however. In the current stable build, 3.4.3, if I select a subtitle track for an x265 encode it gets set as default in the MKV container. This means when I play the video the subtitles are enabled automatically. Nothing in the UI allows me to toggle this, compared to HB where I can tick a box if I want a subtitle track to be flagged as default... except in Mac OS where funnily enough HB has an identical bug.

Easy to fix this with some quick remuxing but nonetheless it'd be great if you could add a little box the user can select if they want the subtitle to be default or not, or simply change the command passed to x265 to explicitly tell it the subtitle track isn't default so the flag is disabled.

Thanks again for making this useful piece of software.

**Comment by cdgriffith** [comment]
Marking this as feature request for now, because this a bug in FFmpeg for MKV containers that I can't control the behavior of. Would either need to have the option to add a fake emtpy first track to make sure that doesn't happen or bring mkvmerge or something else into the mix to handle that after the fact.

**Comment by ftpmorph** [comment]
Thanks for such a rapid response!

I'm sure ffmpeg must be aware of the bug so hopefully they're working on a fix that'll be out soon. I might see if I can find anything about it in their issue tracker. Perhaps it's fixed for the next release so I could install a dev build or compile ffmpeg myself to fix the issue.

If not, mkvmerge would certainly fix it. That's what I'm using to correct the problem myself and it seems like a "cleaner" solution than adding an empty subtitle track. Although I'm sure that would be an effective quick and dirty way to sort it if implementing mkvmerge is a hassle or time consuming to bring another dependency in :)

**Comment by cdgriffith** [comment]
Looking at the docs for it: https://ffmpeg.org/ffmpeg.html

```
-disposition[:stream_specifier] value (output,per-stream)

    Sets the disposition for a stream.

    This option overrides the disposition copied from the input stream. 
    It is also possible to delete the disposition by setting it to 0. 
```
 
 I might actually be setting it wrong, because I do `-disposition:s:<output>` like metadata requires(for example `-metadata:s:a:0`), and it might be using the `:s` to look for subtitles specifically. I will do some tests this weekend, this might actually be something I can fix. Will update when I figure it out.

**Comment by ftpmorph** [comment]
Looking on the bright side, whenever the ffmpeg bug gets fixed upstream this problem will now for sure disappear from FastFlix! Thanks for looking into this so quickly.

**Comment by cdgriffith** [comment]
For anyone looking into this for now, can fix the generated video using [mkvtoolnix](https://mkvtoolnix.download/downloads.html)  mkvpropedit from the command line without the need for remuxing. 

```
mkvpropedit video.mkv --edit track:s1 --set flag-default=0
```

**Comment by cdgriffith** [comment]
In 4.0 this will be a "hidden" feature, aka will attempt to fix automatically in background after an encoding if `mkvprobedit` is found on the PATH. Currently in beta 4.0.0b7:

https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0b7

**Comment by ftpmorph** [comment]
Perfect, nice clean fix thank you!

**Comment by wiedemanu** [comment]
The default flag for subtitles can be disabled with the following ffmpeg command:
`-default_mode infer_no_subs`

I found this solution here:
https://stackoverflow.com/questions/65672037/disable-default-subtitle-track-with-ffmpeg

I just insert the line under "Custom ffmpeg options", but it would be great if this could be integrated as a selectable option in the FastFlix GUI.

**Comment by cdgriffith** [comment]
That is perfect @wiedemanu, thank you! I will look to add that as default behavior when no subtitles tracks are marked as default or forced

**Comment by wiedemanu** [comment]
Perfect! Thank you for adding this feature @cdgriffith 
I am glad I could help a little.

**Comment by cdgriffith** [comment]
Thanks again for that elegant `ffmpeg` based solution, this should now be supported fully in https://github.com/cdgriffith/FastFlix/releases/tag/4.2.1
