### ISSUE TITLE
When using HEVC (x265) GPU not utilized

### ISSUE THREAD

**Issue by howardsternisbatman** [cdgriffith/FastFlix#132]
Hello, 

I'm new to FastFlix. Should the HEVC encoder utilize my nVidia Geforce `GTX 1050 TI? 

I have it working in the experimental build of Handbrake but that does not yet handle HDR10.

thanks.

**Comment by cdgriffith** [comment]
Hi @howardsternisbatman! 

`x265` is a software encoder. nVidia has their own NVENC HEVC encoder which is available in FFmpeg through `nvenvc_hevc`  (can run the command `ffmpeg -h encoder=nvenc_hevc` to see all it's options). 

Historically GPU encoders have been a lot worse quality and not suitable for long term storage of videos, (instead being super fast and capable of real time encoding for streaming) so I haven't added them to FastFlix as that was not its use cases. However it seems the newest hardware generations are turning that around, so tracking the addition of adding those with this other ticket you can track https://github.com/cdgriffith/FastFlix/issues/109

I've done some tests on my 1080gtx and it's still not that good (requires 50~100% larger file for same quality), but apparently 2xxx and 3xxx cards are decently better.
