### ISSUE TITLE
[POLL] FastFlix server API with web UI (remote management)

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#134]
Opening this to get feedback on if people would want something like this or not.

Idea would be to have a background service running on a server, that has a well defined and secure REST API you could interact with. That way you could have various or a single remote node that you could send encoding commands too and it would run in the background. 

Would allow for encoding either local videos or be able to upload videos to it.

👍 for useful | 👎 for unneeded

**Comment by TGMais** [comment]
👎 It's a neat feature, but I wouldn't have a use for it anytime soon.

**Comment by jeremysgates** [comment]
Agree it sounds like a cool feature, but in my opinion more of a long-term/future feature to add.

**Comment by forart** [comment]
Even better: what about a Google-colab control GUI ?

Example:
https://colab.research.google.com/drive/1xqeZvoJXaBBPP6UyVwErnhwrnth0br0u

**Comment by bmcassagne** [comment]
If I'm understanding you correctly, I think remote desktop is much more sensible... If I ever bother to set it up.

**Comment by cdgriffith** [comment]
Glad this is out of scope currently! Closing for now
