### ISSUE TITLE
Can't switch between encoders when no source file selected

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#137]
When there's no source file selected, the quality panel doesn't change when I switch between encoders.
This may not be a problem so please postpone it if hard to fix.

**Comment by cdgriffith** [comment]
It's "working as designed" but I agree will be better to be able to switch properly or disable the drop down until a video is selected.

**Comment by cdgriffith** [comment]
Properly disabled in 4.0.4 https://github.com/cdgriffith/FastFlix/releases/tag/4.0.4
