### ISSUE TITLE
FastFlix on Windows Server 2008 R2 (probably also Windows 7) does start with a system error

### ISSUE THREAD

**Issue by odignal** [cdgriffith/FastFlix#143]
When starting the FastFlix.exe (4.0.1) on Windows Server 2008 R2, I get a system error popup stating: "The program can't start because api-ms-win-core-path|-1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

According to google search, also Window 7 systems have the same problem, as this DLL is available on Windows Server 2012+ and Windows 8+. Found a bug ticket for Python 3.9, which does not support Win 2008/7, might this be the cause?

Can this be fixed?

Version 3.4.3 runs fine on Windows Server 2008 R2.

**Comment by cdgriffith** [comment]
Do you happen to have that link? Because I did update the build from Python 3.6 to 3.9 so that sounds like the issue. 

Could you see if installing the [2019 VS Redistribution x64](Microsoft Visual C++ Redistributable for Visual Studio 2019) fixes it - [direct link](https://aka.ms/vs/16/release/VC_redist.x64.exe)

**Comment by odignal** [comment]
Here's the bug ticket for python 3.9: https://bugs.python.org/issue41412
Installing the 2019 VS Redistribution x64 did not fix it.
I think Python 3.8.7 should work.

**Comment by cdgriffith** [comment]
Ah guess they are just fully dropping support for old windows versions.  I will add a build version for Windows 7 / 2012 for next release as I don't think I use anything 3.9+ yet, was just future-proofing. 

However it will be denoted as legacy version, and won't have as regular of testing by myself at least.

**Comment by cdgriffith** [comment]
Beta version with this build https://github.com/cdgriffith/FastFlix/releases/tag/4.0.2b0

**Comment by cdgriffith** [comment]
Added builds in 4.0.2 to address this https://github.com/cdgriffith/FastFlix/releases/tag/4.0.2. 

The "download latest" will still point to the wrong one as a heads up, as it internally does not understand the difference.
