### ISSUE TITLE
With 4.0.1 and encoding with x264 the "Remove HDR" checkbox has no effect

### ISSUE THREAD

**Issue by chadj** [cdgriffith/FastFlix#144]
I'm attempting to encode with x264 while removing HDR in 4.0.1 and the "Remove HDR" checkbox has no effect on the FFmpeg command line that is being generated.

Also, thanks for the amazing software!

**Comment by cdgriffith** [comment]
Thanks for the report! Fix in beta https://github.com/cdgriffith/FastFlix/releases/tag/4.0.2b0

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.0.2
