### ISSUE TITLE
Extraneous "None" appearing in FFmpeg command (4.0.2)

### ISSUE THREAD

**Issue by chadj** [cdgriffith/FastFlix#146]
While working on an x264 encode I ran into the error:

`[NULL @ 00000287ef094a00] Unable to find a suitable output format for 'None'
None: Invalid argument`

While executing the following command:

`"C:/Users/chadj/AppData/Roaming/FFmpeg/bin/ffmpeg.exe" -y -to 7010.5 -i "D:/Video/Test.mkv" -metadata title="Test" -filter_complex "[0:0]scale=1920:-8:flags=lanczos,zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p[v]" -map "[v]" -c:v libx264 -pix_fmt yuv420p -tune film None -crf 20 -preset medium -map_metadata -1 -map_chapters 0 -map 0:1 -metadata:s:1 title="Surround 7.1" -metadata:s:1 handler="Surround 7.1" -metadata:s:1 language=eng -c:1 copy -map 0:2 -metadata:s:2 title="Surround 5.1" -metadata:s:2 handler="Surround 5.1" -metadata:s:2 language=eng -c:2 copy -map 0:8 -c:3 copy -disposition:3 0 -metadata:s:3 language='eng' "D:/Video/Test-fastflix-c072.mkv"`

The extraneous "None" seems to be after the "-tune film" arguments

**Comment by cdgriffith** [comment]
This is why I shouldn't do late night releases lol. 

Thanks for the heads up! Should be fixed in 4.0.3 https://github.com/cdgriffith/FastFlix/releases/tag/4.0.3
