### ISSUE TITLE
Bug: MacOS - Window Spawn Loop

### ISSUE THREAD

**Issue by TigerC10** [cdgriffith/FastFlix#148]
### What happens:
When starting FastFlix bin, after the UI loads it loads a secondary UI window.  This process repeats itself (endlessly).

Attempted to kill with:
```shell
sudo killall FastFlix
```

While the killall was able to close all of the windows, _they continued to spawn_.  Only solution was to remove executable permissions from the FastFlix bin:
```shell
chmod -x ./FastFlix
```

After removing exe permissions, the spawn loop was broken and I was able to re-add the exe permissions.  Spawn loop did not start again until I manually invoked `./FastFlix` again.

### Environment Details:
* FastFlix Version: 4.0.3
* MacOS Big Sur 11.1 (20C69)
* python --version
  Python 2.7.16
* python3 --version
  Python 3.9.1
* ffmpeg -version
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with Apple clang version 12.0.0 (clang-1200.0.32.27)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100

### Steps to reproduce:
```shell
chmod +x ./FastFlix
./FastFlix
```

### Logs
```plain
$> ./FastFlix

2020-12-30 00:43:33 MacBook-Pro.local fastflix-core[58524] INFO Starting FastFlix 4.0.3
2020-12-30 00:43:34 MacBook-Pro.local fastflix[58527] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -version
2020-12-30 00:43:35 MacBook-Pro.local fastflix[58527] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -hide_banner -encoders
qt.qpa.fonts: Populating font family aliases took 734 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
2020-12-30 00:43:37 MacBook-Pro.local fastflix-core[58528] INFO Starting FastFlix 4.0.3
2020-12-30 00:43:38 MacBook-Pro.local fastflix[58533] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -version
2020-12-30 00:43:38 MacBook-Pro.local fastflix[58533] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -hide_banner -encoders
qt.qpa.fonts: Populating font family aliases took 750 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
2020-12-30 00:43:40 MacBook-Pro.local fastflix-core[58534] INFO Starting FastFlix 4.0.3
2020-12-30 00:43:42 MacBook-Pro.local fastflix[58538] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -version
2020-12-30 00:43:42 MacBook-Pro.local fastflix[58538] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -hide_banner -encoders
qt.qpa.fonts: Populating font family aliases took 732 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
^CTraceback (most recent call last):
  File "fastflix/widgets/main.py", line 1364, in close
KeyboardInterrupt
Traceback (most recent call last):
  File "fastflix/widgets/main.py", line 1364, in close
KeyboardInterrupt
2020-12-30 00:43:44 MacBook-Pro.local fastflix-core[58539] INFO Starting FastFlix 4.0.3
2020-12-30 00:43:47 MacBook-Pro.local fastflix-core[58543] INFO Starting FastFlix 4.0.3
2020-12-30 00:43:49 MacBook-Pro.local fastflix[58546] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -version
2020-12-30 00:43:49 MacBook-Pro.local fastflix[58546] INFO Running command: /usr/local/Cellar/ffmpeg/4.3.1_4/bin/ffmpeg -hide_banner -encoders
qt.qpa.fonts: Populating font family aliases took 734 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
```

**Comment by cdgriffith** [comment]
Well that is very odd. I will look into that tomorrow as much as I can. I sadly do not own a Mac to test on, so will see if it is the same on Linux (does not happen on windows) to hopefully reproduce.

**Comment by cdgriffith** [comment]
Doesn't happen on linux it seems, so I have to do some guesswork with this one. If possible, could you try out this version to see if it fixes it? https://codecalamity.com/wp-content/uploads/2020/12/FastFlix_4.0.4b0-develop-2020.12.30-18.38_macos.zip

**Comment by TigerC10** [comment]
> I sadly do not own a Mac to test on, so will see if it is the same on Linux (does not happen on windows) to hopefully reproduce.

😅 Yeah, figured that'd be the case since the screen shot on the README was windows.

> If possible, could you try out this version to see if it fixes it? https://codecalamity.com/wp-content/uploads/2020/12/FastFlix_4.0.4b0-develop-2020.12.30-18.38_macos.zip

Gave it a shot, also getting the same issue with this build.  I'm not as well versed with Python as other languages, but I kinda wonder if this has to do with `qtpy`.

**Comment by cdgriffith** [comment]
Yeah and I am doing some "weird" things with it. I am creating the UI in a background thread, so that even if it dies the conversion does not.  (But the UIs purposefully designed to die easily, not keep going!)

I'll see if I can't bum a friend's mac at some point to try more ideas or have an "ah ha" moment (aka google result page 192).

May be possible to just create a script for the time being to avoid the issue? 

create `fastflix.sh`
```
chmod +x ./FastFlix
./FastFlix
chmod -x ./FastFlix
```

Then give it permissions and run it instead:
`chmod +x ./fastflix.sh`
`./fastflix.sh`

**Comment by cdgriffith** [comment]
I think this might be related to https://stackoverflow.com/questions/32672596/pyinstaller-loads-script-multiple-times with Pyinstaller and multiprocessing. 

I had `freeze_support` already in there, as I did see this on linux in 3.x, but didn't have it in the newly created process as well, nor in the `main` section (was in first function). So making those small changes for 4.0.4b1. No clue if it will help. https://github.com/cdgriffith/FastFlix/releases/tag/4.0.4b1

**Comment by TigerC10** [comment]
Gave `4.0.4b1` a try and still had the issue. 😕 

Incredible support here, thanks for wrestling with this even though you don't have a Mac.  I'll try setting up a VM and see if this affects an older version of the OS like Catalina.

**Comment by TigerC10** [comment]
So here's something _really_ interesting...  When I clone the repo and run FastFlix from python directly, there's no issues.

```shell
git clone git@github.com:cdgriffith/FastFlix.git
cd FastFlix
python3 -m venv venv
. venv/bin/activate
pip3 install -r requirements.txt
python3 -m fastflix
```

Might be a pyinstaller thing...

**Comment by asleeis** [comment]
Just to add a "me too".  I only recently came to FastFlix (last week, I think) and discovered the issue.  Since I've seen so many good things said about it, I thought I'd dig deeper rather than just move on.  I will have to give the repo clone and direct python execution a try. 

I tried this with FastFlix 4.0.3 stable on Catalina.

**Comment by asleeis** [comment]
And I've confirmed that directly cloning the repo, setting up the python requirements/environment, and running the Python (as noted above)... no issues.

**Comment by cdgriffith** [comment]
Thanks for confirming it's affecting multiple versions of Mac OS. Did either of you happen to try out the script above to see if that prevents the loop?  (Might just include that with release for now if it helps as a stop gap.)

**Comment by cdgriffith** [comment]
I just upgraded to using newer version of PyInstaller with latest beta. Don't know if it makes a difference: https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0b2

**Comment by TigerC10** [comment]
Actually yes, `4.1.0b2` fixed the spawn loop for me. 😄

**Comment by cdgriffith** [comment]
Excellent! I will assume still the case in latest release (4.1.1) and mark this as closed. If it comes up again please let me know!

**Comment by cdgriffith** [comment]
Thanks again @TigerC10  for letting me know!
