### ISSUE TITLE
BugReport - custom ffmpeg options/ffmpeg_extras - not appearing in raw commands / not being passed through

### ISSUE THREAD

**Issue by kipperdawn** [cdgriffith/FastFlix#150]
Using v4.0.x, hevc encoder. i tried passing in an extra command to ffmpeg via the custom ffmpeg options in the gui but noticed i couldnt see my params in the raw commands window. I then tried adding to the end of the custom bitrate (since it had a text field and now my command is passed through). Looking quickly at the code (i don't really know python), it looks like the help class (helpers.py) should be inserting the "extra" via generate_ending,  however generate_all is not passing in the value to generate_ending... or i think this is what is happening.

eg... 
generate_all 
{
...
ending = generate_ending(
        audio=audio,
        subtitles=subtitles,
        cover=attachments,
        output_video=fastflix.current_video.video_settings.output_path,
    )
...
}

header for generate_ending
def generate_ending(
    audio,
    subtitles,
    cover="",
    output_video: Path = None,
    copy_chapters=True,
    remove_metadata=True,
    null_ending=False,
    extra="",
    **_,
):
    ending = (
...

I could be way off though as i didn't do a deep look into the code and i don't really know python

thx

**Comment by cdgriffith** [comment]
Thanks for running down that issue, you were totally correct! 

I still need to fix FFmpeg extras being re-set after returned from queue, so for tonight just put out a beta with that (and other similar) fixes.  https://github.com/cdgriffith/FastFlix/releases/tag/4.0.4b0

**Comment by kipperdawn** [comment]
Thanks so much for looking at it already.

**Comment by cdgriffith** [comment]
Fixed in 4.0.4 https://github.com/cdgriffith/FastFlix/releases/tag/4.0.4
