### ISSUE TITLE
Separate the "profile" in "new profile" button tooltip & "current profile settings" window from others

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#154]
The first 'profile' means a saved set of conversion parameters:
![image](https://user-images.githubusercontent.com/64267563/103435322-6a514780-4c48-11eb-960f-cfac312961be.png)
![屏幕截图(9)1](https://user-images.githubusercontent.com/64267563/103435325-73daaf80-4c48-11eb-919a-19df53fbbb4e.png)
The second one is a concept related to x264/5 & vp9:
![image](https://user-images.githubusercontent.com/64267563/103435362-fb282300-4c48-11eb-8d46-9e3148956f7d.png)
![image](https://user-images.githubusercontent.com/64267563/103435371-1b57e200-4c49-11eb-9fcf-9bfc996ce145.png)
I want to use different Chinese translation for these two "profile"s but they seem to be the same one in the languages file, so can you separate them?

**Comment by cdgriffith** [comment]
Splitting in 4.1.0b2

```
Profile_encoderopt:
Profile_newprofiletooltip:
Profile_window:
```

**Comment by cdgriffith** [comment]
Separated in  https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0
