### ISSUE TITLE
 Copying video stream causes crash

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#156]
Steps:
1. import a video file
2. set output codec as copy
3. click add to queue or start
4. crash
log when it is going to crash:
![屏幕截图(13)](https://user-images.githubusercontent.com/64267563/103445439-175eab00-4caf-11eb-8ba4-132fd9807ead.png)

**Comment by cdgriffith** [comment]
Thought this was fixed in 4.1.0, only tested it now that I released it, and still broke.  Will re-address soon in bug release.

**Comment by cdgriffith** [comment]
Ok, pretty sure it should actually work in this beta https://github.com/cdgriffith/FastFlix/releases/tag/4.1.1b0
