### ISSUE TITLE
Translation of tab name "Quality" lost when output codec switched

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#158]
When program launched this tab name is translated:
![image](https://user-images.githubusercontent.com/64267563/103445560-c8b21080-4cb0-11eb-9bec-cc8a4e09a65a.png)
Then I loaded a source, changed output codec and it went back to English:
![image](https://user-images.githubusercontent.com/64267563/103445584-14fd5080-4cb1-11eb-8d3a-d7dc790f3f93.png)

**Comment by cdgriffith** [comment]
Hopefully fixed in  https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0 thanks for the report! Your contributions have been huge!
