### ISSUE TITLE
Window resize??? And other minor issues.

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#162]
First of all, great program.  Greatly appreciated.  And I love the new queue system.  

1.  Would be great to be able to resize the app because I can't see the full name of many of my videos.
2.  Pausing the queue seems to cause issues.  Videos say they've completed but haven't.  Other videos get ignored completely.  Can't resume the queue.  
3.   Videos don't always process in the order of the queue.  
4.   Possibly unrelated to the app, but I have 3 computers processing videos.  All were approximately the same speed at medium setting, but at slow setting I have one computer processing almost 3 times the speed of the other 2.  The slower ones appear more appropriate.  About a third of the speed of the medium setting.  The one computer is processing almost as fast as it was on medium.  
5. Would be nice to have more options in the presets.  Especially to preselect more than one language.  The main reason I process my videos is to have my movies with Spanish and english audio.  Handbrake worked really well for this allowing me to select the first track of any number of languages.  
6. Options for processing the video streams would be great in the presets also.

And a simple question, does AAC conversion take place at constant bitrate?  If so is there any way to implement variable bitrate?

Once again, the app is greatly appreciated!!

**Comment by cdgriffith** [comment]
1. Thanks for pointing that out, I meant to set it back to "minimum" size after doing my testing and looks like it is set fixed currently.

2-3. If you can remember the behavior that lead to that / GUI logs please let me know. I did just come across an issue that the queue was modifiable when converting, and that should not be happening. In the upcoming beta #161 that will be properly disabled again (can add stuff to it, but not remove stuff from it after it's started). Do you happen to know if any of those times you started an encode and then modified the queue in some way while it was still converting? 

4. Things I would check for:  Were the videos all the same type (film / animation) and resolution? Are the versions of FFmpeg the same?  (x265 changed how it did presets between some recent versions) 

5. Could you do me a favor and write out the behavior you want for that in a separate ticket? That is definitely a nice to have, and Handbrake is really advanced at that so I don't think I will get to that level anytime soon. But may be able to have some sort of minimal solution. 

6. Do you mean like, always select X video track, or one with largest resolution or something? 

7. Also a good thing for a separate ticket, as you are correct right now it just does constant bitrate for everything. I want to do an audio overhaul at somepoint, but lots of things to do and just one me 😄 

Glad you like it and thank you so much for the feedback! It's really helpful getting real use cases and suggestions!

**Comment by bmcassagne** [comment]
1. Thanks for the fix!
2-3.  I noticed I had to drop a new video on the queue to be able to modify it.  I thought that was really strange.  Yes, it does lots of weird things after modifying the queue.  Also sometimes it will show nothing processing in the queue but the encode status shows something processing.  
4.  Seems to be processing at the same speed now.  I thought maybe one processor had some optimizations that were particularly useful for slow or something like that.  LOL
5. I'll do that
6. Sorry I meant to say audio.  It would be nice to be able to have the audio codec and bitrate in the presets.
7.  AAC 768kbps seems to be a good compromise for now.  I only use it for DTS-HD tracks that aren't DTS-X

**Comment by cdgriffith** [comment]
Fixing at least the windows resize, maybe some queue issues https://github.com/cdgriffith/FastFlix/releases/tag/4.1.0

Adding tickets for other long term issues https://github.com/cdgriffith/FastFlix/issues/166  https://github.com/cdgriffith/FastFlix/issues/164

If I missed anything please ping again, easy for me to overlook things!
