### ISSUE TITLE
Add audio stream / conversion selection in Profile

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#164]
As noted in my other post, it would be very useful to be able to select more than one language in a profile.  Such as, select Spanish, English, ets, and use the first stream from each, or use all streams for each.  Also, it would be very helpful to be able to put a transcode codec and bitrate in the presets, such as AAC, 768kbps.

**Comment by cdgriffith** [comment]
Advanced audio matching in the profile now possible in 4.7.0! https://github.com/cdgriffith/FastFlix/releases/tag/4.7.0
