### ISSUE TITLE
More robust queue that is recoverable

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#166]
Reported from bmcassagne in #162

**Comment by E-t-z** [comment]
I think, possibility to save/load queue would be helpful as well.

**Comment by bmcassagne** [comment]
Personally, I'm never going to save or load a queue.  It should autosave at the beginning of every conversion and it should autorecover when you open the app.

**Comment by E-t-z** [comment]
Just had an power outage + UPS failure and lost my 10 video queue... :cry:

**Comment by E-t-z** [comment]
Well, I feel your pain.

Encoding with x265, preset slow, crf 16/17 takes approx 2,5-3 days per video...and when power suddenly dissapears, you will start over... 

I do have fairly powerful system, with liquid cooled 9900k, it can reach, blazing fast 0.8fps... 😃

**Comment by bmcassagne** [comment]
Oh wow. I have an i7-7820HK in my laptop and I'm getting 0.8 fps on slow but CRF 21-23. I can't see any difference below 21 CRF and the files get really big.

**Comment by E-t-z** [comment]
@bmcassagne after some minor tweaking (and leaving it alone), it does improve a bit ~2.7fps.
It would still take almost 1,8 days to complete single video...hence recoverable queue would still help a lot... 🙂

**Comment by bmcassagne** [comment]
That's some pretty good tweaking.  What did you change?

**Comment by E-t-z** [comment]
1) Stopped all other activities on that machine.
2) Higher PL2 wattage, multiplier +2 to sustain higher all core clocks (4.8 -> 5.0GHz). Unfortunately my CPU is “potato”, it cannot do higher than 5.0 on all cores, for more than short benchmark runs and even then.

As far as HW goes, it cannot go any faster, unless I switch to NVENC, so I started to look at x264 params.

One of the most interesting options is x265 no-rect, I have to do some testing, but it seems to halve slow preset encoding time. Not sure about quality impact yet as there seems to be very little information about it.

**Comment by bmcassagne** [comment]
Oh that's a nice setup.  I almost bought a new AMD Threadripper, but I have plenty of hard drive space so there's no real reason to hurry.  I haven't seen anything from NVENC that approaches the quality vs size of using a CPU.  Thought I don't understand why.  They're always saying how how amazing video cards are for parallel processing but so far I haven't seen it with video.

**Comment by E-t-z** [comment]
@bmcassagne Turing supposed to have improved things considerably and I do have RTX2080Ti.

**Comment by cdgriffith** [comment]
Added in 4.2.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.2.0
