### ISSUE TITLE
Have a "No Profile" option

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#170]
Don't change the settings at all based on a profile selection, just have it always use what was last set.   Idea from https://github.com/cdgriffith/FastFlix/issues/152

**Comment by bmcassagne** [comment]
I thought it was already doing this.  At least with video.  Audio settings always return to default.  As far as audio it would be much more useful to make the profiles more robust.

**Comment by cdgriffith** [comment]
As profiles have become more robust and integral to FastFlix, especially for bulk conversions, and the need for a "standard" profile at minimum, this will not happen.
