### ISSUE TITLE
FastFlix 4.1.0 ERROR Could not set profile setting copy

### ISSUE THREAD

**Issue by E-t-z** [cdgriffith/FastFlix#172]
4.1.0 throws at launch.

```
Traceback (most recent call last):
  File "fastflix\models\config.py", line 203, in load
    setattr(profile, setting_name, setting)
  File "pydantic\main.py", line 373, in pydantic.main.BaseModel.__setattr__
ValueError: "Profile" object has no field "copy"
```

**Comment by E-t-z** [comment]
Still testing other functionality, but seems to work fine, otherwise.

**Comment by cdgriffith** [comment]
https://github.com/cdgriffith/FastFlix/releases/tag/4.1.1b0 beta has a bugfix that will hopefully fix that. I don't have the config file with those settings to be 100% sure so would appreciate a test!

**Comment by E-t-z** [comment]
Will test tomorrow.

**Comment by E-t-z** [comment]
Tested, looks to be fixed, thank you.
