### ISSUE TITLE
[REQ] Haiku port

### ISSUE THREAD

**Issue by MarcoRavich** [cdgriffith/FastFlix#173]
Since FF is already available for Windows, Linux and MacOS it would be interesting to have a port for the open source [Haiku OS](https://www.haiku-os.org/) (aka **the** Media OS) too.

I am aware that it is certainly not a priority, but in my opinion it would be a good opportunity for "get a foot in the door" into a growing community.

Hope that inspires !

**Comment by cdgriffith** [comment]
Interesting OS, have not heard of it. 

Downloaded it today and trying it to see what can be installed / built on it. 

Requirements for running:

- [ ] FFmpeg 4.3+
- [ ] Python 3.8+ 
- [ ] QT5 support
- [ ] Support for packages: appdirs, colorama, coloredlogs, iso639-lang, mistune, psutil, pydantic, pyqr5 (or pyside2), python-box, qtpy, requests, reusables, ruamel.yaml

Requirement for static build:

- [ ] [Pyinstaller 4.x + compatable](https://pyinstaller.readthedocs.io/en/stable/requirements.html)

**Comment by cdgriffith** [comment]
I only seen Python 2.7 in their package manager (really??) and FFmpeg says it's installed (4.2), but can't seem to run it from command line? 

So first looks I don't have high hopes it will be something reasonable soon

**Comment by forart** [comment]
Let's open an "help req 3ad" @ Haiku forum (it may help both projects evolve) !

https://discuss.haiku-os.org/t/help-req-fastflix-porting-issues/10275

**Comment by waddlesplash** [comment]
> I only seen Python 2.7 in their package manager (really??) and FFmpeg says it's installed (4.2), but can't seem to run it from command line?

FFmpeg CLI tools may be in a `_tools` subpackage. We definitely have Python 3... You may want to try an x86_64 build if you are on a 32-bit one, as there are more packages available there, anyway.

**Comment by cdgriffith** [comment]
@waddlesplash thanks for the fast reply! 

I think the problem was that I didn't do a update before searching `pkgman` for python. 

Looks like the hard blocker right now is `PyQT5` does not look to build (will try to get dump off the VM).  `psutil` is also not supported, but that is something possible to code around by disabling a few options. 


How would you run said `_tools` ffmpeg subpackage?

**Comment by waddlesplash** [comment]
You just install it, and then the `ffmpeg` command et al. should be available. We already have `pyqt` and `pyqt_python3` in the package repositories, you should just be able to install them.

**Comment by cdgriffith** [comment]
not sure what I'm missing 
![ffmpeg_h_issue](https://user-images.githubusercontent.com/3275435/104503659-fb101780-55a6-11eb-858a-aa3daff59767.PNG)

That is very nice you guys already have so much included btw! I just seem to be unlucky that need the bindings for Python3.8 or 3.9 and looks to only include for 2.7 or 3.7

However after installing those as well as `qt_devel` it looks to be building now, but has been taking half an hour at least, so hopefully works just takes a while.

**Comment by waddlesplash** [comment]
Try `pkgman install cmd:ffmpeg`, this will locate the correct package automatically (probably `ffmpeg_tools`) and ask to install it.

3.8 is not compatible with 3.7, and most Python applications are not all updated for 3.8+ support, so we are still on 3.7.

**Comment by cdgriffith** [comment]
`pkgman install cmd:ffmpeg` did fix it! 

I would ague the point about Python not being updated, as now that it's a yearly release and forwards code compatible there is very few things not automatically supported with newest versions. Generally only those with external dependencies that need custom builds, like PyQT5 sadly.  It finally did error out again trying to build.

When I have some free time I will look at the effort needed to revert the code back to 3.7 compatibility for testing and seeing how that works on Haiku. Thanks again for all the help!

**Comment by cdgriffith** [comment]
As Haiku is not a default github running and I will not have the option of spinning up custom ones, this is not feasible inside this project directly.
