### ISSUE TITLE
Unable to change queue order or delete task from queue since 4.1.0 

### ISSUE THREAD

**Issue by E-t-z** [cdgriffith/FastFlix#176]
In version 4.0.4 you were able to reorder/edit/delete items from queue while encoding.
This does not seem to be possible anymore, in version 4.1.0.

It is really annoying that you have to cancel or wait 5-6 (I mostly use 2-pass for my personal videos) hours, until current encode finishes, before you can do any changes in queue.

Maybe this functionality could be restored?
At least Reordering and deleting?
Only thing currently works, is adding new items to the queue.

**Comment by cdgriffith** [comment]
This will be part of the "more robust" queue system https://github.com/cdgriffith/FastFlix/issues/166

This initial take on it looked to have issues if it was modified in any way after the encoder starts, so had to disable for safety. Current version is that queue system in front end gets modified and sent to backend worker under certain conditions. And then the backend worker doesn't know for sure what order those items are in. 

The improved version will probably use a file based queue system so that they both are using the same data set directly

**Comment by E-t-z** [comment]
Fair enough, thanks 😄

**Comment by bmcassagne** [comment]
PLEASE GO BACK TO QUE SETTINGS OF 4.0.4!!  Queue editing seemed to be fine in 4.0.4.  I'm using 4.1.2, and it's great that I can resize the window but if I want to change a setting on the last encode I added I have to wait a week for the queue to finish???  This feels like a huge downgrade to me.  Or was there a big downside that I'm missing?

**Comment by E-t-z** [comment]
@bmcassagne you could successfully crash it, this way...
For now, I have managed to do it, multiple times and after @cdgriffith comment, it kind of makes sense why.

**Comment by bmcassagne** [comment]
Running 3 computers for several weeks I've only had MAYBE one crash.  One thing I've noticed though is that the que will look inactive but if you look under "status" there is an encode running.  Maybe I'm just doing things in a different order.  A crash on a 3 day encode would certainly be annoying.

**Comment by E-t-z** [comment]
It only crashes, when you mess around with that queue a lot and usually, when it tries to pick next item from queue.
Don't remember exact error message anymore, as UI immediately closes after that. 
Was probably something about, job not found, or something like that.

**Comment by bmcassagne** [comment]
Just to CO firm, there's no easy way to make tasks erasable in the queue? 

I guess I'm stuck with 4.0.4 till the new queue system is implemented. 🤷🏽‍♂️

**Comment by cdgriffith** [comment]
Fixed in 4.2.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.2.0
