### ISSUE TITLE
Autocrop Issue??

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#178]
Autocrop doesn't work properly on [a dark pallet movie].  It crops a large portion of the picture.  Autocrop in general is made worse by the very small preview that also can't be changed to a different time in the movie.  I will say this is the first problem I've noticed with autocrop in maybe 100 conversions.  This movie has a lot of black background that is probably confusing autocrop.  It's also interesting that the black seems to make the movie compress INCREDIBLY well.

**Comment by cdgriffith** [comment]
I think the "answer" to that is having a configurable number of autocheck points. It works by using the FFmpeg `cropdetect` at 4 points throughout the movie.  FastFlix will take that info and look for the one with the smallest amount of crop.

For darker movies probably better to have it configurable to 10 or so.

You can actually change the preview point of the video by setting a start time, and whichever start time you set it too will use that as the first crop detect point.  (Not well documented, and I agree would be nice to have better way to set preview / crop points!) 

Personally if it's 1 in a 100 I am ecstatic it works that well 😄, but there's always room to imporve, thanks for the report! 

Also for a dark movie it might be compressing it tooo well and getting a lot of banding. May have to up the Adaptive Quantization to the 3 option with `dark bias`.

**Comment by bmcassagne** [comment]
That's a good point about the movie but the compression seems to be fine.  Dark movies are usually really noisy but this one seems to be extremely clean.  Also there is a lot of black this is completely black.  Like they intentionally clipped the black levels to give it a different look.  And many of the backgrounds are soft which I think compresses better.  The entire movie looks like it's going to wind up at 1.1 GB.  1080p with 960kbps audio.  21q video compression, 10-bit.   Most movies with these settings wind up 6-9 GB.

**Comment by E-t-z** [comment]
As an side note, there are movies, with varying aspect ratios, so 4 is definitely too little for those.
Some examples: https://www.avsforum.com/threads/list-of-variable-aspect-ratio-movies-on-blu-ray.2811713/

**Comment by bmcassagne** [comment]
Interesting that there are a LOT of superhero movies on that list.  It's off topic but I saw for some reason Ant-Man and the Wasp is almost impossible to make VERY small.  (I saw it on that list)  I like to make movies 150-300mb to mostly listen to on my phone.  If you go less than about 500 mb with that one you can't even recognize the faces.  Even in the opening scene where there simply walking around a house.  I've tried resolutions as low as 240p.

**Comment by cdgriffith** [comment]
Fixed in 4.2.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.2.0  (can set number via setting panel)
