### ISSUE TITLE
Minor UI glitch, custom bitrate retains "k" when edited from queue

### ISSUE THREAD

**Issue by E-t-z** [cdgriffith/FastFlix#180]
Found an minor UI glitch, which does not seem to affect actual operation.

When you have items, in encoding queue, which have custom bitrate defined and you click edit, it retains "k" suffix on bitrate, so it does look like this in main view:

![image](https://user-images.githubusercontent.com/24243843/104627265-7a811200-569f-11eb-93bc-cfcf05d51f97.png)

Adding it back to queue seems to remove it though (it doe snot specify 7500kk as bitrate), hence it does not affect actual encoding.

**Comment by E-t-z** [comment]
Tested multiple times, with different files from queue, it is purely cosmetic issue.

**Comment by E-t-z** [comment]
Fun fact, I did not insert it with "k", when I initially added it to queue  :smile:

**Comment by cdgriffith** [comment]
I made it explicitly impossible to type letters there such as "k", then I just go and do it via the code. *le sigh* 

Thanks for the report!

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.1.2
