### ISSUE TITLE
Duplicate audio tracks

### ISSUE THREAD

**Issue by schlotkins** [cdgriffith/FastFlix#184]
I couldn't find a way to do this so... is there a way to duplicate an audio track? For example, if there is DD and TrueHD, you can only have one of each. But I'd like to disable the DD, have one TrueHD that converts to EAC3 and then a passthru TrueHD.

Thanks for this awesome App Chris - it's come so far so fast!

**Comment by cdgriffith** [comment]
Hi @schlotkins at the far right of the audio line there is an icon that should look like a "copy" icon that will add the same track again below. (can screenshot in a bit, currently on phone sorry)

**Comment by schlotkins** [comment]
Ah thanks sorry for being dumb

**Comment by cdgriffith** [comment]
Not a problem, the icon might not be the best for what it does, maybe changing back to a plus sign or something would be clearer

**Comment by bmcassagne** [comment]
Looks like a copy icon to me!
