### ISSUE TITLE
x265 aliasing problem with lower definition than UHD

### ISSUE THREAD

**Issue by Ing-Popeye** [cdgriffith/FastFlix#189]
Hi,

I'm very happy that a such software for someone like me, who doesn't know how to deal with commands lines in the terminal, exists. Thank you for your hard work.

My concern is about a problem that apparently occurs when using x265 library for encoding. With files that are downscaled to 1080p and bellow or just 1080p x264 transcoded to x265 without downscaling, some obvious aliasing appears on refined edges.

On my test file, a short anime episode, despite using the "Adaptive Quantization" on "enable + auto-variance + edge", some edges, especially the ones with red colors are messed up. Trying with and without "edge", with and without the "animation" tune, with and without Intra-smoothing at both slow and very slow at different bitrates, nothing works, except using x264, which is not the purpose that I'm looking for by using x265.

Here a some screenshots to illustrate.

![Original 1080p](https://user-images.githubusercontent.com/78022537/105841968-cc963180-5fd5-11eb-85cd-1944582f0dc7.jpg)
Original 1080p x264 @ 8482 Kbps

![x265 slower all options 1080p](https://user-images.githubusercontent.com/78022537/105841995-d61f9980-5fd5-11eb-9f65-dc2b23d45f6e.jpg)
Re-encoded 1080p x265 @ 2300 Kbps, slower, tune "animation", AQ "enable + auto-variance + edge"

![x264 slower all options 1080p](https://user-images.githubusercontent.com/78022537/105842003-d9b32080-5fd5-11eb-8f41-6bbe7b2be4ba.jpg)
Re-encoded 1080p x264 @ 2300 Kbps slower, tune "animation"

With this exemple, x264 works really great, I can stick with it, but it's more a concern with real-life footage. I don't keep all my 4K iPhone shot as it, some I re-encode in 1080p, some others in 720p, never bellow or simply deleted if it's not important and perhaps it's less obvious, it's exactly the same problem.

![x265 2160p](https://user-images.githubusercontent.com/78022537/105842975-4c70cb80-5fd7-11eb-89cc-0ec7ac84ab3d.jpg)
Original 2160p x265

![x265 1080p](https://user-images.githubusercontent.com/78022537/105843016-5c88ab00-5fd7-11eb-91c8-4f6f4b11bd6d.jpg)
Re-encoded downscaled 1:2 1080p x265

I don't know if certain filter is applied or if it's only the way x265 works, with such bigger macro blocks that are only visible with lower definition encode. I don't use CRF encode, but for 1080p, I target an average bitrate to have something between QP13 and QP16 and knowing the size before starting any encode. I'll try later today with handbrake to see if it's x265 relative only or an issue with Fastflix/ffmpeg.

I hope I'm clear in my explanation and detailed enough, English is not my native language.

Thanks again for all the effort you put in this incredible software !

**Comment by Ing-Popeye** [comment]
Quick update, it's an issue from VLC h265 decoder, by remuxing from .mkv to .m4v to use QuickLook (macOS), there is no aliasing at all. What a waste of time during the last 2 months I tried to figure out where it came from ,_,

**Comment by cdgriffith** [comment]
Sorry you were having that problem, but glad you were able to fix it and thank you for sharing your findings!
