### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by Demicro** [cdgriffith/FastFlix#192]
Is it possible to have the configuration file and the working folder in the same location as the program?

**Comment by cdgriffith** [comment]
Not currently, but good idea. Would need to allow it to take command line options on startup for that

**Comment by leonardyan** [comment]
Also I hope that ffmpeg binaries can be put here too ( in ./ffmpeg/ , for example ), and auto-detected without further configuration

**Comment by leonardyan** [comment]
This brings the real portability, all you need is in this folder.

**Comment by cdgriffith** [comment]
It is slowly becoming more portable. Now you can use a single folder by specifying env variables. For example on linux:

```
FF_WORKDIR=. FF_CONFIG=./fastflix.yml ./FastFlix
```
Doesn't yet detect a local ffmpeg / ffprobe but looking to add that as well.

**Comment by cdgriffith** [comment]
@ImportTaste let me make it up to ya, adding a more "true" portable mode with 5.1.0 https://github.com/cdgriffith/FastFlix/pull/396 

Will look for and use a local config file (same directory as exe), and create a subfolder `fastflix_workspace` (or FF_WORKDIR env value) to use

**Comment by cdgriffith** [comment]
Added in [5.1.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.1.0)!
