### ISSUE TITLE
Add 640kbps audio

### ISSUE THREAD

**Issue by Harybo** [cdgriffith/FastFlix#195]
Hey,

would it be possible to add 640kbps audio support which is already supported by handbrake and staxrip

**Comment by cdgriffith** [comment]
The current logic is that it will give options in a range of 32K per channel differences, that will be lowered to 16K per channel to have a lot more options in 4.2.0.  (For example 8 channel options, like 7.1, will have 640k. Whereas 6 channels, like 5.1 would have closest 672k, so they are divisible by 16)

**Comment by E-t-z** [comment]
@cdgriffith for AC3 it would be out of spec.. 😄 

AC3 bitrates are supported up to 640, most common is 448/640 for 5.1 or 192/256 for 2.0
Everything above 640, will violate AC3 specification, at the moment it is not even possible to pick 448/640 and I'm not even talking about downmixing.

**Comment by cdgriffith** [comment]
Good to know! I hope someday to do a big audio overhaul and add filters / vbr / custom rates / etc... but that's quite few months away probably.

**Comment by E-t-z** [comment]
Thats great, but I see one caveat here.
You have to go theough all of audio codec specifications you plan to support.
Or simply leave it to user an allow them do, whatever they want and encode things which nothing is able to play back... 😆

**Comment by ObviousInRetrospect** [comment]
I added 640k in this pull request: https://github.com/cdgriffith/FastFlix/pull/287

**Comment by cdgriffith** [comment]
Added in https://github.com/cdgriffith/FastFlix/releases/tag/4.6.0 thanks to @ObviousInRetrospect
