### ISSUE TITLE
GUI overlap controls

### ISSUE THREAD

**Issue by tyeeman** [cdgriffith/FastFlix#200]
Thanks for writing this. 

I'm using a 1080p monitor but using Windows scaling to 150% for text to read easier. That I suspect is causing the overlaps as shown in the image shown here. I think it's called "dpi aware" or something like that. You would have to add it to your app somehow I suspect.
One other preference is not to delete the current file or at least have some option to remember what the queue was. Lot of times I run multiple encodes of small segments and reloading the same file over and over is a pain. If there is a better way please suggest it.

Keep up the good work here!
<img width="960" alt="2021-02-15_223835" src="https://user-images.githubusercontent.com/4469306/108027996-f2649400-6fdf-11eb-9cb5-ab2231751a3d.png">

So you are using ffmpeg to access NVENC hardware or are you using Rigaya's encoder? I would suggest you compare. I'm using Rigaya's for over a year and some say it's better than ffmpeg for hardware encoding.

**Comment by cdgriffith** [comment]
Hey @tyeeman  sorry the interface is giving you issues at those settings. It does have DPI scaling enabled, but PyQT5 is still iffy on that. I will look into how I can make that better, thanks for providing the settings! 

A "don't clear on send to queue" is a good option I did not think about. Another good thing to look into! 

It's actually going to support both FFmpeg's and Rigaya's. Need to download Rigaya's and make sure the folder the executable is in has been added to the PATH.  Guide on how to add a folder to the path: https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by tyeeman** [comment]
Thanks for doing this. I don't see the setting you mentioned above in the fastflix.yml file, however the only thing cropped off now is the right couple of widgets. See image below - 
<img width="215" alt="2021-10-14_215220" src="https://user-images.githubusercontent.com/4469306/137434348-b6bd4ae3-0c11-4d31-9924-deea3453866a.png">

**Comment by cdgriffith** [comment]
Hi @tyeeman, hopefully this is now fixed with the upgrade to the new QT6 in the 5.x versions https://github.com/cdgriffith/FastFlix/releases/tag/5.1.0

**Comment by cdgriffith** [comment]
Added in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)! Go to setting > UI Scaling > Disable
