### ISSUE TITLE
Persistent Skipping Nal Unit Message

### ISSUE THREAD

**Issue by drluispaulo** [cdgriffith/FastFlix#208]
I apologize if I am using this space incorrectly, but since I have a doubt and I can't find it anywhere I look, I thought here would be the best place to ask. And if is not, there is no problem in deleting this.
I've been trying to rip [a video that] has HDR10+ in it. When I started to use Fastflix a message began to show: 

_### 2021-03-26 13:29:48 xxxxxxx fastflix-core[11240] INFO [hevc @ 0000029f2cc657c0] Skipping NAL unit 63
2021-03-26 13:29:48 xxxxxxx fastflix-core[11240] INFO     Last message repeated 9 times_

I immediately went to codecalamity.com to search an answer, witch I found (it is my first HDR10+ encode). Took all the steps, created the metadata.json file, updated my ffmpeg and Fastflix and then, tried again. And, for my surprise, the same messages continued to appear.
So, my questions are: Is this normal? Am I missing something? is the movie colors going to be washed out? or they are going to be washed out, but that's the way the movie is?
Yeah, can anyone help a 4k HDR noob here, please?

**Comment by cdgriffith** [comment]
Totally fine to ask here! NAL unit 62 and 63 have to deal with Dolby Vision information, so the source video must have had that as well. Currently [FFmepg does not support those layers](https://trac.ffmpeg.org/ticket/5688), so much so you can't even copy a video with that data in it. 

However that doesn't affect the video, HDR10 or even HDR10+ in any way. Just means the Dolby Vision data will be discarded. 

In FastFlix itself these messages will be filtered out as best possible by default if you have the checkmark checked on the Encoding Status page. It is not possible to filter the message out of the console logs themselves. 
![nal](https://user-images.githubusercontent.com/3275435/112730791-6f4d2c80-8f01-11eb-826e-e18d828d575f.PNG)


Just a more technical note in case anyone else stumbles across this: This will only be safe for Dolby Vision profile 8.1 videos (which will be any with HDR10 / HDR10+ data). Any full profile (like 5) without HDR10 backup will behave differently and may not be safe.  You can check the profile level with something like the MediaInfo tool, look for the HDR line.

**Comment by drluispaulo** [comment]
Thanks!! I was starting to get (very) worried that I was doing things wrongly. Or that I wasn't going to be able to watch with the HDR at all. I noticed that the messages weren't showing in FastFlix, só I thought I was in the right direction. Thanks for answering, for FastFlix, and for your awesome posts on codecalamity, they have saved me more times than you can imagine!
