### ISSUE TITLE
Error encoding with AV1 AOM

### ISSUE THREAD

**Issue by marcelospera** [cdgriffith/FastFlix#213]
Hi. I've found a problem with AV1 AOM encoder. I don't know if this just happens with the new version 4.2.0. I tried with x.265 and AV1 SVT and both worked fine.

Can anyone help me?

Thank you.

This is the log of AOM error: [removed]

Edited by admin:  Sections of pertinent info: 

```
"ffmpeg.exe" -y     -i "F:\Vídeo\<video file>.mkv"  -metadata title="" -max_muxing_queue_size 1024    -filter_complex "[0:0]crop=1920:1072:0:4[v]" -map "[v]"  -c:v libaom-av1 -pix_fmt yuv420p10le    -strict experimental -cpu-used 7 -tile-rows 0 -tile-columns 0 -usage good  -row-mt 1  -b:v 0 -crf 26   -map_metadata -1 -map_chapters 0  -map 0:1 -metadata:s:1 title="Surround 5.1" -metadata:s:1 handler="Surround 5.1" -metadata:s:1 language=eng -c:1 libopus -b:1 160k  -ac:1 2 -filter:1 aformat=channel_layouts=stereo -map 0:2 -c:2 copy  -disposition:2 0 -metadata:s:2 language='eng' -map 0:5 -c:3 copy  -disposition:3 0 -metadata:s:3 language='por'  "F:\Vídeo\fastflix-3e54.mkv"

...

2021-04-14 21:19:08,778 - ibvmaf WARNING could not read model from path: "/usr/local/share/mode
2021-04-14 21:19:08,779 - l/vmaf_v0.6.1.json"
2021-04-14 21:19:08,780 - Fatal error: Failed to load VMAF model.
```

**Comment by cdgriffith** [comment]
It looks like there is some issue with the version of FFmpeg you have (which looks like it was an auto downloaded one as well). Even thought it was built for windows, it's looking for the vmaf libraries on a linux path. 

Just tried with the latest from https://github.com/BtbN/FFmpeg-Builds/releases and can confirm it is an issue with that FFmpeg most likely. It's late here, but will look into it further in the morning. If you are tech savvy enoguh could try grabbing a month or so old version from those releases ( release that ends with -win64-gpl.zip) and extract it and point to it via the "settings "in FastFlix to try again.  

possibly this one, haven't tried myself as on phone internet ATM https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-03-31-12-39

**Comment by marcelospera** [comment]
Hello! I have various previous versions saved on my computer and looks like that at least the last 4.2.0 beta had this same issue but older ones have not. I will wait for the correction, anyway. I think this software is great! I already use HandBrake for x.264 or x.265 transcodes but this is THE software for AV1 transcodes. And this codec is amazing! AOM is far better (altough slower because it doesn't make full use of the CPU cores) than SVT (I don't have enough tests with rav1e to talk about it. Yet.)

Thank you very much.

**Comment by cdgriffith** [comment]
I tracked down the version of `FFmpeg` it started in and raised an issue for them to hopefully look into it. https://github.com/BtbN/FFmpeg-Builds/issues/64

This version of `FFmpeg` works with newest FastFlix for libaom-av1 just fine https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2021-04-03-16-28

**Comment by cdgriffith** [comment]
BtbN put in a patch to get it working again in their FFmpeg version. In FastFlix go to Help > Download Newest FFmpeg  and should be working again!
