### ISSUE TITLE
FFmpeg Hardware Acceleration with HDR

### ISSUE THREAD

**Issue by centuryx476** [cdgriffith/FastFlix#214]
Hello,
When will ffmpeg support fully hevc_nvenc that preserve the HDR10 information ?
I understand I can just use my CPU to preserve the HDR but I don't want to wait 3 days to do an encode.
My 3060 RTX card can chew thru it in probably an hour.

Thank You

**Comment by cdgriffith** [comment]
`FFmpeg`s implementation may never support it. Thankfully rigaya's NVEnc https://github.com/rigaya/NVEnc/releases does support that and you can use that with FastFlix. 

Extract the contents of the `NVEncC_<version>_x64.7z` into a permanent location (aka one you won't move / delete), and add that folder to the system path, and a new option will appear in the encoder drop down when you start FastFlix. If for some reason it doesn't auto detect it then, you can manually set the location through the settings.

**Comment by centuryx476** [comment]
OK wow, 
That worked really well. 
So its my understanding using rigaya's NVEnc that the HDR10 information is being preserved in HEVC stream ?

**Comment by centuryx476** [comment]
Going thru the encode I did with NVEnc and it works really well. Their is random color issues in some parts of scenes. So its a work in progress but a good step forward

**Comment by cdgriffith** [comment]
It should be yes, can look in the "Raw Commands" panel to make sure the "master-display" data is being preserved.   Then for the output video itself open it in a tool like MediaInfo https://mediaarea.net/en/MediaInfo  (I use "text" view)  and you should see a line like: 

```
HDR format                               : SMPTE ST 2086, HDR10 compatible
```

**Comment by centuryx476** [comment]
OK, So I'm using rigaya's NVEncc. The source is the raw mkv file and you can see the video track sees the HDR 10-bit. But the output when I put it back into FastFlix it says 8-bit and no HDR. Is it because I am just doing the first 5 minutes of the movie ?
![NVenc Output](https://user-images.githubusercontent.com/38863757/115398956-ac7da500-a1b5-11eb-8c43-9cffc66de72c.jpg)

**Comment by cdgriffith** [comment]
It looks like you converted it to AVC / H264 instead of HEVC / H265.  AVC does not have HDR support.

**Comment by cdgriffith** [comment]
![encoder select](https://user-images.githubusercontent.com/3275435/115401931-902b3980-a1b0-11eb-9dbd-7ac2fad6f41e.png)

That should be the encoder selected. Try again just to make sure please. If for some reason that one is selected and it still makes it into a AVC video, send me the logs for that encode please!

**Comment by centuryx476** [comment]
Yup,
My eyes were going down and I didn't notice the rigaya's HEVC at the top. My apologies!!
This is beyond great. 
Quick question: Doing a conversion using FastFlix and Rigaya's NVEncC, the output is .MKV; Can I change the container to .mp4, will that mess up the HDR information ? I understand that .mp4 and .mkv are just containers but they are very different containers. 
Thank You

**Comment by cdgriffith** [comment]
Yes a `mp4` should be able to handle that information just fine. I don't have a quick select for it just becasue `mp4` limits the types of audio you can have by a lot, and there is no easy way to grab a list of which ones it supports for each version of `FFmpeg`. 

You can manually change the `mkv` to `mp4` in the `Output` path. It will give a warning that it is unsupported but you can ignore it.

**Comment by centuryx476** [comment]
Perfect. 
If I may ask about my original question. 
Going over NVEncC repo and he uses a combo of C/C++ and most importantly Cuda to achieve this HA HEVC while preserving the HDR information. 
I'm guessing it is safe to say that FFmpeg will never implement this ?

**Comment by cdgriffith** [comment]
I wouldn't say "never" but it has been ongoing for a long time and still needs work https://trac.ffmpeg.org/ticket/7037

**Comment by centuryx476** [comment]
3 YEARS!!!!!!
And that is the part I am a little confused on. If this was opened three years ago and yet the roll-out of it has been next to nothing. And the demand for it is VERY high. Why is this not a natural priority ? I mean I understand that coding what me and others are asking for is not easy. But by now they should have some experimental builds with HA NVENC that preserves HDR!

**Comment by cdgriffith** [comment]
Tough problem + volunteer project = long time. I'm sure if some company invested directly for that feature it would happen a lot faster, but as HDR is still in it's infancy as far as video goes it's not their main concern. 

When they get around to adding that we can re-open this / create new ticket for making sure it's added to FastFlix.
