### ISSUE TITLE
Some questions/feature requests

### ISSUE THREAD

**Issue by cwills75** [cdgriffith/FastFlix#221]
First of all, this project is awesome!  Thank you for all of your hard work!

I've been using this for a couple of weeks now, and am wondering if I can streamline my workflow a little better.  A few things I can't seem to figure out how to do are:

1.  Set default Source folder.
2.  Set default Output folder.
3.  Disable adding of -fastlix... to the end of the output file.
4.  Save HDR->SDR Tone Map setting in saved user profile.

**Comment by cdgriffith** [comment]
That is amazing, thank you so much! 

I have added at least quick stops for 1 and 3 in https://github.com/cdgriffith/FastFlix/releases/tag/4.2.1  not in the setting panel, but added to the config file itself. 

Supported variables (anything in `{}` brackets) for `output_name_format` currently are: 

* source - original file name
* datetime - "near" iso filename safe datetime (ex. 2021-05-11T3-27-00)
* rand_4 - 4 random characters
* rand_8 - 8 random characters
* ext - the encoder specific file extension 

Just in case anyone else looks to donate, please always look in wiki for most up to date address (going to have to go dig up an old hardware wallet I almost forgot about for that one lol).

**Comment by cwills75** [comment]
Excellent update!  Hope you found your wallet.  I would have sent ETH but the gas is insane right now!

**Comment by cdgriffith** [comment]
Gah! I of course accidentally switched the logic while adding the filename generation. Should have a new release in a few hours for that, thanks for the quick heads up!

**Comment by cdgriffith** [comment]
Well lets hope this time I didn't do anything so obviously wrong lol https://github.com/cdgriffith/FastFlix/releases/tag/4.2.2

**Comment by forart** [comment]
>     4. Save HDR->SDR Tone Map setting in saved user profile.
>
I don't thing this is a good idea, 'cause you decide to switch parameters between different sources.

I would really prefer FF to store hw accelleration "defaults" since my hardware don't change so fast.

**Comment by cwills75** [comment]
> > ```
> > 4. Save HDR->SDR Tone Map setting in saved user profile.
> > ```
> 
> I don't thing this is a good idea, 'cause you could decide to switch parameters between different sources.
> 
> I would really prefer FF to store my hw accelleration settings since my hardware don't change so frequently.

I guess even a config file setting to set the default tone map option would be better than nothing.  I turn it to "None" for every file.

**Comment by cdgriffith** [comment]
> I turn it to "None" for every file.

@cwills75 just making sure, you don't need to set that to "None" to disable HDR -> SDR, just make sure the checkmark on the upper section is not checked. 

![remove hdr](https://user-images.githubusercontent.com/3275435/117994994-940d3000-b306-11eb-824c-bfbbad0dbd63.PNG)

**Comment by cwills75** [comment]
OK, I have that unchecked, I just thought the default HDR -> SDR Tone Map setting of hable or something other than None would override and apply it.  If it's not the case, then I'll just leave it on hable.

**Comment by cdgriffith** [comment]
Correct, that is only telling it which tonemap to use IF `Remove HDR` is checked.  Easy way to check is that in the "Raw Command" it will show a long filter complex if it is enabled: 

```
-filter_complex "[0:0]zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p[v]"
```

**Comment by cwills75** [comment]
That makes sense.  The latest update is working on my end also with source/output/naming, thanks again.

**Comment by odignal** [comment]
For default source folder: Which value must I set in the YAML file to set the source folder to the last used folder. This would be very helpful for converting a batch of video files in a directory without navigating from the user home directory to the video directory for every video.

**Comment by cdgriffith** [comment]
Closing as all these features should now be available! 

The source and destination folder are part of the Setting tabs, and Remove HDR can be saved to profile
The output file name will remain a "hidden" option in the config file
