### ISSUE TITLE
Odd Error - avcodec

### ISSUE THREAD

**Issue by centuryx476** [cdgriffith/FastFlix#228]
Hello,
I am trying to use NVEncC for some test encodes and I am getting this error. The only thing I did was update FastFlix
I attached some screenshots

![2021-05-21_10-03-10](https://user-images.githubusercontent.com/38863757/119150174-31114c80-ba1c-11eb-8657-2aa421c7b4dd.jpg)
![2021-05-21_10-03-22](https://user-images.githubusercontent.com/38863757/119150175-31114c80-ba1c-11eb-9367-3b94717b52b3.jpg)
![2021-05-21_10-03-27](https://user-images.githubusercontent.com/38863757/119150176-31114c80-ba1c-11eb-8c2d-eb74d7f372b5.jpg)

**Comment by cdgriffith** [comment]
Make sure: 

Those dlls are in the same folder as the executable
The folder C:\NVEncC has been added to the system PATH

**Comment by centuryx476** [comment]
When you say folder. You mean the FastFlix folder ?
C:\Program Files\FastFlix

**Comment by centuryx476** [comment]
AY no, I found them.
The dll files for some reason were not copied properly into the NVEncC folder.
Problem solved.
