### ISSUE TITLE
-default_mode issue

### ISSUE THREAD

**Issue by Nhunz** [cdgriffith/FastFlix#229]
I'm running FastFlix on linux Mint 20.1 and each time I try to covert a move it adds "-default_mode infer_no_subs" to the ffmpeg commands. This causes ffmpeg to crash with the error "Unrecognized option 'default_mode'" so the conversion fails. If I copy the raw commands to a text editor and remove that argument. I can then paste the commands into a terminal and it runs fine.  Any thoughts on a fix for this?

Thanks,

**Comment by cdgriffith** [comment]
Hi @Nhunz! 

I imagine your version of FFmpeg is out of date. If you downloaded via the package manager it probably is too old. From the README: 

> It needs FFmpeg (version 4.3 or greater) under the hood for the heavy lifting, and can work with a variety of encoders.

You can always go to https://ffmpeg.org/download.html where they list `Static Builds` at the bottom for linux that are up to date if you don't want to compile yourself.

**Comment by cdgriffith** [comment]
Closing this as it's outdated, if you're still having issues after updating please let me know!
