### ISSUE TITLE
Average bit rate

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#230]
I feel like this is a dumb question, but isn't there a dual pass average bit rate mode??   Some movies wind up much larger or smaller than expected.  It would be nice to run these in average bit rate mode.

**Comment by cdgriffith** [comment]
The "Bitrate" mode selector for each type of encoder are average bitrate (some are for the whole movie, when done with two passes, some are sliding window based like the hardware encoders) and shouldn't have much filerate difference. Keep in mind the audio may also be affecting the size of that is not being set at a single bitrate as well, as well as number of audio tracks.

**Comment by bmcassagne** [comment]
So I'm back to this again.  I see the new implementation of NVENC has options for 2 pass but all combinations I try give me an error message. I'm looking for a way to do constant quality really and I haven't been able to find any explanations. As far as your previous answer, that is true, but obviously some videos just compress MUCH better than others also.  Thanks again for the amazing work!
