### ISSUE TITLE
[TEST STUFF] UHD HDR10 R2020 ST2084 1000nit "free" video

### ISSUE THREAD

**Issue by MarcoRavich** [cdgriffith/FastFlix#235]
I found this interesting Creative Commons-licensed stuff on a fast server, check it out:

http://download.opencontent.netflix.com/?prefix=SolLevante/

**Comment by cdgriffith** [comment]
Link doesn't seem to work? Just showing `Error: [object Object]` 

Do you have an article or something that lists it's license and such?

**Comment by forart** [comment]
Works for me:
![test_1](https://user-images.githubusercontent.com/171307/122353897-c555cd00-cf50-11eb-9232-031704a29ecc.png)
![test_2](https://user-images.githubusercontent.com/171307/122353917-cb4bae00-cf50-11eb-8e9a-4d7b88c902f0.png)

Then "Save object as..."
