### ISSUE TITLE
NVEncC Multipass??

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#236]
Sorry if I'm missing this but I've searched everywhere.  So the default option with NVEncC is multipass.  But it seems to be only making one pass.  Am I doing something wrong?

**Comment by cdgriffith** [comment]
You mean that it's only running a single command? 

I am pretty confident to say NVENC multipass works is not the traditional full run and a second run, but rather an internal frame analysis run during a single run https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-video-encoder-api-prog-guide/#multi-pass-frame-phencoding so it will only be that single command.

**Comment by bmcassagne** [comment]
Well ok, I've never heard of that.  But also, I'm watching the bitrate during the encode and it's not changing.  I was under the impression that 2-pass is always VBR.   Otherwise what's the point?

**Comment by cdgriffith** [comment]
NVENC was designed with real-time / streaming in mind so all of its functionality and internal evaluations are based around shorter periods of time to look at and average for the target bitrate. 

I haven't played with it myself but I imagine giving much higher vbv Maxrate and Bufsize (bottom of advanced panel) will make it look at larger sections and have more variation, but not sure myself how much affect it would have.

**Comment by bmcassagne** [comment]
Ok, that's a good tip! If I'm reading correctly it may not affect how big of a section it looks at but should allow a lot more variation in the bitrate.   I'm playing with a new laptop with a Geforce 2060 and the speed is incredible.  Just wish I could trade some of that speed for more quality.  38fps at 4k HDR, 100-130fps @1080p.  And this is only a $900 laptop.

**Comment by bmcassagne** [comment]
So I'm doing a couple trial runs, max bitrate at 10k, and bufsize at 40k.  32 look ahead, AQ= temporal. VBR target=22,  2-pass, 5k for 1080p and 5k bitrate for 4k HDR.  Initial results seem very impressive and not much performance loss.
