### ISSUE TITLE
Preview image is too small

### ISSUE THREAD

**Issue by chelobaka** [cdgriffith/FastFlix#237]
Please make it possible to view bigger preview image. It's too small on a HiDPI monitor. Some possible solutions:
* Resize the image to fill empty GUI space.
* Statically configure image size.
* Add option to open the image in a separate window like HandBrake does.

**Comment by cdgriffith** [comment]
Ability to click on the image and get a pop-out full size tiff image now in 4.4.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.4.0

In the future might be nice to select exact timing for the image, as well as upgrade to using AVIF full HDR10 supported images when OSes (and pyqt) ship with those decoders by default. 

Thanks for the enhancement!
