### ISSUE TITLE
[IDEA] Auto name export file based on TMDB metadata

### ISSUE THREAD

**Issue by sdimovv** [cdgriffith/FastFlix#240]
It would be nice if FastFlix is a little smarter on output file naming. 

For example, a lot of self hosted streaming services have naming conventions. For example [Plex naming conventions](https://support.plex.tv/articles/naming-and-organizing-your-tv-show-files/).

In my opinion this can be done in two different ways, or a 3rd way that combines the previous two.

Option 1:
In most cases the input filename includes information about the movie name, year, season & episode (if TV show) etc. There is a [fantastic module](https://github.com/platelminto/parse-torrent-title) that can parse that and present it in a more usable format.
Example from their Github page:
```
PTN.parse('The Walking Dead S05E03 720p HDTV x264-ASAP[ettv]')
# {
#     'encoder': 'ASAP',
#     'title': 'The Walking Dead',
#     'season':  5,
#     'episode': 3,
#     'resolution': '720p',
#     'codec': 'H.264',
#     'quality': 'HDTV',
#     'website': 'ettv'
# }
```

Option 2:
There is an awesome TMDB API wrapper - [tmdbv3api](https://pypi.org/project/tmdbv3api/), that can get metadata by movie / TV show name. A minimum working example would be:

```
from tmdbv3api import TMDb
tmdb = TMDb()
# you can get one from the settings page of your TMDB account, this can be exported as a setting in FastFlix
tmdb.api_key = 'YOUR_API_KEY' 

search = movie.search('Mad Max')

# Sometimes more than one result can be returned but this can be fixed by either making a more targeted search or letting the user select which one they want 
for res in search:
    print(res.id)
    print(res.title)
    print(res.overview)
    print(res.poster_path)
    print(res.vote_average)
```

Option 3:
In my opinion this is the best option.
The [PTN](https://github.com/platelminto/parse-torrent-title) module can be used to parse the file name,  and that can be used to initiate the initial TMDB search. Then, if multiple results are returned, the extracted metadata from the file name can be used to select the correct title. Of course, the user should still be able to correct the output name (or make a manual search) in case the wrong title is selected. 

This option will also allow for the most accurate output naming as it would have metadata from 2 separate sources, which can compliment each other. For example, sometimes the episode name in a TV show is not included in the name, but that information is available in TMDB.

**Comment by cdgriffith** [comment]
This will not be implemented because content on IMDB / TVDB is copyrighted.

FastFlix does not condone unauthorized reproduction of copyrighted works and never shall.
