### ISSUE TITLE
Youtube HDR Profile? 

### ISSUE THREAD

**Issue by Devicetron** [cdgriffith/FastFlix#241]
I want to say that FastFlix is amazing! Can you create a HDR profile to upload videos to youtube? I been trying a few renders using different options and all say processing even after a few days... then I did a test render one in Adobe Premiere and it worked, I'm not an expert so I don't know what I'm doing wrong but this is the details I got from that file that worked in mediainfo json

"media": {
"@ref": "C:\\Users\\rene1\\Desktop\\C0059_1.mp4",
"track": [
{
"@type": "General",
"VideoCount": "1",
"AudioCount": "1",
"FileExtension": "mp4",
"Format": "MPEG-4",
"Format_Profile": "Base Media",
"CodecID": "mp42",
"CodecID_Compatible": "mp42/mp41",
"FileSize": "188696957",
"Duration": "37.538",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "40214600",
"FrameRate": "23.976",
"FrameCount": "900",
"StreamSize": "63189",
"HeaderSize": "61480",
"DataSize": "188635477",
"FooterSize": "0",
"IsStreamable": "Yes",
"Encoded_Date": "UTC 2021-07-04 14:59:17",
"Tagged_Date": "UTC 2021-07-04 15:10:45",
"File_Created_Date": "UTC 2021-07-04 14:59:17.410",
"File_Created_Date_Local": "2021-07-04 09:59:17.410",
"File_Modified_Date": "UTC 2021-07-04 15:10:45.908",
"File_Modified_Date_Local": "2021-07-04 10:10:45.908",
"extra": {
"TIM": "00:00:00:00",
"TSC": "24000",
"TSZ": "1001"
}
},
{
"@type": "Video",
"StreamOrder": "1",
"ID": "1",
"Format": "AVC",
"Format_Profile": "High 10",
"Format_Level": "5.2",
"HDR_Format": "SMPTE ST 2086",
"HDR_Format_Compatibility": "HDR10",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"Format_Settings_GOP": "M=3, N=23",
"CodecID": "avc1",
"Duration": "37.538",
"BitRate": "39884176",
"Width": "3840",
"Height": "2160",
"Sampled_Width": "3840",
"Sampled_Height": "2160",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.778",
"Rotation": "0.000",
"FrameRate_Mode": "CFR",
"FrameRate": "23.976",
"FrameCount": "900",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "10",
"ScanType": "Progressive",
"StreamSize": "187144221",
"Language": "en",
"Encoded_Date": "UTC 2021-07-04 15:00:16",
"Tagged_Date": "UTC 2021-07-04 15:00:16",
"colour_description_present": "Yes",
"colour_description_present_Source": "Stream",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"colour_primaries": "BT.2020",
"colour_primaries_Source": "Stream",
"transfer_characteristics": "PQ",
"transfer_characteristics_Source": "Stream",
"matrix_coefficients": "BT.2020 non-constant",
"matrix_coefficients_Source": "Stream",
"MasteringDisplay_ColorPrimaries": "BT.2020",
"MasteringDisplay_ColorPrimaries_Source": "Stream",
"MasteringDisplay_Luminance": "min: 0.0050 cd/m2, max: 1000 cd/m2",
"MasteringDisplay_Luminance_Source": "Stream",
"extra": {
"CodecConfigurationBox": "avcC"
}
},
{
"@type": "Audio",
"StreamOrder": "0",
"ID": "2",
"Format": "AAC",

**Comment by cdgriffith** [comment]
Hey @Devicetron thanks for posting, we are currently trying to figure this out as well in this issue https://github.com/cdgriffith/FastFlix/issues/231 so just closing this one as a dup, so please follow that one to make sure you get pinged if we figure anything out!
