### ISSUE TITLE
Add create a save profile and Main10 @profile 4.1

### ISSUE THREAD

**Issue by malzen** [cdgriffith/FastFlix#247]
There is only create, delete a profile and no save profile.
I noticed when I encode this is only profile 3.1 and no profile 4.1.

Please can you add this feature.

**Comment by cdgriffith** [comment]
What do you mean profile 4.1? 

And by save I assume you mean "update current profile to current settings"?

**Comment by malzen** [comment]
I meant this: ![alt text](https://i.imgur.com/W9alyJq.png)

**Comment by cdgriffith** [comment]
Ah, the decoder level. That is automatically determined by x265, and lower is better (as that means it can play on more devices). 

However you can add `level-idc=4.1` to the "Additional x265 params" (if you hover over it, it actually shows that as an example) to force a certain level.

**Comment by malzen** [comment]
I understand I am new to using this program.
