### ISSUE TITLE
Is there any new version of FastFlix

### ISSUE THREAD

**Issue by malzen** [cdgriffith/FastFlix#253]
Just wanting to know if you are going to release a new version anytime soon. As the last update you did was on may.

**Comment by cdgriffith** [comment]
Recovering from surgery currently so will be a bit before next release. Latest work I did is with AMF hardware endcoding will probably be next feature. If others put in code PRs for other features can test / add those faster of course.

**Comment by malzen** [comment]
Take your time to recover, as I will be patiently waiting for the next release.
