### ISSUE TITLE
Be able to update the x265 version

### ISSUE THREAD

**Issue by malzen** [cdgriffith/FastFlix#258]
Will I be able to update the x265 version of the software

**Comment by cdgriffith** [comment]
FastFlix is dependent on FFmpeg which has the x265 tool in it. Currently on Windows using https://github.com/BtbN/FFmpeg-Builds builds.  You can see what commit x265 is based off of https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-x265.sh#L4

On Windows, You can always update to latest FFmpeg through the Help Menu > Download Newest FFmpeg

On Mac / Linux you would have to download and link a newer static build or custom compile.

**Comment by cdgriffith** [comment]
If you're having any further issues with this, please feel free to keep asking / re-open.
