### ISSUE TITLE
Advanced settings are currently not saved on Profiles

### ISSUE THREAD

**Issue by georgesaumen** [cdgriffith/FastFlix#261]
Hello,

Can I ask, why I cannot config setting on Advance tab on your software ? I got error "Advanced settings are currently not saved on Profiles", can I know reason why ?

Thanks!

**Comment by cdgriffith** [comment]
It's a warning that it has not been implemented yet. There is nothing wrong with your particular install.

**Comment by phanluchoaofficial20** [comment]
> Đó là một cảnh báo rằng nó vẫn chưa được thực hiện. Không có gì sai với cài đặt cụ thể của bạn.

How can I enable it to config that tab ?

**Comment by cdgriffith** [comment]
Hi @phanluchoaofficial20 , as mentioned above there is no "fix". There is no way to save options under advanced profile currently. It still hasn't been coded.  

We can leave this ticket open as a Feature Request to add that functionality down the road.

**Comment by phanluchoaofficial20** [comment]
> Hi @phanluchoaofficial20 , as mentioned above there is no "fix". There is no way to save options under advanced profile currently. It still hasn't been coded.
> 
> We can leave this ticket open as a Feature Request to add that functionality down the road.

Thanks for reply, can I ask one more question ? Why I cannot enocde H265 NVENC with Rate Control is vbr_hq ?

![Untitled](https://user-images.githubusercontent.com/86090065/134107901-e192507e-d6f9-4e6f-bf7d-8f988fc3fa77.png)

This is my error!

Thanks!

**Comment by OnyxStreaming** [comment]
@phanluchoaofficial20, you need to change the Tune Preset to "Lossless" this can be found on the Quality Tab

**Comment by OnyxStreaming** [comment]
can you send a photo of your presets before starting the encode please and what buffer size do you have set

**Comment by ElDavoo** [comment]
@phanluchoaofficial20  FYI, vbr_hq has been removed from NVIDIA's video encoding API and thus from NVEncC .

**Comment by cdgriffith** [comment]
Adding saving of advanced options to profile in 4.7.0! https://github.com/cdgriffith/FastFlix/releases/tag/4.7.0

**Comment by georgesaumen** [comment]
Thks

Vào Th 6, 11 thg 3, 2022 vào lúc 08:23 Chris Griffith <
***@***.***> đã viết:
