### ISSUE TITLE
MacOS version does not show full codec name

### ISSUE THREAD

**Issue by kachijs** [cdgriffith/FastFlix#272]
Version 4.5.0 - does not show full name under codec dropdown - same goes for profile dropdown and trim profile dropdown. 4.4.2 version does not have this problem.
![image](https://user-images.githubusercontent.com/861217/138401220-5bb70ee4-9623-4c33-bc7c-6fe3a8d4408a.png)

**Comment by cdgriffith** [comment]
Hopefully fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.6.0 don't have a Mac to test with, so guessing for the fix!  (Will re-open if anyone reports otherwise)
