### ISSUE TITLE
(False Positive) Virus warning when using Windows versions

### ISSUE THREAD

**Issue by killer4king** [cdgriffith/FastFlix#274]
I just downloaded the latest version, and defender from Win 10 is reporting a virus:  Trojan:Win/Spursint.F!cl
also run it via virus total, there 2 out of 60 also detect a trojan...

are they fals positive?!

**Comment by cdgriffith** [comment]
False positives (as long as github DNS hasn't been hijacked nor your system compromised). The code is obviously here and open source, and the build info is public https://github.com/cdgriffith/FastFlix/runs/3901378888?check_suite_focus=true 

To protect against possible DNS hijacking you can check the signature after downloaded. Right click on the installer / portable and go to "Properties", then the "Digital Signature" tab. Should be signed by me, Chris Griffith. 

![sig](https://user-images.githubusercontent.com/3275435/140104540-f8ba44dd-8df1-4333-8c1e-173efb86ea15.png)

What's most likely happening is the tool I use to package the program into executables (PyInstaller) is being used by other evil parties, so the virus scanners are triggering on the PyInstaller parts.

**Comment by cdgriffith** [comment]
This has hopefully not been flagged in  recent times due to now buying the windows cert and increased usage showing it's a legit program. If it comes up again please let me know!

**Comment by mikeSGman** [comment]
Just happened to me on the latest version (5.7.0). Strange, because I checked the cert, and it shows your name and address and that it's valid. Install occurs, but exe file is deleted upon install.

![image](https://github.com/cdgriffith/FastFlix/assets/398394/90786300-9cb4-474d-81f6-0fba050f2926)
