### ISSUE TITLE
VBR mode for NvEncC

### ISSUE THREAD

**Issue by ElDavoo** [cdgriffith/FastFlix#276]
Hello,
This program is gorgeous. I love it!
NvEncC also supports VBR mode for encoding, which is a different thing from CQP. Is it possible to support it?
Thank you.
[Reference](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-int)

**Comment by cdgriffith** [comment]
Already supported! That is what is used if you use "Bitrate" mode. 

https://github.com/cdgriffith/FastFlix/blob/master/fastflix/encoders/nvencc_hevc/command_builder.py#L120

**Comment by ElDavoo** [comment]
Nice. I automatically assumed that was the CBR mode. :)
