### ISSUE TITLE
[REQ] QSVenc (and not only) support

### ISSUE THREAD

**Issue by forart** [cdgriffith/FastFlix#277]
Well, I know @cdgriffith don't have an Intel-based workstation, but - since other popular transcoders (such as @staxrip) already implements QSVenc - it would be great to integrate it too:
https://github.com/rigaya/QSVEnc

Last but not least, it would be interesting @rigaya's VCEEnc (HW encoder - VCE - for AMD) too, of course:
https://github.com/rigaya/VCEEnc

Hope that inspires !

**Comment by cdgriffith** [comment]
Already has VCEEnc support actually! Just need to link it up in the Settings panel. https://github.com/cdgriffith/FastFlix/wiki#hardware-encoders

As for QSV I am holding off until we figure out why it randomly drops quality and how to stop it from doing so: https://codecalamity.com/hardware-encoding-4k-hdr10-videos/#doblys-glass-blowing-demo-4k-hdr10-60fps-151-mbs-bitrate  

Closing this ticket as I'm tracking all hardware encoder stuff in https://github.com/cdgriffith/FastFlix/issues/109 ,  feel free to continue discussion there :smile:
