### ISSUE TITLE
Convert to DTS = experimental codecs are not enabled

### ISSUE THREAD

**Issue by Sub-7** [cdgriffith/FastFlix#283]
Hi cdgriffith,
First of all, thank you for the wonderful piece of software.

CMD:
`ffmpeg.exe" -y  -to 5838.5    -i "C:\Input.mkv"  -metadata title="Venom.2" -max_muxing_queue_size 1024 -map 0:0   -c:v copy -pix_fmt yuv420p10le       -map_metadata -1 -map_chapters 0  -map 0:1 -metadata:s:1 title="German DTS-HD MA 5.1" -metadata:s:1 handler="German DTS-HD MA 5.1" -metadata:s:1 language=ger -c:1 dca -b:1 384k -default_mode infer_no_subs  "C:\Final.mkv"`

When converting audio to DTS, I get the following error message:
`The encoder 'dca' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.`

simple "**-strict -2**" behind "**-c:1 dca -b:1 384k**" shows other error message:
`Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height`

increasing the audio bitrate solves my problem:
CMD:
`ffmpeg.exe" -y  -to 5838.5    -i "C:\Input.mkv"  -metadata title="Venom.2" -max_muxing_queue_size 1024 -map 0:0   -c:v copy -pix_fmt yuv420p10le       -map_metadata -1 -map_chapters 0  -map 0:1 -metadata:s:1 title="German DTS-HD MA 5.1" -metadata:s:1 handler="German DTS-HD MA 5.1" -metadata:s:1 language=ger -c:1 dca -b:1 1384k -strict -2 -default_mode infer_no_subs  "C:\Final.mkv"`

can you please look at this problem?

**Comment by cdgriffith** [comment]
Not sure what the issue / desired solution is with this?  

DTS is not in the "sane audio selection" via settings for reasons like this so should not affect non power users.

**Comment by cdgriffith** [comment]
Added `-strict -2` when dca is detected in 5.8.0, beta https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
