### ISSUE TITLE
FFmpeg 5.0 - DoVi Support

### ISSUE THREAD

**Issue by centuryx476** [cdgriffith/FastFlix#285]
Hello,
Does this mean Dolby Vision support in FFmpeg 5.0 ?
![DV](https://user-images.githubusercontent.com/38863757/150022953-6b90ba77-bb58-4d5c-9e65-a0a248d36bcc.jpg)

**Comment by centuryx476** [comment]
This the only reference I can see in ffmpeg 5.0. This is not present in the previous ffmpeg.
![DV_Out](https://user-images.githubusercontent.com/38863757/150025057-f7f5cd3e-0772-4b82-86dc-2e6b7e160c3e.JPG)

**Comment by cdgriffith** [comment]
Quick test seems that simply remuxing (aka copying the video stream) now doesn't remove Dolby Vision data with 5.0 like it did with 4.4! 

Not yet added to libx265 for encoding https://trac.ffmpeg.org/ticket/9131

Thanks for pointing this out, exciting news!

**Comment by centuryx476** [comment]
Awesome. 
A step in the right direction.

**Comment by cdgriffith** [comment]
What version are you using, seems to work with ffmpeg-n5.0-latest-win64-gpl-5.0.zip from https://github.com/BtbN/FFmpeg-Builds/releases  Tried with 2 different videos just to make sure. 

```
HDR format  : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
```

Tested with simple remux into a mkv ` ffmpeg -i in_video.mp4 -max_muxing_queue_size 1024 -map 0:0   -c:v copy -pix_fmt yuv420p10le       -map_metadata -1 -map_chapters 0 out_video.mkv`


`apply_dolbyvision`  is part of the libplacebo filter  (can see all options `ffmpeg -h filter=libplacebo` )  never used it myself before so don't have any context for it.

**Comment by centuryx476** [comment]
I'm an idiot. I was outputting as a .mp4. Now it works!
Question: Now that this first step of ffmpeg preserving the DV layer. How much harder will it be for them to implement a way to encode down the BL layer while preserving the DV ?
If i'm not mistaken the BL layer is the layer we want to encode down. Correct ?

**Comment by cdgriffith** [comment]
It should be currently possible to encode the DV layer and pair back with the RPU, but requires using x265 directly https://codecalamity.com/encoding-uhd-4k-hdr10-videos-with-ffmpeg/#saving-dolby-vision

However I know no way of saving the EL layer.

**Comment by cdgriffith** [comment]
Unfortunately x265 has DV RPU as a CLI only option https://x265.readthedocs.io/en/master/cli.html#cmdoption-dolby-vision-rpu

So have to wait for an update from them or for the ffmpeg workaround to be added https://trac.ffmpeg.org/ticket/9131

**Comment by centuryx476** [comment]
@cdgriffith 
I sent you an email asking about x265.

Thank You
