### ISSUE TITLE
FastFlix 4.6.0 can't load on Windows 7 or 8

### ISSUE THREAD

**Issue by Causemic** [cdgriffith/FastFlix#292]
I installed FastFlix 4.6.0 on Win7 x64.  Running it, the command window throws an error:
"Import error: DLL load failed while importing QtCore: The specified procedure could not be found."

Please advice?
Thanks
Causemic

**Comment by cdgriffith** [comment]
Windows 7 went EOL two years ago https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information . Packages and build systems are no longer supporting it I guess.

**Comment by Causemic** [comment]
Thanks, I was afraid of that. Pitty.
Could you tell me which version is the last supported by Win7? I had it installed and functioning some time ago.
regards

**Comment by cdgriffith** [comment]
Guessing 4.4.2 https://github.com/cdgriffith/FastFlix/releases/tag/4.4.2 as that was the last one before PySide6. 

Looking into it a bit more, does seem that QT6 (aka the graphics backend powering PySide6) [doesn't support Win 7 or 8, just 10+](https://ddgobkiprc33d.cloudfront.net/af5e6425-8244-4cf9-b7f4-8633f62e8ffd.png)

**Comment by tyeeman** [comment]
V4.5.0 works for me on Win7 64bit!

**Comment by Causemic** [comment]
Thanks @tyeeman. Sorry for late reply, been busy as hell.
Cheers

**Comment by cdgriffith** [comment]
I am moving back to older GUI library for time being to try and support Win 7 and 8 with https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0 

Let me know if it works or not!

**Comment by oleedd** [comment]
@cdgriffith
It doesn't.

**Comment by oleedd** [comment]
@cdgriffith
It doesn't. It wants "api-ms-win-core-path-l1-1-0.dll".

**Comment by cdgriffith** [comment]
FastFlix was re-updated to lastet GUI version after Windows 7 and 8 went outside of End of Life support. Only some version prior to 5.0.0 will work on old Windows versions.

**Comment by oleedd** [comment]
The thing is they don't support VVC.
