### ISSUE TITLE
Feature Request - Allow main-10 (10-bit) encoding for 8-bit content using rigaya's NVEncC encoder (HEVC)

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#294]
Hi, Chris! 

First, I know and understand that the rigaya NVEncC encoder is still experimental. It has been pretty much perfect for me other than this issue. Thank you for this great program. 

I had been using Handbrake and StaxRip for encoding. Both of those programs have an option to use main-10 (10-bit) encoding for 8-bit source files with NVEncC. This can help lower the bandwidth required for darker scenes so you can use a reasonable CRF / bitrate and don't get hard banding of gradients in content. 

I know that the 4K content I'm reencoding is 10-bit when using this encoder and FastFlix. It looks like there might have been a choice made keep the video pipeline at the same bit-depth as the input - 8-bit in and 8-bit out. Could I ask you to implement an option to allow us to choose the bit depth with this encoder? I can select main-10 on the FFMPEG NVENC encoder, but I'd like to do CRF single-pass instead of CBR. Since rigaya's implementation supports this, I'm asking about that one.

If there are other factors at play, let me know. I'm pretty dumb when it comes to software programming and the ins and outs of FastFlix. I'm really trying to have my cake and eat it too. :-) 

Thanks for all your hard work so far and your article with Jesse's info that helped me get Dolby Vision working on every single encode I've tried so far. This used to be so difficult and now it works fantastically.

**Comment by cdgriffith** [comment]
Thanks for pointing out this was missing! Added a check box for now to set to 10-bit output depth for 8-bit videos. https://github.com/cdgriffith/FastFlix/releases/tag/4.7.0  (will be auto checked if the source is already 10-bit)
