### ISSUE TITLE
Unable to select Level 5.1

### ISSUE THREAD

**Issue by Rayman24365** [cdgriffith/FastFlix#295]
I encoded a movie and it ended up at Profile Level 5, but I wanted Level 5.1.
I cannot find how to manually set the Level to 5.1.

**Comment by cdgriffith** [comment]
It's definitely more of an advanced option that you need to know that if you set it too low it will hurt your encode (as it will force the encoder to de-complicate it), and if you set it artificially high, certain devices might refuse to play the video even if the encoding isn't actually that complex. 

Unless a certain spec requires an exact level, it's best to let the encoder set if for you.

**Comment by Rayman24365** [comment]
Clear.
In my case I'm x265'ing a UHD HDR movie that is originally "Main 10@L5.1@High" which comes out after the encode as "Main 10@L5@Main".
I don't understand why FastFlix would 'downgrade' to L5, doesn't that hurt somehow?
From your knowledge, what would the effect be if I re-encoded it and forced L5.1?
Also ending up with Main when it started from High is something I cannot place (or actually even know what it is to be honest. I'm in the learning stages).

**Comment by cdgriffith** [comment]
With re-encoding you're losing information, that's all encoding does is toss out info and (usually) reduce complexity of the video unless doing it wrong. 

By making the video smaller and less complex, the encoder automatically detects "hey, this is the new complexity" and tells us without us needing to set one. 

From the x265 docs:  https://x265.readthedocs.io/en/master/cli.html#cmdoption-level-idc

> If specified, the encoder will attempt to bring the encode specifications within that specified level. If the encoder is unable to reach the level it issues a warning and aborts the encode. The requested level will be signaled in the bitstream even if it is higher than the actual level.
> Beware, specifying a decoder level will force the encoder to enable VBV for constant rate factor encodes, which may introduce non-determinism.

So for x265 case setting it higher won't do anything (unless using bitrate mode will require VBV), but setting it lower will make the video lower quality if possible, or outright error if it can't reasonably lower it. 

The `tier` is also automatically set. It only sets it at `High` tier if it needs the extra bandwidth. 

Having bigger level numbers / listing it as "High" is actually detrimental overall. As it is lying to video players / decoders by saying our new simpler video is a complex and high bitrate video.

**Comment by Rayman24365** [comment]
All very clear, thank you for taking the time for explaining this part in detail.

**Comment by cdgriffith** [comment]
Closing as I think all points addressed, if more questions please reopen or create new issue!
