### ISSUE TITLE
Auto crop inaccurate

### ISSUE THREAD

**Issue by Rayman24365** [cdgriffith/FastFlix#296]
Fastflix detected the auto crop to 48 pixels top and bottom.
VidCoder detected auto crop to 42 pixels top and bottom.
Encoded both and Vidcoder was correct as with crop at 42 pixels I had zero black pixels on top and bottom.
Possibly the auto crop detection is inaccurate.

**Comment by cdgriffith** [comment]
You can increase accuracy at the expense of a bit more time taken when loading videos by going to Settings and changing "Crop Detect Points" 

It works by using ffmpeg "cropdetect" at different points in the video (up to the number specified in settings) and will use the one that detects the most possible to crop. 

I am not sure how filter itself works, or how other tools do theirs so I cannot really comment on accuracy of the algorithms chosen beyond that.

**Comment by Rayman24365** [comment]
Well, should anyone ever ask you this again, I think I found the answer. It's indeed not FastFlix but ffmpeg related as you stated.
Ffmpeg likes to stick to multiples of 16 because codecs (used to) prefer that for lower overhead. Nowadays it doesn't matter.
So the actual crop was 42 like I discovered, but FastFlix is bullied by ffmpeg to use 48 (16x3) to stick to that old adaggio.

If I understand it correctly ffmpeg CAN be told to not use multiples of 16 pixels but can use 4 or even 2 (just has to be even for compatibility sake), but it defaults to a 16 pixels multiple for cropping.
So until (perhaps) this is resolved in FastFlix I will have to use Vidcoder, or any other tool, to confirm the actual crop.
A pixel is a pixel!

**Comment by cdgriffith** [comment]
Ah, thanks for that heads up. I will change the `cropdetect` to round to `2` instead of `16`!

**Comment by Rayman24365** [comment]
Excellent, glad I could contribute to this gem!

**Comment by cdgriffith** [comment]
Lowered the window to 2 pixels instead of 16, thanks for bringing this to my attention! https://github.com/cdgriffith/FastFlix/releases/tag/4.7.0
