### ISSUE TITLE
checkbox subtitles

### ISSUE THREAD

**Issue by Genine-Collin** [cdgriffith/FastFlix#301]
would it be possible and for me useful to have an checkbox to select all or deselect al subtitles

**Comment by jannisberry** [comment]
Could there also be a Checkbox to transfer all Attachments? Like fonts that are attached for the Subtitles? Would be really cool

**Comment by cdgriffith** [comment]
Added in [4.10.0](https://github.com/cdgriffith/FastFlix/releases/tag/4.10.0)    

@jannisberry  thanks for opening separate ticket for attachments #355, will track that there
