### ISSUE TITLE
Audio Filter

### ISSUE THREAD

**Issue by wynterca** [cdgriffith/FastFlix#304]
In the new update 4.7.0 the new audio filter doesn't select anything beyond 256kbps if you select 640kbps or 480kbps it wont take and shows 256kbps.  Also anything selected above 6 or 7 (which itself is confusing as you have to count to find out 5.1 is 10 or 11 on the list) for the downmix setting doesn't show correctly on the audio tab and if you leave it unset sometimes selects mono at 512kbps?   The new 10bit selection (I assume for converting 8bit video to 10bit) doesn't save in a profile?

**Comment by cdgriffith** [comment]
Thank you for bringing those issues to my attention! Fixed the bitrate and downmix issues in https://github.com/cdgriffith/FastFlix/releases/tag/4.7.1 

For the 10bit selection, you do mean specifically for rigaya's NVEncCC encoder correct?  I see those options were "hiding" in the profile window (was too small to see and had to increase size).

**Comment by wynterca** [comment]
Yes the one for nvencc 10-bit.   It doesn’t set in the profile also.   Every time i load an 8 bit file it turns off.

**Comment by cdgriffith** [comment]
Fixing the 10-bit issue in https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0

Thanks for bringing it up, and let me know if you run into anything else!
