### ISSUE TITLE
New audio profiles don't work with rigaya's encoders

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#306]
The new style of audio matching always creates new tracks for best behavioral results. However currently it's not possible to duplicate audio tracks with rigaya's encoders  so there will be an error message. 

Need to figure out the best way to use some form of advanced matching but still using the original audio inputs.

**Comment by wynterca** [comment]
I tried some earlier and i think it worked bit i have only one track selected.

**Comment by cdgriffith** [comment]
Should now work with https://github.com/cdgriffith/FastFlix/releases/tag/4.10.0

**Comment by Wontell** [comment]
Doesnt work, only selects one track, the previous version do work, it creates 2 duplicate tracks and they work fine
This new version doesnt create duplicate tracks and does nothing
When i have 2 tracks for example, say english and russian, I always get engliish track one and russian disbaled, no matter the settings i choose in profile
Matching by Title name =  doesnt work
Matching by Language =  doesnt work
Matching by track number = doesnt work

**Comment by Wontell** [comment]
Look at these images 
Same profile that was created with 4.10.0
Works properly on 4.9.4
Doesnt work on 4.10.0

![p1](https://user-images.githubusercontent.com/36778216/190311225-9d01b33b-cc21-4ba1-bb18-0b925b032f2d.jpg)
![p2](https://user-images.githubusercontent.com/36778216/190311227-d3d68682-f73a-4c57-912b-bed66405d6b2.jpg)

**Comment by cdgriffith** [comment]
Quick testing shows this should be fixed since 5.0.0 now, but if anyone has any more odd issues please let me know, thanks again!
