### ISSUE TITLE
Use SVT-AV1 Error CLI " -svtav1-params"

### ISSUE THREAD

**Issue by eveloki** [cdgriffith/FastFlix#307]
https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1553
Svt-av1 is the only stable encoder available to me at present
By Last  ffmpeg Buding. I Pull the SVT-AVL Last Version https://github.com/BtbN/FFmpeg-Builds/pull/139
Also Don,t Have  "-svtav1-params"
` 
ffmpeg -hide_banner -h encoder=libsvtav1
Encoder libsvtav1 [SVT-AV1(Scalable Video Technology for AV1) encoder]:
    General capabilities: delay threads
    Threading capabilities: other
    Supported pixel formats: yuv420p yuv420p10le
libsvtav1 AVOptions:
  -hielevel          <int>        E..V....... Hierarchical prediction levels setting (from 3 to 4) (default 4level)
     3level          3            E..V.......
     4level          4            E..V.......
  -la_depth          <int>        E..V....... Look ahead distance [0, 120] (from -1 to 120) (default -1)
  -preset            <int>        E..V....... Encoding preset [0, 8] (from 0 to 13) (default 13)
  -tier              <int>        E..V....... Set operating point tier (from 0 to 1) (default main)
     main            0            E..V.......
     high            1            E..V.......
  -rc                <int>        E..V....... Bit rate control mode (from 0 to 2) (default cqp)
     cqp             0            E..V....... Constant quantizer
     vbr             1            E..V....... Variable Bit Rate, use a target bitrate for the entire stream
     cvbr            2            E..V....... Constrained Variable Bit Rate, use a target bitrate for each GOP
  -qp                <int>        E..V....... Quantizer to use with cqp rate control mode (from 0 to 63) (default 50)
  -sc_detection      <boolean>    E..V....... Scene change detection (default false)
  -tile_columns      <int>        E..V....... Log2 of number of tile columns to use (from 0 to 4) (default 0)
  -tile_rows         <int>        E..V....... Log2 of number of tile rows to use (from 0 to 6) (default 0)
`

However, the commands generated automatically at present

`
"D:\ADE\PT_ENCODE\ffmpeg.EXE" -y  -to 300.0    -i "E:\ADE\Ex.Machina.2014.2160p.BluRay.Remux.HEVC.DTS-X.7.1.2Audio-ADE\Ex.Machina.2014.2160p.BluRay.Remux.HEVC.DTS-X.7.1.2Audio-ADE.mkv" "E:\ADE\Ex.Machina.2014.2160p.BluRay.Remux.HEVC.DTS-X.7.1.2Audio-ADE\Ex.Machina.2014.2160p.BluRay.Remux.HEVC.DTS-X.7.1.2Audio-ADE-fastflix-7b11.mkv"  -metadata title="Ex Machina - Ultra HD Blu-ray™" -max_muxing_queue_size 1024    -filter_complex "[0:0]crop=3840:1606:0:278[v]" -map "[v]"  -c:v libsvtav1 -pix_fmt yuv420p10le     -strict experimental -preset 7 -tile_columns 0 -tile_rows 0 0-tier main -sc_detection true -svtav1-params "color-primaries=9:transfer-characteristics=16:matrix-coefficients=9:mastering-display=G(0.2650,0.6900)B(0.1500,0.0600)R(0.6800,0.3200)WP(0.3127,0.3290)L(1000.0000,0.0000):content-light=1347,546:enable-hdr=1" -passlogfile "C:\Users\Administrator\AppData\Roaming\FastFlix\temp_c9cd1161a5c994eb0de87ee0\pass_log_file_d3b4175ff0e03cee9ff6" --crf 18 -pass 1  -an -f matroska NUL
`

Is also Use “-svtav1-params”

Perhaps the correct usage is  `SvtAv1EncApp.exe`

The end result is that I lost my hdr10 information

![W`4FP3 2TX}$}YS656W16PW](https://user-images.githubusercontent.com/24290190/158289447-fad64f89-1c38-420a-8018-12d8fa6f7937.png)

Update please.

**Comment by eveloki** [comment]
Thank!
I'll try again tonight。If works normally, I will rp;

**Comment by cdgriffith** [comment]
Closing this as there hasn't been activity in a while, if still an issue please reopen!
