### ISSUE TITLE
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#310]
After upgrading to 4.7.1, at startup I get warning messages listed below:

2022-03-17 13:53:19 Computer fastflix-core[6576] INFO Starting FastFlix 4.7.1
2022-03-17 13:53:22Computer fastflix[11988] DEBUG Creating new config file C:\Users\User\AppData\Roaming\FastFlix\fastflix.yaml
2022-03-17 13:53:23 Computer fastflix[11988] INFO Running command: C:\Users\User\AppData\Roaming\FFmpeg\bin\ffmpeg.exe -version
2022-03-17 13:53:23 Computer fastflix[11988] INFO Running command: C:\Users\User\AppData\Roaming\FFmpeg\bin\ffprobe.exe -version
2022-03-17 13:53:23 Computer fastflix[11988] INFO Running command: C:\Users\User\AppData\Roaming\FFmpeg\bin\ffmpeg.exe -hide_banner -encoders
2022-03-17 13:53:23 Computer fastflix[11988] INFO Running command: C:\Users\User\AppData\Roaming\FFmpeg\bin\ffmpeg.exe -hide_banner -log_level error -init_hw_device opencl -h
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile

This happens on multiple machines. Not sure if there's a setting I need to change or if I'm missing a configuration somewhere. I've tried uninstalling and removing the AppData\LocalLow\FastFlix directory before reinstalling the application. I'm running Windows 11. 

Thanks!

-Don

**Comment by cdgriffith** [comment]
Huh, I see that when using the github packaged one but not if I package locally. This will be fun to test. Not a warning to worry about, just means I need to update some PNG files apparently.

Now to figure out which ones...

**Comment by dongafford** [comment]
Thanks for the quick response. I was pretty sure it wasn't something serious since it was just a warning. I might have another issue with the new version. I'll submit a report when I can verify it on another machine and get you a report.

**Comment by dongafford** [comment]
As a follow-up to my last comment--

I was having an issue where the output of the encoding process would have issues seeking in the last 4-5 minutes of the film. Playback of the film showed no issues, and I had no issues seeking in the rest of the film. 

I had 5 titles that this occurred with. 4 of the films were part of a box set and the single film was from another studio. All 4K encodes. The source MKV did not have the issue and if I re-muxed with MKVToolnix, the issue still remained. The issue even happened when I ripped the video track with gMKVExtractGUI and re-muxed it by itself. 

The good news is that after uninstalling both, removing the AppData\LocalLow\FastFlix directory, and reinstalling, I'm no longer seeing this issue. The affected machine was running 4.7.1 and I had another machine running 4.7.0 where I hadn't seen the issue. 

Not sure what happened, but I'm glad I'm not experiencing the problems any longer. 

Thanks again for your work!

**Comment by cdgriffith** [comment]
Thank you so much for the sponsorship @dongafford! 

Think I figured out which PNGs were causing the issues using. Putting process here just in case others that google this issue stumble here (but mostly so I have it for the inevitable next time it happens.) 

```
# apt install pngcrush
find . -name "*.png" -exec sh -c 'echo Testing "{}" && pngcrush -n -q "{}"' \;
# go into directory with the issues
find . -type f -iname '*.png' -exec pngcrush -ow -rem allb -reduce {} \;
```

As for the seeking, that is an odd issue. Most players will look for a keyframe to seek too and do an offset based off that. So if that version of FFmpeg put a bad keyframe timing as the last one (let's say the random scenario is that it sets the time of the last one to the end of the video accidentally) then any seeking past that wouldn't work. 

I have also seen problems seeking if audio and video aren't synced properly. 

My best guess would be that the version if FFmpeg / the encoder itself would make the difference. Did you also delete the FFmpeg directory and re-download it after switching versions?  Either way, glad it's working for you now!

**Comment by cdgriffith** [comment]
Fixing the PNG issue in https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0 thanks for bringing it up! 

Feel free to keep commenting on this ticket about the seeking stuff or create new ones as needed!
