### ISSUE TITLE
VP9 is unable to use profile 2 or 3

### ISSUE THREAD

**Issue by BuyMyMojo** [cdgriffith/FastFlix#312]
Because the Bit Depth drop down in VP9 only shows yuv420p you are unable to select Profile 1 or 3.
Need options for for pix_fmt yuv422p and yuv444p

Encode status/ffmpeg output:
```
[libvpx-vp9 @ 000002cb3873a240] Error encoding frame: Invalid parameter
[libvpx-vp9 @ 000002cb3873a240]   Additional information: 4:2:0 color format requires profile 0 or 2
Video encoding failed
Conversion failed!
```

**Comment by cdgriffith** [comment]
Thanks for pointing this out. Going through and adding valid options for 422/444 videos for all ffmpeg encoders in https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0
