### ISSUE TITLE
FastFlix 4.7.1 NVEncC always has a command line:  --avsync vfr, Ignores CFR settings

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#313]
Hi,
Im re-encoding game footage that has variable FPS
FastFlix when used with NVencC ignores the advanced tab settings and always sets  --avsync vfr, completely ignoring the setting i chose, 60fps original, 60fps output and CFR.
Raw Command tab always show --avsync vfr, no matter my settings.
It works fine with FFmpeg nvenc option, but its slower

I created a FastFlix preset with my encode settings, all the game footage is from same game, captured by ShadowPlay, Variable FPS, usually hovers around 80, later by the end of the game i capped to 60fps while keeping 120hz, some re-encoded files indeed came out with constant bitrate but most didn't.
I think for the files with 60fps capped variable fpsm FastFlix uses CFR when you enable it in the advanced tab, but files with variable fps that go above 60, FastFlix for some reason always does --avsync vfr.

If anyone have this bug, temporal solution is easy: set all your settings in FastFlix, including the input and output file names.
Go to Raw Command and copy everything to text file.
find where it says --avsync vfr
replace with --avsync forcecfr

Open CMD window and copy paste everything and press enter, it will start rendering in the CMD window

**Comment by Wontell** [comment]
Update: I just installed 4.7.0 and I have same issue, unbelivable.

I have game files that I captured using nvidia overlay, I almost finished re-encoding most of them to save space and using SAME settings, and they all have originally variable FPS, so i set it 60/60 and CFR and some of them do have constant frame-rate but most dont.
I have no idea how and why FastFlix chnages the settings

**Comment by Wontell** [comment]
> Labeling this as bug and enhancement because the "bug" is there is nothing properly saying half the stuff on the advance page doesn't work with the hardware encoders. Nor is there a way to tell what does without deciphering the command yourself.
> 
> The enchantment is, just set `forcecfr` when `cfr` is selected and `vfr` if `vfr` is explicitly set. Otherwise fall back to figuring it out from the input video. Will either add this enhancement first, or both at same time. Thanks for raising the issue!

Hi,
NVencC only has 3 FPS modes, cfr, forcecfr and vfr, if you can change the advanced setting for nvencc to just reflect these 3 options it can also be a solution, right now the advanced tab vsync option has more settings then actual encoder.
Unless the advanced settings page is mirrored for all encoders and cant be changed to suit each encoder individually.

Thank you

**Comment by cdgriffith** [comment]
Correct that panel is independent of the encoders / doesn't get info about what encoder is currently selected. It was created back when only FFmpeg was used and these were just filters or stuff we could tack onto FFmpeg itself so it didn't matter. 

Best solution would be to make it aware of what encoder is being used and preset only valid options. Will need a stopgap until that can be done. Probably just label the options with a marker beside them of what doesn't work with rigaya's encoders.

**Comment by cdgriffith** [comment]
Adding the ability to set CFR / VFR from vsync drop down for rigaya's encoders in https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0

Also adding note about items not supported at all in advanced panel. Thanks for bringing this up!
