### ISSUE TITLE
ERROR    Could not run task Gather    FlixError(f'"{config.ffmpeg}" file not found')

### ISSUE THREAD

**Issue by brunogm0** [cdgriffith/FastFlix#314]
hi,  Im on Linux Garuda x86_64,  follows attached log. ffmpeg was found and executed for the version but it did not found the later "config.ffmpeg";

[flix_gui_2022-03-26T14.42.25.log](https://github.com/cdgriffith/FastFlix/files/8356128/flix_gui_2022-03-26T14.42.25.log)

**Comment by cdgriffith** [comment]
> "/usr/bin/ffmpeg" file not found

does it exist at `/usr/bin/ffmpeg` and is it executable by the same user running FastFlix?

**Comment by brunogm0** [comment]
Yes, but now i found the Issue on ArchLinux, so im closing this one sorry.

**Comment by RyanHakurei** [comment]
@brunogm0 So how did you fix it?

**Comment by brunogm0** [comment]
> @brunogm0 So how did you fix it?

I did not fix it, just closed this to follow up in the existing issue about ArchLinux. #271
