### ISSUE TITLE
HDR10 data missing

### ISSUE THREAD

**Issue by msaintauret** [cdgriffith/FastFlix#315]
I have noticed that for somes files fastflix is unable to find the hdr10 metadatas and i don't understand why because i saw them in the first frame : 

```
ffprobe.exe  -hide_banner -loglevel warning -select_streams v -print_format json -show_frames -read_intervals "%+#1" -show_entries "frame=color_space,color_primaries,color_transfer,side_data_list,pix_fmt" -i The.movie.mkv
{
[matroska,webm @ 0000024122212800] Could not find codec parameters for stream 5 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
    "frames": [
        {
            "pix_fmt": "yuv420p10le",
            "color_space": "bt2020nc",
            "color_primaries": "bt2020",
            "color_transfer": "smpte2084",
            "side_data_list": [
                {
                    "side_data_type": "Mastering display metadata",
                    "red_x": "35400/50000",
                    "red_y": "14600/50000",
                    "green_x": "8500/50000",
                    "green_y": "39850/50000",
                    "blue_x": "6550/50000",
                    "blue_y": "2300/50000",
                    "white_point_x": "15635/50000",
                    "white_point_y": "16450/50000",
                    "min_luminance": "20/10000",
                    "max_luminance": "10000000/10000"
                },
                {
                    "side_data_type": "Content light level metadata",
                    "max_content": 992,
                    "max_average": 518
                }
            ]
        }
    ]
}
```

**Comment by cdgriffith** [comment]
While looking at the coding block for this I see there is a issue for pulling HDR10 info out of not first video track I'll fix in next release. Is the video track 0 or higher?

**Comment by cdgriffith** [comment]
Fixing at least that one found bug in https://github.com/cdgriffith/FastFlix/releases/tag/4.8.0 

Please let me know if that fixes it for you!

**Comment by msaintauret** [comment]
i'm afraid nothing changed

i open the file, it take somes minutes because it seems that all the file is read
then in the quality tab none of the checkbox force hdr10 signaling / hdr10 optim / reapeat headers are checked
the raw command with standard profile is : 

`"C:\Users\xx\AppData\Roaming\FFmpeg\bin\ffmpeg.exe" -y      -i "E:\The.file.mkv"   -max_muxing_queue_size 1024    -filter_complex "[0:3]crop=3840:1600:0:280[v]" -map "[v]"  -c:v libx265 -pix_fmt yuv420p10le      -x265-params "aq-mode=2:repeat-headers=0:strong-intra-smoothing=1:bframes=4:b-adapt=2:frame-threads=0:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:hdr10_opt=0:hdr10=0:chromaloc=2"   -crf:v 22 -preset:v medium   -map_metadata -1 -map_chapters 0  -map 0:0 -metadata:s:1 title="DTS 5.1 @ 768Kbps" -metadata:s:1 handler="DTS 5.1 @ 768Kbps" -metadata:s:1 language=fre -c:1 copy -map 0:4 -metadata:s:2 title="TRUE-HD ATMOS 7.1 @ 4868Kbps" -metadata:s:2 handler="TRUE-HD ATMOS 7.1 @ 4868Kbps" -metadata:s:2 language=eng -c:2 copy -default_mode infer_no_subs  "E:\The.file.mkv"

so still no hdr10 master display

`in tried manually your command : 
E:\>C:\Users\xxx\AppData\Roaming\FFmpeg\bin\ffprobe.exe -loglevel panic -select_streams v:3 -print_format json -show_frames -read_intervals %+#1 -show_entries frame=color_space,color_primaries,color_transfer,side_data_list,pix_fmt E:\The.file.mkv
{
    "frames": [

    ]
}

I checked with mkvtoolnix and video is id 3

**Comment by msaintauret** [comment]
i tried exactly your command whithout the :3 and it works fine and instantly
with :3 the returned array is empty and i must wait 5 minutes to have the result

**Comment by cdgriffith** [comment]
You're right, looks like I have a bad line where I am doing ` -select_streams v:{video_stream.index}` where I need to remove the `v:` and just use `3` in that case. As `v:3` is saying use the third **video** stream, not the third stream overall. 

Other's probably haven't run into it as most videos have their primary track as track 0, so v:0 would give same result.

**Comment by cdgriffith** [comment]
Hopefully actually fixed with https://github.com/cdgriffith/FastFlix/releases/tag/4.8.1

**Comment by msaintauret** [comment]
yes v4.8.1 is working now
thank you !
