### ISSUE TITLE
dhdr10_opt not in command line window 

### ISSUE THREAD

**Issue by GizmoDudex** [cdgriffith/FastFlix#321]
Hi, when I check the hdr10+ optimisations checkbox on quality tab, this won't change something in the command line output.
I expected an x265param dhdr10_opt=1, but it is not in the command line section.
I use the commands to run them separately from fastflix. But it's great for generating the command.

**Comment by cdgriffith** [comment]
Thanks for bringing this up! Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0
