### ISSUE TITLE
When encoding errors occur, continue with the rest of the queue

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#323]
I think this is a feature request. I've noticed that when there is an error encoding a file that FastFlix will stop encoding the queue completely. I'd like to see if this behavior could be changed to throw an error in the queue and continue to the next encode in the list. 

When I have encoding issues, usually it's the one file and not a larger issue. 

Thanks.

**Comment by cdgriffith** [comment]
Hi Don, sorry for the delay on this one, but finally added to the queue page with a check mark.  https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0

Looking to possibly expand as just a perm config setting, but wanted to at least get something in for now!

**Comment by dongafford** [comment]
Thanks for getting this integrated, Chris!

It sounds like you had a bit of a tough time with this release. Hope you
get the new queue stuff worked out soon!
