### ISSUE TITLE
NVEncC wrong Interlace Value set by FastFlix

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#324]
Hi,
For some reason it wrongly detects already encoded HEVC HDR files as interlaced, happened twice already.
But the issue is that I cant re-encode the file, the encoding stops with  this error, which i managed to fix by closing FastFlix and re-opening and it stopped detecting this file as interlaced and it worked.

Looks like for NVEncC you need to set Interlace value to Auto instead False, let the encoder deal with it
and other options will be nice to have as drop down menu: Progressive, tff, bff

```
Error: Invalid value "False" for "--interlace"

  Option value should be one of below...
    progressive, tff, bff, auto

```

P.S. For some reason some BluRay Remuxes that have metadata Scan type: Progressive are detected as Interlaced

**Comment by cdgriffith** [comment]
for some reason a boolean was being cast to a string, hence seening the "False" there. (And it detected "oh there is a string, so it's true!") 

Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0 thank you for opening the issue!
