### ISSUE TITLE
error when starting fastflix on Ubuntu 22.04-beta

### ISSUE THREAD

**Issue by mrjayviper** [cdgriffith/FastFlix#325]
Any ideas on how to fix?

-----------

myuser@my-home-desktop ~/Downloads> ./FastFlix 
2022-04-10 23:18:17 my-home-desktop fastflix-core[5034] INFO Starting FastFlix 4.8.1
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so: undefined symbol: g_tls_channel_binding_error_quark
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
/tmp/_MEIE0EB53/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so

(FastFlix:5041): GLib-GIO-ERROR **: 23:18:17.786: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
2022-04-10 23:18:18 my-home-desktop fastflix-core[5034] DEBUG Conversion worker shutting down

**Comment by cdgriffith** [comment]
I am [seeing others](https://askubuntu.com/questions/1399085/glib-gio-error-settings-schema-org-gnome-settings-daemon-plugins-xsettings) starting to see this error as well. I haven't done testing on the latest ubuntu yet, but as it will soon be released that's a good thing to do, may just need to build on it for it to work IDK

**Comment by cdgriffith** [comment]
Added ubuntu 22.04 build in [4.10.0](https://github.com/cdgriffith/FastFlix/releases/tag/4.10.0) , may need to set an env variable, described in the wiki https://github.com/cdgriffith/FastFlix/wiki/Common-questions-and-problems#warning-ignoring-xdg_session_typewayland-on-gnome
