### ISSUE TITLE
[Feature Request] Support for hwaccel decoding

### ISSUE THREAD

**Issue by MobyGamer** [cdgriffith/FastFlix#326]
Currently fastflix has no options for adding `-hwaccel auto` to the processing pipeline.  I can add this myself by copying the generated commands and adding it, but it would be nice to have this option added to the GUI so that no such step is necessary.  Without it, my CPU usage becomes 100% dedicated to decoding, which throttles the speed of the process, thereby negating much of the benefits of using hardware acceleration in the first place.

My use case:  Due to various technical constraints(*), I am only able to successfully stream UHD 4K rips that have average bitrates of 60 Mbps or less; anything higher (for example Cloverfield, which has an abr of 89 Mbps) will pause and buffer occasionally.  My goal in using FastFlix was to use my RTX 3080 to transcode some of these larger rips to a slightly smaller rate, such as 50 Mbps, while still retaining full HDR information.  It works very well for that, however I must always copy the commands to a batch file and add `-hwaccel auto` to enable NVENC-assisted decoding

(*)The constraint is not one of network bandwidth, but of processing power on my LG C8, which can only decode up to 60 Mbps of network traffic at the same time HEVC video decoding is being processed.

**Comment by cdgriffith** [comment]
Does `-hwaccel auto` have to be added before the input / at a certain place, or can it just be added as `Custom FFmpeg Options` at the bottom of the encoder panel?  (If unsure I can look up more documentation on it as well, just might be a quick workaround for you).

**Comment by MobyGamer** [comment]
Good question.  I tried adding it as a command-line param, but it doesn't show up in the first pass bitrate command, and in the second pass bitrate command it is placed after the input file (specifically, after the encoding profile) which generates this error:

```
"C:\Users\mobyg\AppData\Roaming\FFmpeg\bin\ffmpeg.exe" -y      -i (input) -metadata title="(title) -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_nvenc -pix_fmt p010le     -tune:v hq -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -spatial_aq:v 0 -tier:v main -rc-lookahead:v 0 -gpu -1 -b_ref_mode disabled -profile:v main  -pass 2 -passlogfile "E:\temp\temp_4e67a83b907dab4a7dd6c088\pass_log_file_805748394bfa59308eb4" -2pass 1 -b:v 35000k -preset:v slow -hwaccel auto  -map_metadata -1 (etc. etc.)"

Option hwaccel (use HW accelerated decoding) cannot be applied to output url e:\temp\Jurassic Park III (2001)-fastflix-c
35f.mkv -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it
belongs to.
```

When I manually relocate it to the beginning, before the input file, it works:

```
"C:\Users\mobyg\AppData\Roaming\FFmpeg\bin\ffmpeg.exe" -y -hwaccel auto -i (input) -metadata title="(title) -max_muxing_queue_size 1024 -map 0:0   -c:v hevc_nvenc -pix_fmt p010le     -tune:v hq -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -spatial_aq:v 0 -tier:v main -rc-lookahead:v 0 -gpu -1 -b_ref_mode disabled -profile:v main  -pass 2 -passlogfile "E:\temp\temp_4e67a83b907dab4a7dd6c088\pass_log_file_805748394bfa59308eb4" -2pass 1 -b:v 35000k -preset:v slow -map_metadata -1 (etc. etc.)"
```

It should be added to the first pass command-line too.  Without it, on a test hdr 4k file on my setup, it runs at 32fps and burns up 60% total CPU, but added to the 1st pass, it runs at the same speed but with only 20% CPU.

**Comment by MobyGamer** [comment]
It should still be added, as decoding the source file is necessary to complete both a 1st pass and the 2nd pass, and my use case is recompressing h.265 HDR files to fit within a target bitrate.  "-hwaccel auto" drastically reduces CPU usage for supported source codecs in this case.

**Comment by forart** [comment]
> It should still be added, as decoding the source file is necessary to complete both a 1st pass and the 2nd pass, and my use case is recompressing h.265 HDR files to fit within a target bitrate. "-hwaccel auto" drastically reduces CPU usage for supported source codecs in this case.
>
Same needs here (we have to perform 4K HDR encodings with best possible quality @ 6000kbps), but hw DEcoding doesn't help mutch to be honest.

It would be really great to perform a full - not only decoding - HW-based 1stpass (= "analysis") to feed x265-2ndpass.
We don't know if is technically possible, but theoretically - if the encoders don't "break" the HEVC standard - it *should* be possible.

**Comment by MobyGamer** [comment]
You don't want a hardware ENcoding first pass for a software encoding second pass, because they have incompatible bit allocation strategies.  All passes of an N-pass encoding must be with the same encoder.

Even using x265, "-hwaccel auto" still helps, as it makes decoding of supported sources "free", giving more CPU time to the software encode.

**Comment by forart** [comment]
> You don't want a hardware ENcoding first pass for a software encoding second pass
>
Right, we would like to have 2-pass hw encoding.

> Even using x265, "-hwaccel auto" still helps, as it makes decoding of supported sources "free", giving more CPU time to the software encode.
>
Of course, we do always use that FFMPEG parameter in our x265 encodings, but - in our best machine, an i7-7700 - it perform very slow (compared to an "equal parameters" QSV encode on the same source material) anyway.

**Comment by MobyGamer** [comment]
As a data point, some more details on my usage and the background behind this request:  My use case as stated earlier is transcoding 4k HDR rips of my collection to stream to my TV via Plex.  My TV, an LG C8, has a processing power upper bound of about 60mbit/s when h.265 decoding occurs at the same time data is being transferred over the network (local files on a usb stick inserted into the TV don't exhibit this problem).  Since most UltraHD 4k files are 60-80mbps, most of them pause and skip when streaming directly to the TV.

My need for transcoding is not to obtain a high-quality replacement for the original files, but rather just a "best effort" that gets stored alongside the original to be switched to in case the original file has sections that exceed the processing bandwidth of my TV.  I own an RTX 3080 and leverage it for this in windows using the following arguments (line breaks inserted for formatting, not present in the batch file):

```
mkdir "Plex Versions\LG C8"

for %%a in ("*.*") do ffmpeg -find_stream_info -hwaccel auto -i "%%a" -map 0 -c copy -c:v hevc_nvenc -pix_fmt p010le \
-tune:v hq -preset:v p7 -color_primaries bt2020 -color_trc smpte2084 -colorspace bt2020nc -spatial_aq:v 1 -temporal_aq:v 1 \
-b_ref_mode middle -profile:v main10 -tier:v high \
-b:v 40M -maxrate:v 60M -bufsize:v 120M \
"Plex Versions\LG C8\%%~na.mkv"
```

(I suppose another feature request could be "can we have single-pass nvenc encoding, unless I missed that somewhere in fastflix?)

**Comment by MobyGamer** [comment]
Now that there have been several releases past the one where this issue was opened, I'm hoping that my feature requests can now more easily be implemented?

**Comment by cdgriffith** [comment]
Can now add that flag for ffmpeg nvenc in 5.5.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
