### ISSUE TITLE
FastFlix Duplicates encoding task and encodes same movie to infinity

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#327]
Hello,
I noticed a rather annoying bug, usually it happens when i have large list of encodes.
At one moment FastFlix would duplicate a task and keep re-encoding the same movie.
Lok at this screenshot, it duplicated <video 3>, after finishing it for the first time and from this point all it will do is keep re-encoding this movie to infinity or until i press pause Queue, then i can wait until he finishes, and manually cancel.

![163239187-52cf4f96-acf6-4b9f-8598-4eb3399e755c](https://user-images.githubusercontent.com/3275435/163312731-e8fe4840-c8cc-4690-aeef-0daf6ce262b4.png)

**Comment by cdgriffith** [comment]
Thanks for the heads up, I have had some other queue issues as well. I have gutted and replaced the current system with a fully file based one for time being in branch `feature/ignore-errors`. Hope to get that out in a week or so.

**Comment by Wontell** [comment]
> Thanks for the heads up, I have had some other queue issues as well. I have gutted and replaced the current system with a fully file based one for time being in branch `feature/ignore-errors`. Hope to get that out in a week or so.

Great, thank you.
Can you consider adding manual save to the queue system? Now it recovers automatically but what if it doesn't,  a button to save queue will be a nice addition.

**Comment by cdgriffith** [comment]
With the new mode, every time an interaction with the queue is made the file is written to. However that might be a nice option of "export/import queue"

That way you could possibly even design the queue on one system and just copy the queue file (or more likely compressed file with covers as well) to another system. Then on import it auto replaces the FFmpeg to use, and you would just say where the videos are on that system.

**Comment by cdgriffith** [comment]
Welp, that design didn't work. 

I'm adding a save / load queue feature as requested instead and re-writing the internal queue logic completely.

**Comment by cdgriffith** [comment]
I moved to a much simpler internal queue system. Basically instead of both the command runner and the frontend both having some state management of the queue itself, the command runner is now "dumb" and just run what is told by the UI. 

Should make this problem go away, if there are any more issues please re-open or recrate if it's different! https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0
