### ISSUE TITLE
Add Hardware VAAPI encoding support

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#329]
This is more difficult as basic things like scaling are [done differently](https://trac.ffmpeg.org/wiki/Hardware/VAAPI) with vaapi. Opening separate issue to track this and possible beta tries with this version.

**Comment by sourpatched** [comment]
@cdgriffith Let me know when you need to test VAAPI encoding as I'd be happy to help.

**Comment by sourpatched** [comment]
Any update on VAAPI support?

**Comment by cdgriffith** [comment]
Have not spent any effort on that yet myself.  Always looking for other contributors!

**Comment by marcscama** [comment]
hi,
i have a IGPU AMD 4800u.
If i want encode with vaapi and HEVC i use:

ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mkv -vf 'scale_vaapi=w=1920:h=800' -c:v hevc_vaapi -rc_mode CQP -qp 26 -c:a copy -strict unofficial output.mkv

i think for AMD a vaapi profile works so it's a good idea to add in the list.

Best regards.

**Comment by ojaksch** [comment]
+1 to see that coming to live. But I'm using 
`ffmpeg -vaapi_device /dev/dri/renderD128 -i INPUT -c:v hevc_vaapi -b:v 3000k -c:a aac -b:a 160k -c:s copy -map 0:v:0 -map 0:a:0 -vf format='nv12|vaapi,hwupload' OUTPUT`
with my AMD Ryzen 5 PRO 3400G / Vega 11, which should do the same as the example above.

**Comment by cdgriffith** [comment]
Finally added in 5.5.0! For HEVC, AVC, VP9 and MPEG2 https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
