### ISSUE TITLE
"Remove Metadata" only removes video metadata for Rigaya's hardware encoders

### ISSUE THREAD

**Issue by wynterca** [cdgriffith/FastFlix#330]
The "Remove Metadata" option doesn't seem to do anything the tool tip says removes titles etc?  I am usually encoding with NVencC, maybe that is not supported with that particular encoder?

**Comment by cdgriffith** [comment]
For the NVencC (and all rigaya's encoders) it will pass in `--video-metadata clear` vs `--video-metadata copy` ([their docs](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--video-metadata-string-or-stringstring)). I do need to fix that tool tip, as it doesn't remove titles as there is the "Title" field on the left hand side now to set / unset that. 

I just tried it, and seems to clear the Video Language, but doesn't clear container metadata (which is cleared when that option is selected with ffmpeg)  Looks like I need to also provide just [--metadata clear](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--metadata-string-or-stringstring) which I missed. Thanks for pointing it out!

**Comment by cdgriffith** [comment]
Updated to provide both in https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0, thanks for opening the issue!
