### ISSUE TITLE
NVEncC: Please add API v10 Quality presets: P1 to P7

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#331]
Hello,
If possible, please add P1 to P7, quality presets like FFMpeg has, but for NVEncC, its supported by the encoder.
This should allow more granular quality options.

https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#-u---preset

-u, --preset

Encode quality preset. P1～P7 preset is available from API v10.0.

    default
    performance
    quality

    P1 (= performance)
    P2
    P3
    P4 (= default)
    P5
    P6
    P7 (= quality)

P.S. BTW, NVEncC was updated to version 6.0 and now has 3D noise reduction feature, will be nice if its implement in the advanced page, sometime when you have time for it.
If you interested, search for --vpp-convolution3d, thats the command 
https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vpp-convolution3d-param1value1param2value2

**Comment by cdgriffith** [comment]
I was honestly thinking "there is no way there is that much of a gap between them you need that granulairty.  Did a quick test on a 1 minute 4K video on a 3060:

* Performance - 17 seconds
* Default - 20 seconds
* Quality - 56 seconds

So while there might not be a huge diff between P1 and P4, there is a huge gap between P4 and P7 apparently on the time scale (even if there is actual minimal quality difference.)  Easy enough to add, so thanks for pointing that out! 

Very interested to try out the noise reduction as well, thanks for bringing it to my attention!

**Comment by cdgriffith** [comment]
Added in https://github.com/cdgriffith/FastFlix/releases/tag/4.9.0
