### ISSUE TITLE
FastFlix Command Window always shows "qt.svg: Cannot open file" errors

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#332]
Hello,
Its probably nothing serious but it happens for me for every version of FastFlix i had. always during boot

qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_critical.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_critical.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_information.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_information.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_question.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_question.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_warning.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:message_warning.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_cancel.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_cancel.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_close.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_close.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_open.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_open.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_reset.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_reset.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_save.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_save.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_help.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_help.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_no.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_no.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_ok.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_discard.svg', because: The system cannot find the file specified.
qt.svg: Cannot open file 'C:/Program Files/FastFlix/dark:dialog_discard.svg', because: The system cannot find the file specified.

**Comment by cdgriffith** [comment]
Thanks for adding this to track it. Yeah the portable version has a hard time finding some of the theme files for some reason, doesn't affect functionality thankfully.

**Comment by Wontell** [comment]
> Thanks for adding this to track it. Yeah the portable version has a hard time finding some of the theme files for some reason, doesn't affect functionality thankfully.

Hi, this is normal full install version, not portable one, i just updated to latest version with FastFlix_4.9.0_installer.exe

**Comment by cdgriffith** [comment]
Fixed in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)!
