### ISSUE TITLE
Machine now sleeps during encoding

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#334]
Fastflix 4.8.1 and lower kept my machine from sleeping during encodes. With Fastflix 4.9.1, the application no longer keeps my machines from sleeping during encodes. Encodes appear to resume without issue after waking from sleep. 

This behavior happens on my laptop and desktop. I didn't use 4.9.0, so it could also be in that version.  I can work-around with power settings, but I did appreciate this option.

**Comment by cdgriffith** [comment]
That is definitely due to the new queue system with 4.9.0+  I have it set the command for it not to sleep during encodes still, but only for each command it runs. I didn't think it would chose to sleep in the second between command when there would still be some CPU usage ☹️  

Thanks for letting me know, I can change where that logic is run hopefully pretty simply, can work on that in the next few day!

**Comment by dongafford** [comment]
Thanks for jumping on these so fast. I was actually seeing the machine go to sleep _during_ the encode. 

I came back to say that when I did an uninstall / reinstall and cleared out the old log files, the cover files, and queue.yaml file the issue went away. I was seeing a message on one machine that the queue file was unusable and that's what sent me down this path. Maybe I had too many log files in there? I might have had close to 150 logs, ~50 temp folders, and 2600 cover files on one of the machines as I was doing a lot of extras encoding. 

I usually upgrade in place with the installer. This time I went from 4.8.1 to 4.9.1 directly. 

I will load up a bunch of Blu-Ray "extra" files tonight and see if I can cause it to sleep at some point. I'd say hold off on making changes until I let you know what I see tomorrow. I think clearing out the directory might have fixed it.

**Comment by dongafford** [comment]
OK. I have an issue where one of my machines will do whatever is in the After Conversion option box after every encode.

I have two machines I use to do encodes. My main encoding machine is a laptop with an AMD Ryzen 7 5000 series processor. That one seems to still show the issue. When it finishes an encode, it does whatever I have set in the "After Conversion" box. I had it set to hibernate after conversion and it diligently did that every time it finished a file. I set the After Conversion option to None and it appears to be working as advertised. This sounds like it may be related to your post. 

My other machine is a desktop with an i7 9700. I will use it from time to time for encoding. That machine did exhibit the issue I originally reported, but once I cleared everything out, it has stopped doing that. The After Conversion option behaves as expected and only does the action after the queue is completed. 

Let me know if you need me to check anything.

**Comment by dongafford** [comment]
Now I'm completely confused. I disabled the Windows power plan settings on my laptop to disable the computer going to sleep while plugged in and Fastflix encoded for about 3 hours then the computer went to sleep. In checking the logs, Fastflix started the encode, ran for 4 seconds, then the computer went to sleep. 

I have no after conversion steps. I'm going to finish the queue and then do a complete uninstall / reinstall wiping out the Fastflix directory under AppData. If that doesn't work, I'll drop back to 4.8.1

**Comment by cdgriffith** [comment]
>  I might have had close to 150 logs, ~50 temp folders, and 2600 cover files on one of the machines as I was doing a lot of extras encoding.

Holy cow. The temp folders and covers should be deleted when cleanly exiting the program, so that is worrying to hear. Can at least add a "cleanup temp folders" option in Help like there is "Cleanup old logs" option. 

As for the sleeping, my guess is that it detects "oh hey I can sleep!" after an encode, and starts the sleeping. So as the next one starts and says "hey don't go to sleep!" it's already too late and in the process of going to sleep as it starts up a few seconds in. 

Re-writing it to send that notice of "ok you can sleep" until after entire queue is done / pause encode is hit.

Thank you for all the details, makes life a lot easier on my end to think through things!

**Comment by dongafford** [comment]
I'll make sure to clean the old files out more often. I was doing a lot of small files over the last week or so. Those extras mean I'd do about 20-50 files in the timeframe where I would do one film. I'm not sure why mine weren't being deleted. I'm thinking it might be due to having just upgraded over and over from older versions.

That definitely makes sense about the "hey I can sleep" commands. I think your solution is a good one. 

Work's been crazy today, so I haven't had a chance to reinstall. I'll update you later. If there's anything that's a nice to have when reporting these issues, please let me know. 

I am enjoying the ignore errors option. I've found that when there is a title name or descriptive name on a track that has a double quote (") in it, FFMPEG (or Fastflix) doesn't like it. I've started converting these to single quote (') to fix the issue as I add the file, but I will sometimes miss those.

**Comment by cdgriffith** [comment]
Adding #336 to track the new cleanup option at some point, and #337 for the double quotes.

Hopefully fixing the core of these issues with 4.9.2 https://github.com/cdgriffith/FastFlix/releases/tag/4.9.2

Let me know if you run into any more issues with it! Thanks again for all the details!
