### ISSUE TITLE
Another Windows Defender false positive?

### ISSUE THREAD

**Issue by ahayes** [cdgriffith/FastFlix#341]
Similar to Issue #232 , I got an alert about `Win32/Uwamson.A!ml` related to FastFlix this evening:
![image](https://user-images.githubusercontent.com/1750076/166168604-d9feb68b-9fb3-454e-9cba-0f092d1883ef.png)

**Comment by cdgriffith** [comment]
Thanks for the heads up. I already paid their certificate extortion to try and avoid it the extra popups, but seems that anything packaged with PyInstaller becomes "poisoned" as soon as another malicious program is also packed with it. 

Anyone that can report it as a false positive when these come up would be appreciated. Can of course check with VirusTotal as well to get a better broad scan of anything suspicious. For example current release: 

Installer: https://www.virustotal.com/gui/file/8117c606ce6ab5eef6bea22cc7a510a5295b5c9edc86ad26e27327fb4d679251

Standalone: https://www.virustotal.com/gui/file/edefde2717c0b69d3d41cffa48482caecec081b662db95c99bdaba9e99206fe3

They each have just 2/3 out of 67 detections, but totally different ones, which shows a bit that it's how its packed into the exe with a multipurpose tool that other people use for nefarious reason that is causing the confusion.

**Comment by ahayes** [comment]
Thank you. That must be so frustrating. I told it to ignore and allow but I will keep an eye out for a way to flag as a false positive if I see it again. Unless you have a link people can use to report?

**Comment by cdgriffith** [comment]
This has hopefully not been flagged in recent times due to now buying the windows cert and increased usage showing it's a legit program. If it comes up again please let me know!
