### ISSUE TITLE
[Feature Request] live video input

### ISSUE THREAD

**Issue by sfahadshahzad** [cdgriffith/FastFlix#342]
Hi,

Hope you are doing well.

I would be great if live video input from decklink SDI / HDMI added for recording purposes.

Regards,

Fahad

**Comment by forart** [comment]
@sfahadshahzad: I don't think it's a desiderable - nor maintainable - feature to integrate inside an offline encoder GUI...

Check out projects like [Streamline](https://github.com/streamlinevideo/streamline) by @streamlinevideo instead.

**Comment by cdgriffith** [comment]
Long time for response, but yes better to use tools like that or OBS for real time streaming or recording
