### ISSUE TITLE
[Feature Request] Change the default priority of spawned tools

### ISSUE THREAD

**Issue by maxpiva** [cdgriffith/FastFlix#345]
Basically, a combo box that permits setting the default priority of the spawned programs by Fastflix.

IE: Realtime, High, Above Normal, Normal, Below Normal, Low.

My primary,  use case, is, on long encoding sessions, to get the computer more responsive, or if you use background services, prioritize that. So instead of normal, probably spawn FFmpeg with Below Normal Priority.

**Comment by forart** [comment]
I do believe that FF shold run in "administrator mode" to change its priority settings.

...an "elevate" button (like [FastCopy](https://fastcopy.jp/) has) could be needed too, then.

Anyway we're treferring to the Windows version ONLY...

**Comment by cdgriffith** [comment]
This should be possible cross platform with the toolset I am currently using, adding link for myself for later https://psutil.readthedocs.io/en/latest/index.html?highlight=priority#psutil.Process.nice

**Comment by cdgriffith** [comment]
New "Priority" drop down in the Queue panel with 5.0.0!
