### ISSUE TITLE
GUI Bug: FastFlix does not preserve the order of audio tracks when editing a queued job

### ISSUE THREAD

**Issue by bassner** [cdgriffith/FastFlix#346]
I usually add and order multiple audio tracks. When I try to edit an already queued job, it reimports my audio track configuration successfully, but does not preserve the order of audio tracks.

See screencast below.

https://user-images.githubusercontent.com/23171488/168804852-a7ac1bc2-f772-4396-81fc-57b5a25e3707.mov

**Comment by cdgriffith** [comment]
Good catch, had an overenthusiastic `sort` in there that didn't need to be. Fixed in [4.10.0](https://github.com/cdgriffith/FastFlix/releases/tag/4.10.0)
