### ISSUE TITLE
Custom Settings don't impact command Line

### ISSUE THREAD

**Issue by schlotkins** [cdgriffith/FastFlix#35]
HDR is going over, DTS can be converted to AC3 - I am a happy camper :)

With that said, it seems the custom settings don't work. So if I put the CRF to the default of 20 for 4k, I get this commad line:

"{ffmpeg}" -y -i "F:/Beautiful Day in the Neighborhood, A_t00.mkv" -map 0:0 -c:v libx265 -x265-params "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50):max-cll=(1264,211)" -crf 20 -preset slow -map 0:2 -metadata:s:1 title="Surround 5.1" -metadata:s:1 handler="Surround 5.1" -c:1 ac3 -b:a:1 576k   -map_chapters 0 "{output}"

If I change it to "custom" and then put in say "18," I get this:
"{ffmpeg}" -y -i "F:/Beautiful Day in the Neighborhood, A_t00.mkv" -map 0:0 -c:v libx265 -x265-params "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50):max-cll=(1264,211)" -crf 30 -preset slow -map 0:2 -metadata:s:1 title="Surround 5.1" -metadata:s:1 handler="Surround 5.1" -c:1 ac3 -b:a:1 576k   -map_chapters 0 "{output}"

no matter What I put in, I get -crf 30

I have the same issue with the bitrate. If I do custom, it just stays to whatever was in there last time.

Thanks,
Chris

PS - On the quality tab, it might be nice to not have the resolutions in there because then it seems like the program is going to downscale 4k rather than just change the CRF setting. I assume you mean those to be recommendations since I don't see any rescale parameters enter the FFMPEG code. For example, here is CRF 24:

"{ffmpeg}" -y -i "F:/Beautiful Day in the Neighborhood, A_t00.mkv" -map 0:0 -c:v libx265 -x265-params "hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc:master-display=G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50):max-cll=(1264,211)" -crf 24 -preset slow -map 0:2 -metadata:s:1 title="Surround 5.1" -metadata:s:1 handler="Surround 5.1" -c:1 ac3 -b:a:1 576k   -map_chapters 0 "{output}"

**Comment by cdgriffith** [comment]
Good spot! I think this is a GUI bug only, so if you actually did start an encode with those settings it would be proper, but the command page wasn't updating as it should. 

Fixing in 2.3.1 - (dev build with fix) https://ci.appveyor.com/project/cdgriffith/fastflix

And you are correct that everything in the parens are just suggestions for when to use what bitrate / crf. 
I didn't think about the angle how they might be thought of as scaling, will have to make that cleaner somehow.

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/2.3.1

**Comment by schlotkins** [comment]
All set!
