### ISSUE TITLE
[Feature request] - Please Add Option to Choose Default Open Tab

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#351]
Hello,
When working on many files like TV series and doing lots of copy pasting, will be easier if you consider adding an option to select Default tab.
Example, after pressing 'Add to Queue' button, the tab automatically switches to Encoding Queue, so when i drop a new file I need to click Audio tab to change the audio label, and when you do lots of file like TV series its time consuming and breaks the pase. But if I could select audio tab as default it the software would switch it automatically upon dropping new file, so all i need to do is copy paste the new label and press 'Add to Queue' button

Thank you and best regards.

**Comment by cdgriffith** [comment]
Have added a setting to disable tab switching! So whatever you left it on it should stay on https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0

**Comment by Wontell** [comment]
> Have added a setting to disable tab switching! So whatever you left it on it should stay on https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0

Thanks!
