### ISSUE TITLE
[Enhancement] Remember Last-Used Output Folder

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#352]
I've been using FastFlix for a while and I feel it would be a great improvement if last-used folders were remembered.  Another option might be to allow for user-configured paths to be defined in settings.

This would greatly improve workflow.

**Comment by cdgriffith** [comment]
huh, I still haven't added that to the setting page, thanks for heads up. In the FastFlix config file, can add a "output_directory" field with the directory you want as the default.

**Comment by mrdav1** [comment]
Thanks for the tip… much appreciated.

**Comment by mrdav1** [comment]
Sorry but I need a little more help... Where is the config file?  I changed the field in "FastFlix\fastflix\models\config.py" but it made no difference.

**Comment by flixtor** [comment]
Hello sir.

It'a working nice, both with input and aoutput folder under Linux, but I can not get it to work in windows,
Can you provide a simple exsample ?

In linux I do : output_directory: /mnt/name of my mount
or output_directory: /home/finnish_movies

As told, working great!

On win: output_directory: d:\output

I have even tried with d: alone, don't work but gives errors here.

Thanks for great app!

**Comment by cdgriffith** [comment]
Have added this to the settings page now so you can set a default output folder https://github.com/cdgriffith/FastFlix/releases/tag/4.10.0
