### ISSUE TITLE
Macbook M1

### ISSUE THREAD

**Issue by Nhunz** [cdgriffith/FastFlix#354]
Is there a version of FastFlix that will run on the Apple M1 chip?

Thanks

**Comment by cdgriffith** [comment]
I won't be able to build specific packages for it unless github actions supports it https://github.com/actions/virtual-environments/issues/2187

But I beleive other have had luck building it for source on the M1 - https://github.com/cdgriffith/FastFlix#running-from-source-code

**Comment by user334** [comment]
Just so you know, Apple Silicon runners are now available from GitHub actions: 
https://github.com/actions/runner-images/issues/2187#issuecomment-1743277255
https://github.com/actions/runner-images/issues/8439

**Comment by cdgriffith** [comment]
Thanks for the update @user334 ! I am adding support for the M1 with mac-14 in next version, testable https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
