### ISSUE TITLE
[REQ] --adapt parameters settings for QSVEnc

### ISSUE THREAD

**Issue by forart** [cdgriffith/FastFlix#357]
In @rigaya 's [QSVenc latest versions](https://github.com/rigaya/QSVEnc/releases/), many improvement quality parameters has been added:

https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.en.md#--adapt-ref=

Hope that inspires !

**Comment by cdgriffith** [comment]
Adding the adapt params in 5.5.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
