### ISSUE TITLE
How to change the encoding container?

### ISSUE THREAD

**Issue by Begemotoid** [cdgriffith/FastFlix#358]
Currently, encoding is available only in the MKV container. But I need an MP4 container.

**Comment by cdgriffith** [comment]
On the Output line, just change it to `.mp4` instead of `.mkv`, it will give a warning, but you can chose to continue with it.  Closing this one as it's a dup of https://github.com/cdgriffith/FastFlix/issues/100 request to be able to have an easier way to change output type.
