### ISSUE TITLE
x265 parameters not recognized

### ISSUE THREAD

**Issue by zorrax2b** [cdgriffith/FastFlix#361]
Hi
I used your soft since few days but I have some problem with x265 parameters. 
using additional x265 params, i tried to activate several params : 
ref=5:deblock=1,1:subme=7:scenecut-aware-qp=3:ipratio=1.30:pbratio=1.20:aq-mode=4:aq-strength=0.70:psy-rd=1.5:qblur=0.6: qcomp=0.80:tu-inter-depth=4:tu-intra-depth=4:limit-tu=4:max-merge=5:aud:hrd:rc-lookahead=60:lookahead-slices=1:amp:limit-refs=2:no-limit-modes:weightb:no-sao:early-skip:rskip-edge-threshold=0.05:b-intra:vbv-init=0.9:min-vbv-fullness=50.0:max-vbv-fullness=80.0:sar=0:chromaloc=0:level-idc=5.1:selective-sao=0

but I got this message for few of params:
[libx265 @ 0000021fd9bb4a40] Unknown option: aud:hrd:rc-lookahead.
[libx265 @ 0000021fd9bb4a40] Unknown option: traditional-scenecut:amp:limit-refs.
[libx265 @ 0000021fd9bb4a40] Unknown option: no-limit-modes:weightb:no-sao:early-skip:rskip-edge-threshold.
[libx265 @ 0000021fd9bb4a40] Unknown option: b-intra:vbv-init.

is it normal ?

**Comment by cdgriffith** [comment]
Closing as there hasn't been a follow up, let me know if you're still having issues!
