### ISSUE TITLE
Recent change in encoding speed

### ISSUE THREAD

**Issue by bmcassagne** [cdgriffith/FastFlix#363]
So I bought a new laptop recently with an Intel i9-12900H processor.  Initially the performance seemed really good, but then later I did another decode that went much slower.  Obviously I'm talking about software encoding.  

So a couple of things I've noticed is that the encoding is much faster if I use version 4.6.0 instead of 4.10.0.  I'm using the slow quality setting and I've tried CRF19-21 with the same results.  Also I'm getting significantly different speeds depending on the movie I'm encoding.  I've never noticed this before.  With 4k videos I seem to get 3-5 fps with 4.6.0, but with 4.10.0 I've seen as low as 0.9 fps.   Another thing that's really strange is that when it was running really slow my processor usage was only showing about 30% in windows task manager.  Typical seems to be 70-80% usage, which also seems odd.  On my other computer with a Ryzen 7,  my processor usage was always at 98-100% while encoding.

**Comment by cdgriffith** [comment]
Hi @bmcassagne, can you please provide example Raw Commands that were generated and run between the two versions that had such a speed difference with the same video?

**Comment by cdgriffith** [comment]
Also make sure you are using latest master build of FFmpeg. Older versions have issues using intel's new architecture with the P/E cores, which could explain the issues and low cpu usage.

**Comment by bmcassagne** [comment]
I'm using the ffmpeg that was downloaded automatically but I'll look for
the master build. Also the CPU was at 70-80 C, well below the temp limit of
100 C.   I'm going to experiment more tonight. I used the default profile
wirh out any manual parameters to avoid possible issues. I'm getting about
3 fps this time with 4.10.0, so that may have helped some. I've never added
any manual parameters but I was using profiles from an older version.

**Comment by cdgriffith** [comment]
Changing this over to a discussion https://github.com/cdgriffith/FastFlix/discussions/444 as an FYI to merge multiple issues and hopefully make it easier for people to comment on it.
