### ISSUE TITLE
[Feature Request] H.265 / HEVC all-intra

### ISSUE THREAD

**Issue by DesertCookie** [cdgriffith/FastFlix#366]
There is no `main10intra` profile for H.265. Would it be possible to add the intra-profiles to allow for all-intra encoding?

**Comment by cdgriffith** [comment]
There was apparently a few I was missing. So I added all of them. Thanks for the idea @DesertCookie ! 

- main
- main10
- mainstillpicture
- msp
- main-intra
- main10-intra
- main444-8
- main444-intra
- main444-stillpicture
- main422-10 
- main422-10-intra
- main444-10
- main444-10-intra
- main12
- main12-intra
- main422-12 
- main422-12-intra
- main444-12 
- main444-12-intra
- main444-16-intra 
- main444-16-stillpicture
