### ISSUE TITLE
VCEEnc Forces 8Bit + Mission Options

### ISSUE THREAD

**Issue by Wontell** [cdgriffith/FastFlix#368]
Hello Dev,
How are you these days?
Hope you are doing well.

I just moved from Nvidia to AMD and noticed many missing options in the AMD coder that exist in the nvidia encoder but the main issue is that 8Bit is always enabled and no options to change it  to 10bit [for example I encode 8Bit bluray SDR rips to 10Bit for increased quality vs compression]

So I compared NVENC and VCEenc FastFlix pages and from the official encoder page made a list of missing options that available on FastFlix NVenc, and AMD options that will be nice to have.

Also right now FastFlix detects Color, matrix transfer etc. and sets properly in the command line.
But there is Auto option to do it automatically by the encoder, maybe to avoid mistakes its better to set it to auto? Its up to you to decide of course. [I copied settings at the bottom of the message]

**8/10 Bit:**
--output-depth 
8 ... 8 bits (default)
10 ... 10 bits

**B-pyramid**
--b-pyramid
Enable b-pyramid feature.

**LTR Frames**
--ltr <int>
Set the long term reference mode.

And these Settings

--pa-sc <string>
Sensitivity of scenechange detection. (default: medium) none, low, medium, high

--pa-ss <string>
Sensitivity of static scene detection. (default: high) none, low, medium, high

--pa-caq-strength <string>
Content Adaptive Quantization (CAQ) strength. (default: medium) low, medium, high

--enforce-hrd
Enforce hrd compatibility of bitstream.

**Range settings:**
--colorrange <string>
"auto" will copy characteristic from input file (available when using avhw/avsw reader).
limited, full, auto

--colormatrix <string>
"auto" will copy characteristic from input file (available when using avhw/avsw reader).
undef, auto, bt709, smpte170m, bt470bg, smpte240m, YCgCo, fcc, GBR, bt2020nc, bt2020c

--colorprim <string>
"auto" will copy characteristic from input file (available when using avhw/avsw reader).
undef, auto, bt709, smpte170m, bt470m, bt470bg, smpte240m, film, bt2020

--transfer <string>
"auto" will copy characteristic from input file (available when using avhw/avsw reader).
undef, auto, bt709, smpte170m, bt470m, bt470bg, smpte240m, linear,
log100, log316, iec61966-2-4, bt1361e, iec61966-2-1,
bt2020-10, bt2020-12, smpte2084, smpte428, arib-std-b67

Thank you and best Regards

**Comment by cdgriffith** [comment]
Bit depth: Yup, good idea to have a way to manually set that!

Color matrix / primaries / transfer: Are manually detected and set to what was detected, but can always be set in the "Advanced" panel to "Unspecified" and then will revert to "Auto"  (not something looking to tackle / change currently. But not opposed to auto being default for hardware encoders either.) 

I don't see any reason not to all all the others you suggest as well, just got to get around to it, thanks for opening the ticket!

**Comment by cdgriffith** [comment]
Added all the PA options in 5.5.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
