### ISSUE TITLE
Name change: hdr10plus_parser is now hdr10plus_tool

### ISSUE THREAD

**Issue by rharmonson** [cdgriffith/FastFlix#374]
Please update settings and other UI items referencing hdr10plus_parser to hdr10plus_tool. Also, https://github.com/cdgriffith/FastFlix/wiki/HDR10-Plus-Metadata-Extraction.

You can verify the name change at https://github.com/quietvoid/hdr10plus_tool.

Love fastflix. Thank you.

**Comment by cdgriffith** [comment]
Gah, was about to close this and call complete, but just noticed after release that in the config doesn't auto look for the new name, everywhere else changed.   Guess this will go in one of the first bugfixes!

**Comment by chreds** [comment]
> Gah, was about to close this and call complete, but just noticed after release that in the config doesn't auto look for the new name, everywhere else changed. Guess this will go in one of the first bugfixes!

@cdgriffith I think you fixed this in 5.1.0, probably can close -> resolved this issue now.

**Comment by cdgriffith** [comment]
Thanks for heads up, finally added proper attribution in the change log in next upcoming version so closing this now
