### ISSUE TITLE
Feature request: enable disposition so user can change default track

### ISSUE THREAD

**Issue by markmarz** [cdgriffith/FastFlix#379]
Excellent utility, thanks!

Please consider adding support for ffmpeg disposition option for tracks. If it were an option, I could specify which audio track (for example) is the default.

`-disposition:a:0 default -disposition:a:1 none -disposition:a:2 none `

Thanks!
Mark M.

**Comment by cdgriffith** [comment]
Adding audio dispositions in 5.5.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
