### ISSUE TITLE
HEVC nvenc profile

### ISSUE THREAD

**Issue by draco1544** [cdgriffith/FastFlix#381]
What is the difference between P7 and quality in nvenc HEVC encoding ?

**Comment by cdgriffith** [comment]
My apologies that I totally missed this question! 

```
-u, --preset

Encode quality preset. P1～P7 preset is available from API v10.0.

    default
    performance
    quality
    P1 (= performance)
    P2
    P3
    P4 (= default)
    P5
    P6
    P7 (= quality)
```

They are actually the same, just different verbiage. https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#-u---preset
