### ISSUE TITLE
Support for AMF 1.4.26

### ISSUE THREAD

**Issue by GlitterKill** [cdgriffith/FastFlix#385]
A few months ago a new AMF version was released that improves the quality of H264 encodes.  Will this app include these updates?

[https://github.com/GPUOpen-LibrariesAndSDKs/AMF/releases/tag/v1.4.26](url)

**Comment by cdgriffith** [comment]
Hi @GlitterKill, FastFlix is just a GUI wrapper around encoders. So for example doing H264 encodes with AMD using VCEEnc, you'll need to make sure you download and link to the latest version of that in Settings (first one that supports 1.4.26 is 7.03, but would grab latest https://github.com/rigaya/VCEEnc/releases )

It's a bit more complicated to figure out for the FFmpeg version of the encoder, as you have to lookup who built it and how they compiled it. But looking at BtbN (the default download for FastFlix), it seems they are linking to latest AMF in their code base, so should be good there as well. https://github.com/BtbN/FFmpeg-Builds/blob/0c02e8fe66d8def2ff34de52f244789609f78d9a/scripts.d/50-amf.sh
