### ISSUE TITLE
-threads option not passed to ffmpeg

### ISSUE THREAD

**Issue by jdevrie** [cdgriffith/FastFlix#386]
I am using svt av1 encoder and I am putting in the -threads 20 option in to the quality tab field called "custom ffmpeg options". However I do not see the 100% cpu usage like when I use ffmpeg from the commandline.  Also I do not see the warning that using more than 16 threads is not  recommended. So i suppose the option is never passed to ffmpeg. 
I discovered I have svtav1 version "SVT-AV1 Encoder Lib v1.2.1-70-ge7e99798"which might be the reason I am getting 100% cpu when using ffmpeg from the command line. I am getting way more fps processed from the command line. 31 versus 6,5  from fastflix.

**Comment by cdgriffith** [comment]
Looks like SVT-AV1 doesn't respond to the ffmpeg `-threads` option, have to pass `lp=<threads>` in the additional svt-av1 params section instead.   https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Parameters.md#1-thread-management-parameters

**Comment by jdevrie** [comment]
Well! Even with 20 threads AV1 encoding takes forever in ffmpeg because it is done is software. I just wait untill some packages start to support hardware AV1 encoding (e.g. with the latest NVIDIA NVENC on the latest RTX40nn video cards) to speed up this process. In  the meantime I just stick to HEVC/H265 in Premiere pro. :-)
