### ISSUE TITLE
Bitrate HEVC is broken in 2.3.1

### ISSUE THREAD

**Issue by schlotkins** [cdgriffith/FastFlix#39]
I'm sure you are sick of me, but in the 2.3.1 version switching to bitrate in HEVC does not seem to work. The command line page shows just the single pass CRF code and then encoder gives a location not found error.

This was working in one builds you had me test so I think it's probably something easy.

Thanks,
Chris

**Comment by cdgriffith** [comment]
You kidding, it's great to get feedback and improve stuff I miss! 

Location not found is a weird issue I didn't see, but did fix two related things, so if it's still not working in 2.3.2 let me know and can re-open this
