### ISSUE TITLE
Wrong scale and behavior for DPI 250%

### ISSUE THREAD

**Issue by smtad** [cdgriffith/FastFlix#390]
My DPI is 250%. 
When I run FastFlix, the FastFlix window is larger than my screen. Then if I tried change the size of FastFlix window, it disappeared!

**Comment by cdgriffith** [comment]
What OS are you running on, and with what resolution? 

Does updating to the latest 5.0.0 help (updated GUI engine)

**Comment by cdgriffith** [comment]
Thanks for the additional details. Looking into this more it seems to be something with how it's built on github. Locally running it, or building it into an exe, those all remain fine. However, using the exe generated from github actions also exhibits that same behavior for me. 

Left is locally built, right is from github

![dpi issues](https://user-images.githubusercontent.com/3275435/205444511-4c148ec5-5383-4b16-bb68-f680760bc92d.png)

Going to have to start digging into the logs or something to try and find what's different

**Comment by cdgriffith** [comment]
Fixed in [5.1.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.1.0)

Setting a hardcoded font size seemed to be the only way to fix it
