### ISSUE TITLE
Nvenc AV1 encoding

### ISSUE THREAD

**Issue by draco1544** [cdgriffith/FastFlix#393]
Hi !

Can you add the support of av1 nvenc encoding ?

**Comment by cdgriffith** [comment]
It is being added for next major version, there are development versions being dropped on the fastflix discord as a heads up!

**Comment by cdgriffith** [comment]
[Added in 5.0.0!](https://github.com/cdgriffith/FastFlix/releases/tag/5.0.0)

100% Untested as I don't have a new card, raise any issues you find please, would be greatly helpful!
