### ISSUE TITLE
LibOpus audio converting issue

### ISSUE THREAD

**Issue by marcelospera** [cdgriffith/FastFlix#397]
Hi! I am using version 5.1.0 but I've found some problems. When I select AV1 AOM with bitrate of 1200 kbps for video and Libopus audio option with downmix to stereo 128 kbps  the audio is converted to Opus but not downmixed and uses 640kbps. And video's final bitrate is about 650kbps and not the 1200kbps I've selected.
Looks like it added 1200 kbps for video and 128 kbps for audio and the resulting 1330 kbps was the overall bitrate. If the audio used 640 kbps of this, the video was forced to use the rest. I don't know...

Thanks.

**Comment by cdgriffith** [comment]
Sorry I never commented on this, I have tested with upcoming version 5.8.0 and do not see these issues when encoding with those settings anymore. Not sure if from ffmpeg or encoder updates or anything I did. Hopefully it's working for you now!
