### ISSUE TITLE
audio disabled when editing queue item

### ISSUE THREAD

**Issue by philblue1** [cdgriffith/FastFlix#398]
When using the edit button of an queue item the audio track is disabled.
```
FastFlix 5.1.0
Windows
```

**Comment by dongafford** [comment]
I have noticed this issue as well. When you edit the item in the queue, it will disable audio and subtitles. You will need to re-enable them on those tabs.

**Comment by dongafford** [comment]
Hi, Chris. 

Thanks for fixing this and sorry to bring this old item back to life. I noticed this bug also affected the cover image selection (Copy Cover) on the Cover tab. I'm not sure how close you are to 5.2.0, but I wanted to make sure that your fix covered this as well. If not, I'm sure we'll see it in a later version.

Thanks again.

**Comment by cdgriffith** [comment]
Thanks for bringing it up! Didn't notice that, adding separate ticket to make sure I don't lose it.

**Comment by cdgriffith** [comment]
Fixed in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)!
