### ISSUE TITLE
Best way to detelecine DVDs?

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#402]
I've been struggling with getting DVD encodes to work correctly. Fastflix will determine that the incoming file is interlaced and check the Deinterlace box. If I leave the Output FPS as default, I will get a 30FPS video with some hitching as frames are duplicated. If I specify 23.976 as the output frame rate, things line up, but I get artifacting on fine lines (jaggies). 

Is there a dedicated way to invoke a detelecine function like Handbrake uses? I can't figure out how to enable this functionality. I can be a test subject if you need one.

Thanks!

**Comment by cdgriffith** [comment]
I imagine what is happening is the frame rate filter is happening before the deinterlacer so it's getting a little messy. (All speculation, but hopefully easiest to test) 

You will have to manually edit / run the ffmpeg command at the moment to test this.  In the raw command, you should see `-filter_complex "[0:0]yadif[v]" ` as part of it, as well as a `-r 23.976` after it somewhere. 

Change that to: 

```
-filter_complex "[0:0]yadif=mode=1,framerate=fps=23.976[v]" 
```

and remove the `-r 23.976`. This will run the deinterlacer in a mode that it actually doubles the framerate, and that just gives it more frames to better cut down too.

**Comment by dongafford** [comment]
Hi, Chris. 

That works MUCH better. The filter complex after the change for the file I'm encoding is:

-filter_complex "[0:0]yadif=mode=1,framerate=fps=23.976[v]",crop=652:466:24:8[v]"

I've also removed the -r 23.976 from the batch file. I assume that's put in there by the Output FPS parameter, so I won't set that. Thanks for the assistance.
