### ISSUE TITLE
Copy video track title information from input file

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#409]
Hi. Currently FastFlix doesn't copy the title information ('Name' field for the video track in MKVToolnix) when encoding files. I would like to see if this data could be copied if it exists. I have to manually remux files to get this information back into the encoded file once FastFlix has completed the encode. 

Currently FastFlix will copy this information for the Audio and Subtitle tracks. 

Thanks

**Comment by cdgriffith** [comment]
Yeah I got rid of that field in 5.2.0 beta to save space up there then...forgot to add it back anywhere. Thanks for the ticket!

**Comment by dongafford** [comment]
Hi, Chris. I haven't tried this in the 5.2.0 beta. I'm still running 5.1.0. Not sure if you tried it yourself and it's still broken.

**Comment by cdgriffith** [comment]
Ohh, make sure you don't have "remove metadata" selected on the right hand side, and I think it should copy then

**Comment by dongafford** [comment]
Hi, Chris. 

I tested this issue with the 5.2.0 beta. You are correct, I no longer see the 'title' field in the top area of the window. That has been useful for me in the past (edit a typo), but usually I've configured that field correctly before I get to the FastFlix step. 

I tested the encode with an "extras" file (documentary included with a disc), and I'm seeing the same behavior. The "name" goes away for the video track. I've included screenshots from MKVToolnix GUI.

Please let me know if you want me to test anything. 

![Original File](https://user-images.githubusercontent.com/5377128/219478107-d650385f-34e8-4b0f-9a48-004f4efea20c.jpg)
![After Encode](https://user-images.githubusercontent.com/5377128/219478122-ea0f7869-bd85-4ec7-873e-265b9389452f.jpg)

**Comment by dongafford** [comment]
Running the 5.2.0b1 Beta.

I ran the encode twice with remove metadata unchecked and still saw the same behavior. The name value for the video track is cleared. The name value in the audio track is the same as the source file

I was trying to figure out how to make the remove metadata option the default, but it's not bubbled up in the GUI. I closed the GUI down and edited the YAML file to set remove_metadata to false. I saved it and went into FastFlix and the Remove Metadata box is selected by default. 

I loaded a new source and it stayed selected. I chose a different profile, then back to my profile in the YAML file and it kept the setting checked. If I uncheck it and Add to Queue, the checkbox checks itself (but greyed as I don't have a source file loaded). When I load a new source file with my profile active, the option stays checked until I uncheck it.

**Comment by cdgriffith** [comment]
Could you check if you load that video into FastFlix and look at the Source Details page, if you could copy in the output could help make sure I am copying the right thing. 

The example I have looks like it might be storing title under `HANDLER_NAME` in the tags, want to make sure that is the case.

```
tags:
  language: eng
  HANDLER_NAME: VideoHandle
```

**Comment by cdgriffith** [comment]
Not most elegant solution, and no way to put them in profile yet, but do have a way to at least change them and should auto passthrough on the Advanced page now (didn't have video to test regular title with tonight, but video track handler name goes through)  https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0b2

**Comment by dongafford** [comment]
Hi, Chris. 

Sorry for the late response. It was patching weekend and things went sideways :-)

I don't have the file I was referencing before, but I have another one I was working on. The source details are attached. I found the title under the **tags:** section. Here's a snippet of the output:

tags:
language: eng
**title: Merrily We Go to Hell - Film Historian Cari Beauchamp Interview**
BPS-eng: '31064561'
DURATION-eng: 00:26:33.592000000
NUMBER_OF_FRAMES-eng: '38208'
NUMBER_OF_BYTES-eng: '6188029598'

[Source Details.txt](https://github.com/cdgriffith/FastFlix/files/10835176/Source.Details.txt)

It seems a bit random as to this working or not. I think about 5% of the time I get a transfer of the title to the new file. 

As soon as my queues are completed, I'll switch over to 5.2.0b2 and check that version. 

Thanks again.

**Comment by dongafford** [comment]
I just finished encoding the file referenced above with 5.2.0b1. It copied the title information into the new file.

**Comment by dongafford** [comment]
OK. I found one that didn't work with 5.2.0b1. Source details and Raw Commands are attached below. I encoded 4 other files from this directory / movie. The title information from those copied over.

There are a lot of commonalities between what does and doesn't work. The only thing that looks weird about the title is it has two dashes in the title. 

tags:
  language: eng
  **title: Luca - Summer -- English Teaser Trailer**
  BPS-eng: '20764806'

[Source Details.txt](https://github.com/cdgriffith/FastFlix/files/10835351/Source.Details.txt)
[Raw Commands.txt](https://github.com/cdgriffith/FastFlix/files/10835360/Raw.Commands.txt)

I'll try this with 5.2.0b2 soon.

**Comment by dongafford** [comment]
Here's another one. Two files, same directory. 
This one's title didn't transfer:
[Mad Max 2-  The Road Warrior - Leonard Maltin Introduction Source Details.txt](https://github.com/cdgriffith/FastFlix/files/10835392/Mad.Max.2-.The.Road.Warrior.-.Leonard.Maltin.Introduction.Source.Details.txt)

This one did:
[Mad Max 2-  The Road Warrior - Theatrical Trailer Source Details.txt](https://github.com/cdgriffith/FastFlix/files/10835396/Mad.Max.2-.The.Road.Warrior.-.Theatrical.Trailer.Source.Details.txt)

I thought it might be special characters, but these both have colons in the title.

**Comment by dongafford** [comment]
OK. This did not work with 5.0.2b2, but did work with 5.2.0b3. 

I tested this with both files that had an issue with 5.2.0b1 and both had the title information in the output file.

**Comment by cdgriffith** [comment]
As an update I did a bit of a tweak with latest beta 4 to specifically only copy `title` and not video handler any more, so if that breaks any of your flows please let me know!

**Comment by cdgriffith** [comment]
Added in [5.2.0](https://github.com/cdgriffith/FastFlix/releases/tag/5.2.0)!
