### ISSUE TITLE
Allow audio track to be forced in output file

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#410]
Hi. Currently FastFlix allows for forced subtitle tracks but we don't have this ability for audio tracks. I have many files with multiple audio tracks and there are a lot of players that force the "native" language as the default. On foreign films with English language commentary tracks this leads to the commentary playing by default. 

Is there a way to have a selection where one of the tracks could be labeled as forced or default- similar to the way the subtitle track 'disposition' dropdown works? I realize this might hurt the simplicity of the UI and I would be willing to use a submenu if needed. I realize there might be other disposition settings others would appreciate, but I really only want forced for my purposes to make sure the correct track plays.

Thanks.

**Comment by cdgriffith** [comment]
Added audio dispositions in 5.5.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.5.0
