### ISSUE TITLE
[Question] speed up av1 encoding

### ISSUE THREAD

**Issue by marcscama** [cdgriffith/FastFlix#412]
hi,
i have many question but in general my purpose is encoding faster with av1 encoders.
with a IGPU AMD 4800u i have a strange vaapi behaviour:
 i can decode a 8k av1 file with hardware vaapi support...
ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i input.mp4 -f null -
 but for vainfo i don't have this support.

1) it's possible to encode from av1 to hevc or scale with some vaapi filters to av1?

2) fastflix is faster with external encoders like av1an or some av1 binary encoders?

3) wich encoders is faster in the 2023?

best regards 
Marks

**Comment by cdgriffith** [comment]
Hi Marks!

> i can decode a 8k av1 file with hardware vaapi support...

The AMD 4800u doesn't have hardware AV1 decode or encode support, so I think it is just falling back to using software

> it's possible to encode from av1 to hevc 

Yes you can take a AV1 video and encode it back to HEVC with any HEVC encoder like x265 or vaapi on supported hardware. 

> or scale with some vaapi filters to av1?

No, to transform it into another format always requires an encoding. The only hardware that has support right now is Intel Arc, AMD 7xxx series and Nvidia 4xxx GPUs. And I do not know if `vaapi` has caught up with av1 yet, possibly. 

> fastflix is faster with external encoders like av1an or some av1 binary encoders?

The fastest you can get it always hardware. So one of the above mentioned GPUs paired with one of Rigaya's encoders https://github.com/cdgriffith/FastFlix/wiki#hardware-encoders can be done in FastFlix itself. 

Second fastest will be `av1an` as it can split up a file to work on multiple chunks at a time, which FastFlix does not support but there are other GUIs for it out there. 

> wich encoders is faster in the 2023?

Again Hardware is fastest, but if talking about software that's a hot debate. I find SVT-AV1 to be the best mixture of speed vs quality. The "fastest" possible would be comparing their "real time" speeds meant for streaming, not encoding, so straight up looking for the fastest is a bad idea IMO. 

Here are some benchmarks from a while back comparing them, I don't know of one that is more up to date https://not.cafe/2021/06/01/an-up-to-date-av1-benchmark.html

**Comment by marcscama** [comment]
Thank you very much
