### ISSUE TITLE
5.2.0b3 - Creation of profiles gives "Profile cannot be saved! Unknown encoder type."

### ISSUE THREAD

**Issue by dongafford** [cdgriffith/FastFlix#417]
This occurs with both the portable and installed version of FastFlix.

From the application window: fastflix[29400] ERROR Profile cannot be saved! Unknown encoder type.

I had issues deleting profiles with the GUI with 5.2.0b1. As with this issue, I could manually edit the yaml file. I was able to add new profiles with 5.2.0b1 and 5.2.0b2 through the GUI without issue.

**Comment by dongafford** [comment]
This occurs with both the portable and installed version of FastFlix. 

From the application window: fastflix[29400] ERROR Profile cannot be saved! Unknown encoder type.

I had issues deleting profiles with the GUI with 5.2.0b1. As with this issue, I could manually edit the yaml file.  I was able to add new profiles with 5.2.0b1 and 5.2.0b2 through the GUI without issue.

**Comment by cdgriffith** [comment]
Totally missed this for 5.2.0b4, will be fixed with next beta! Thanks for reporting!
