### ISSUE TITLE
Custom resolution!

### ISSUE THREAD

**Issue by AlisaFmla** [cdgriffith/FastFlix#419]
In versions 5.2.0b3, the ability to set the custom resolution that was in previous versions has disappeared! Fastfix differed from the others in that it was possible to set a custom resolution! I always encode a video from my smartphone into an anamorphic video, because it's not of the best quality. These are resolutions: 1440 * 1080 pixels, 1280 * 1080 pixels, etc,  with an aspect ratio of 16 by 9! Please return the custom resolution!

**Comment by cdgriffith** [comment]
Added back in for the 5.2.0 release! Now has a custom option you can specify
