### ISSUE TITLE
Version 5.2 does not run

### ISSUE THREAD

**Issue by Bandid0** [cdgriffith/FastFlix#426]
Hello 
I just did a clean install and when you run the program it closes automatically.
Thank you for your work

**Comment by cdgriffith** [comment]
hi @Bandid0, what operating system?

In windows logs are stored in C:\Users\<your user name>\AppData\Roaming\FastFlix\logs  (I think you can get to app dirs by typing %AppData% into the windows bar in the file explorer).  Look for the latest gui log and past it's content here please!

**Comment by Bandid0** [comment]
The version that I am using is Windows 11, I have tried to install it also in a virtual machine with Windows 10, the exact same thing happens. No log is generated.
The only way I've gotten it to work is to install an older version first and then the 5.2

**Comment by cdgriffith** [comment]
Thank you for letting me know of this issue, should be fixed in https://github.com/cdgriffith/FastFlix/releases/tag/5.2.1
