### ISSUE TITLE
Misssing VVC option

### ISSUE THREAD

**Issue by BuyMyMojo** [cdgriffith/FastFlix#434]
**Describe the bug**
There is no option to use the new VVC codec added in 5.2.0.
I am using the latest Windows 11 version, FFMPEG build from BtbN and FastFlix version

I know this is probably just the FFMPEG build not having VVC encoding for some reason so if that is the case a description of where to get/how to build FFMPEG with support would be helpful.

`G:\tools\ffmpeg.EXE -hide_banner -encoders` does show VVC as not having encode or decode support which is why I am asking for updated info on where to get FFMPEG.

```
..V.L. vvc                  H.266 / VVC (Versatile Video Coding)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the latest `-win64-gpl` FFMPEG version from BtbN
2. Install the latest FastFlix version and run

**Screenshots**
![FastFlix_oxQupgA8xp](https://user-images.githubusercontent.com/46948241/224456696-5e416448-3eb8-4ffc-90c7-576306c58a25.png) ![FastFlix_72aVwAx1Ne](https://user-images.githubusercontent.com/46948241/224456700-d58057b3-d94f-4936-b04c-5722503db68d.png)

![image](https://user-images.githubusercontent.com/46948241/224456787-437d837f-c0b4-4097-bfb7-6d06bd22e913.png)

![image](https://user-images.githubusercontent.com/46948241/224456869-10821122-ae41-4376-95f8-ac265c07ba5d.png)

**Comment by cdgriffith** [comment]
Correct, need a ffmpeg with that enabled: https://github.com/cdgriffith/FastFlix/discussions/425#discussioncomment-5256514
