### ISSUE TITLE
Unable To Start FastFlix 5.2.3

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#436]
On starting the above on Windows 10 the following appears:

_Traceback (most recent call last):
  File "fastflix\entry.py", line 14, in <module>
    import fastflix.language  # Have to set language first thing
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "fastflix\language.py", line 29, in <module>
    config = Path(user_data_dir("FastFlix", appauthor=False, roaming=True)) / "fastflix.yaml"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "appdirs.py", line 81, in user_data_dir
  File "appdirs.py", line 480, in _get_win_folder_with_pywin32
ImportError: Module use of python310.dll conflicts with this version of Python.
Could not load FastFlix properly!
Please report this issue on https://github.com/cdgriffith/FastFlix/issues (press any key to exit)_

**Comment by cdgriffith** [comment]
That seems like some file conflict, like the last version wasn't fully uninstalled properly (possibly still running when tried to uninstall it?) 

I would suggest running the new installer again, making sure FastFlix is fully closed, make sure it uninstalls (should be either no or an empty FastFlix directory in `C:\Program Files` after uninstalling) and try installing again.

**Comment by mrdav1** [comment]
That sorted it... thanks
