### ISSUE TITLE
nvencc 7.15 - 7.20 result in pgs_merge error

### ISSUE THREAD

**Issue by rharmonson** [cdgriffith/FastFlix#438]
**Describe the bug**
On using rigaya NVEnc versioni 7.15 or 7.20 to encode bluray or 4k bluray, FastFlix reports:

```
perf monitor: Failed to start NVML Monitoring for "0000:01:00.0": A query to find an object was unsuccessful.

avout: failed to find pgs_frame_merge.
failed to initialize file reader(s).
Failed to open output file: "/path/to/movie.mkv"
```

**To Reproduce**
1. Obtain [https://github.com/rigaya/NVEnc/releases/tag/7.15](https://github.com/rigaya/NVEnc/releases/tag/7.15) 
2. Configure FastFlix settings to use NVEnc.
3. Source a file to encode
4. Enable subtitle(s)
5. Add to queue and convert

Error should result.

**Resolution**

After Installing 7.14, I was able to encode/convert without errors.

Happy to provide additional information but may need guidance on how to obtain. Thank you.

**Comment by cdgriffith** [comment]
I would definitely open an issue directly on their page https://github.com/rigaya/NVEnc/issues with an example command!

**Comment by rharmonson** [comment]
The "command" being from FastFlix's Raw Commands tab and "NVEncCEncode" or something else?

**Comment by cdgriffith** [comment]
Correct the command(s) listed on the Raw Commands and then the output from the encoding page as you showed above ^ 

Would just make sure to remove any paths to video files before posting it.

**Comment by rharmonson** [comment]
Done!

https://github.com/rigaya/NVEnc/issues/471

**Comment by rharmonson** [comment]
Fixed!

Tested NVEnc 7.21 against FastFlix 5.3.0 without errors.

@cdgriffith and @rigaya your support is amazing. Absolute pleasure to work with both of you.
