### ISSUE TITLE
Transcoded video still has metadata of the original one

### ISSUE THREAD

**Issue by HannesJo0139** [cdgriffith/FastFlix#44]
After transcoding, mediainfo still shows e.g. bitrate of the original video what is not correct anymore. A metadata update of the output file can be triggered with ffmpeg option "-map_metadata -1"

**Comment by cdgriffith** [comment]
Actually trying it out myself some more, it looks like ffmpeg handles translation of rotate metadata to the final product itself behind the scene, and any transposing is done additionally on top of that, so should be safe to always remove metadata!

**Comment by cdgriffith** [comment]
is removed in 2.4.0. Thanks for the suggestion!
