### ISSUE TITLE
SVT-AV1 Encoding Guide link

### ISSUE THREAD

**Issue by gaLDWoRE** [cdgriffith/FastFlix#441]
The link at the bottom seems to go to an old location.
![image](https://user-images.githubusercontent.com/7178005/224565380-f85636aa-5c0d-435e-a131-cfbf405dba7d.png)

I believe it should lead to this now: https://gitlab.com/AOMediaCodec/SVT-AV1/-/blob/master/Docs/Ffmpeg.md

**Comment by cdgriffith** [comment]
Fixed in https://github.com/cdgriffith/FastFlix/releases/tag/5.4.0 thanks!
