### ISSUE TITLE
qsvenc with y4m input file

### ISSUE THREAD

**Issue by Joet73** [cdgriffith/FastFlix#442]
**Describe the bug**
1. Encoder error with colorrange and chromaloc parameters automatically setup to auto. As per the QSVenc documentation says only avsw and avhw readers are able to use auto.
2. When I manually set colorrange to limited & chromaloc to anything but auto (tried from 0 to 5), encoding works but color is shifted.

**To Reproduce**
1. Input .y4m file downloaded [ here](https://media.xiph.org/video/derf/y4m/park_joy_2160p50.y4m)
2.  Choose qsvenc HEVC encoder option (Using V7.34 for the test)
3. Use icq mode. I haven't tried other mode but error should be the same.
4. Start encoding.
5. Using a the below command line no error but the chroma is shifted as well.
`QSVEncC64.exe --y4m -i input.y4m --icq 18 -c hevc -u best -o output.mp4`
Using this ffmpeg piping no chroma shift
`ffmpeg.exe -y -i input.y4m -an -f yuv4mpegpipe - | QSVEncC64.exe --y4m -i - --icq 18 -c hevc -u best -o output.mp4`
It might be a bug with Rigaya's y4m reader.

**Comment by Joet73** [comment]
Hi
Issue reported [here](https://github.com/rigaya/QSVEnc/issues/121) 
But i still believe that there is an issue with fastflix automatically setting chromaloc and colorrange to auto which throw an error with y4m input file.
BTW, just tested eith avi file, same error.

**Comment by cdgriffith** [comment]
Thanks for the extra details about it trying to add stuff it can't to avi / y4m. Right now have a quick fix for qsv / nvenc that will always specify the avsw reader that should fix it, but going to be adding option to allow it to use the  default y4m reader as well https://github.com/cdgriffith/FastFlix/releases/tag/5.4.1
