### ISSUE TITLE
Normalization of Specific Audio Tracks

### ISSUE THREAD

**Issue by Damundai** [cdgriffith/FastFlix#449]
Encoding my 4K movies, I usually have 3 tracks.  An MP3 track (primary track), the original Atmos, Dolby EX, etc track (second track), and a Surround 5.1 track (third track).  Looking for a way to apply normalization to just the MP3 track and not the others.

When I attempt to add the ffmpeg code for it, FastFlix errors out telling me it is attempting to apply the normalization to all three tracks, which ffmpeg is unable to do on the Atmos, EX, Dolby, etc tracks.

Unless there is a command or setting I am missing somewhere....

Thanks!

**Comment by cdgriffith** [comment]
Hi @Damundai, you can add filters like that to specific tracks thankfully! I cover it briefly in the existing topic for normalization https://github.com/cdgriffith/FastFlix/issues/45#issuecomment-713807807 

If you have other questions or issues with specifically that please add to the discussion there, but of course please feel free to open new discussions or issues for other topics as they come up!
