### ISSUE TITLE
-vsync is deprecated?

### ISSUE THREAD

**Issue by GT500org** [cdgriffith/FastFlix#450]
**Describe the bug**
Message in FFmpeg output:

> -vsync is deprecated. Use -fps_mode

**To Reproduce**
1. When encoding a video, select an option for "vsync" on the Advanced tab (I used CFR).
2. Start encode process, and watch output on Encoding Status tab.
3. Message about -vsync appears above information about the input media.

Not really a bug... Just something that might need to be changed eventually.

**Comment by cdgriffith** [comment]
Adding a way to determine ffmpeg version and if it's a "true" version and newer than 5 will use fps_mode. If it is using a non version number build (like downloading latest master) will not be able to know the version so will use vsync. Best I can do for detect at the moment https://github.com/cdgriffith/FastFlix/releases/tag/5.4.0
