### ISSUE TITLE
HEVC Tunes not being applied properly

### ISSUE THREAD

**Issue by HannesJo0139** [cdgriffith/FastFlix#451]
Hi! I'm working with HEVC and I noticed that Fastflix does not handle selection of tunes properly. When selecting eg. tune grain, I would expect every setting of that tune to be applied in the resulting encode. But in fact, every setting the GUI offers a form element for will be overwritten. For example, the tune grain comes with adaptive quantization = 0 and the [docs state](https://x265.readthedocs.io/en/stable/presets.html?highlight=presets#film-grain) that it must not be overwritten. But Fastflix is overwriting it with what ever aq setting I selected previously. 

When selecting a tune, Fastflix should adjust affected form fields or even disable them. If that is too much work, another approach would be kind of a warning that single settings overwrite the tune, so the user knows he has to look into the docs and match the settings.

**Comment by cdgriffith** [comment]
Thanks for the knowledge on that, I was not aware of those requirements!

**Comment by cdgriffith** [comment]
Thanks again for the link with all the details, I actually updated both the tune and what changing the preset does to match what's on that page in 5.4.1 https://github.com/cdgriffith/FastFlix/releases/tag/5.4.1
