### ISSUE TITLE
New Profile Audio disabling Passthrough All only working when Pattern Match added

### ISSUE THREAD

**Issue by HannesJo0139** [cdgriffith/FastFlix#452]
Since I downmix audio using external tools (2-pass) I want to create a Fastflix profile that selects no audio streams at all. So I disable the setting Passthrough All and add no pattern match, but Fastflix behaves as if Passthrough All would have been activated.

**Comment by cdgriffith** [comment]
Adding toggle to disable all audio via profile in https://github.com/cdgriffith/FastFlix/releases/tag/5.4.0
