### ISSUE TITLE
Extra Frame at the Start of Encoded File

### ISSUE THREAD

**Issue by GoodarzMehr** [cdgriffith/FastFlix#454]
**Describe the bug**
FastFlix adds an extra frame to the start of a 4K HDR .mkv file that I encode using the default UHD HDR settings preset (I do convert the audio to AAC from Dolby TrueHD). I wonder if this is because the file has a DV MEL layer, because when I encode another non-DV 4K HDR file the frame number is the same as the source.

**To Reproduce**
N/A

**Screenshots**
N/A

**Comment by cdgriffith** [comment]
Hi @GoodarzMehr thanks for the info! 

That is going to be something the muxer or encoder is doing behind the scenes. Are you using x265, ffmpeg's nvenc or one of rigaya's hardware encoders? (With default UHD profile assuming x265 which is ffmpeg, but just want to make sure.) 

For `ffmpeg` all I can recommend make sure you are on latest version. Otherwise I honestly don't know best place for feedback of that. 

If it's something with rigaya's encoders would open a bug report on that corresponding repo https://github.com/rigaya.

**Comment by GoodarzMehr** [comment]
Hi,

Thanks for the information. I'm using the default ffmpeg x265, and what you said seems like the most plausible explanation. It's still a bit strange since it happens for only this one file!

**Comment by GoodarzMehr** [comment]
Hello again,

After closer inspection, it seems that during the encoding process of my `.mkv` files frame timestamps get shifted, which is why some programs interpret it as an extra frame at the beginning. In the example I mentioned above, the timestamps of the original file are
```
0.000
0.042
0.083
0.125
...
```
but for the encoded file the timestamps are
```
0.000
0.063
0.104
0.146
...
```
For another `.mkv` file, the timestamps of the original file are again
```
0.000
0.042
0.083
0.125
...
```
but for the encoded file the timestamps are
```
0.000
0.047
0.088
0.130
...
```
Does this relate to FastFlix or is it still an FFmpeg issue?

BTW I'm using v5.3.0 on Ubuntu 22.04, v5.4.0 runs into the `xcb` issue and the recommended method does not resolve it.

Thanks!

**Comment by cdgriffith** [comment]
Anything with the encoding itself is in ffmpeg, FastFlix just passes the args to it. Looking around I have seen another similar thing https://trac.ffmpeg.org/ticket/2333 having to due with audio timestamps fix to not be negative at the start. 

Sorry to hear about the xcb issues, that is always an annoying one. Can you paste the output of `QT_DEBUG_PLUGINS=1 ./FastFlix` in another ticket (when running 5.4.0) ? 

Also can try `QT_QPA_PLATFORM=wayland ./FastFlix` to force it to try and use wayland.

**Comment by GoodarzMehr** [comment]
Thanks for the info, I'll check it out. For now I'm just rewriting the timestamps after the encoding is done.

Sidenote, v4.5.1 is working on my system without any `xcb` issues.
