### ISSUE TITLE
[QSVEnc] framerate parameters not applied

### ISSUE THREAD

**Issue by forart** [cdgriffith/FastFlix#455]
Hi there and, as always, thanks for your (voluntary) work.

We noticed that FF doesn't set the framerate parameter correctly: whatever we input in "Override Source FPS", "Output FPS" or "Video Speed" fields, nothing changes in the relative commandline.

Hope that helps to fix the issue.

**Comment by cdgriffith** [comment]
Thanks for the heads up! 

* "Override Source FPS" was totally missing, adding that for next version! 
* "Output FPS" is not supported, but was not marked as such with the "ʘ" to show it doesn't work with rigaya's stuff, adding the marker.
* "Video Speed" already has the "ʘ" beside it showing it will not work with the hardware encoders

**Comment by cdgriffith** [comment]
Changes made in https://github.com/cdgriffith/FastFlix/releases/tag/5.4.0
