### ISSUE TITLE
AV1 Nvenc changing resolution issue

### ISSUE THREAD

**Issue by smartworld-10** [cdgriffith/FastFlix#456]
Converting video to lower resolution like from 1920x1080 to 1280x720 makes video unplayable by firefox browser and it's playing only the audio.
If the same file is converted to exact the same resolution as the original file everything is working.

I don't have any alternative to convert files to Nvenc AV1 to determine if it's FastFlix bug or Firefox

**Comment by cdgriffith** [comment]
Hi @smartworld-10  that is very odd behavior, and sounds more like a potential bug with NVEncC. 

Could you open up an issue on their page https://github.com/rigaya/NVEnc/issues with example commands (from the Raw Commands) panel?
