### ISSUE TITLE
Fastflix fails to start under Lubuntu 22.04

### ISSUE THREAD

**Issue by PabloAbreu** [cdgriffith/FastFlix#459]
**FastFlix Version:** 5.4.0

**Operating System:** Lubuntu 22.04
5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
Fastflix UI does not start 

**To Reproduce**
Steps to reproduce the behavior
 - Quite fresh install of Lubuntu 22.04
 - ffmpeg and libopengl0 installed from the standard apt repo
 - Download Fastflix 5.4.0 from github releases && chmod +x
 - from bash, "./Fastflix"
 - Ran into problems described into "common-questions-and-problems" page
 - Ran "sudo apt install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev"
 - still no luck. see logs below

**Screenshots**
N/A

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.

2023-04-17 18:21:26 machine-name fastflix-core[8364] INFO Starting FastFlix 5.4.0
qt.core.plugin.factoryloader: checking directory path "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqwayland-generic.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqwayland-egl.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqvnc.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archlevel": 1,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vnc")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqvkkhrdisplay.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqvkkhrdisplay.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vkkhrdisplay"
        ]
    },
    "archlevel": 1,
    "className": "QVkKhrDisplayIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vkkhrdisplay")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqminimalegl.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimalegl")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqlinuxfb.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archlevel": 1,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("linuxfb")
qt.core.plugin.factoryloader: looking at "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqeglfs.so"
qt.core.plugin.loader: Found metadata in lib /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archlevel": 1,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 394496
}

qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: checking directory path "/path/to/folder/platforms" ...
qt.core.library: "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so" cannot load: Cannot load library /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /tmp/_MEIql3sPY/PySide6/Qt/plugins/platforms/libqxcb.so: (libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.

2023-04-17 18:21:27 machine-name fastflix-core[8364] DEBUG Conversion worker shutting down

**Comment by cdgriffith** [comment]
Hi @PabloAbreu  thanks for the logs and sorry for the delay. 

In that output it is showing: `(libxcb-cursor.so.0: cannot open shared object file: No such file or directory)"` so I would look for `libxcb-cursor` in the OSes package manager. In ubuntu that would be `sudo apt search libxcb-cursor` to show the options available then I would install 

`sudo apt install libxcb-cursor0`

**Comment by PabloAbreu** [comment]
Hi
Thanks a lot, "sudo apt install libxcb-cursor0" did the trick.
