### ISSUE TITLE
QSVEncC not listed as encoder with FastFlix 5.4.0

### ISSUE THREAD

**Issue by zedfreak** [cdgriffith/FastFlix#460]
**FastFlix Version:**
5.4.0

**Operating System:**
Windows 10 22H2 64bit (build 19045.2846)

**Describe the bug**
rigaya QSVEncC (7.36 or 7.37 tested) is not an available encoder from the drop down menu in FastFlix 5.4.0, however it is available in 5.3.0.  Both from upgrade or clean install with either installer or portable versions.

Reverting to 5.3.0 restores functionality.

**To Reproduce**
Primarily tested with portable version, although the same issue was seen with a clean installation with the installer version.  Also, clean installations tried with both variants.

Upgrade or install FastFlix 5.4.0 (portable easiest), install FFmpeg and QSVEncC (7.36 or 7.37 tested) and point FastFlix to their location.  Once configured, restart FastFlix and check encoder drop down if QSVEncC is present.

Overwrite 5.4.0 portable with 5.3.0 portable and functionality returns.

**Screenshots**
Comparison screenshots between 5.3.0 and 5.4.0 provided to show encoder is missing.

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.
Log file included.
Config file included which seems to show QSVEncC  encoder detected.

![FastFlix_5-3-0](https://user-images.githubusercontent.com/131057530/232614240-18ef9b96-baf0-4408-8643-b9fcf5a71970.png)
![FastFlix_5-4-0](https://user-images.githubusercontent.com/131057530/232614241-8d6d6ccd-e92b-4a02-af07-3f63f7a322e5.png)
[flix_gui_2023-04-17T17.25.07.log](https://github.com/cdgriffith/FastFlix/files/11255979/flix_gui_2023-04-17T17.25.07.log)
[fastflix_yaml.txt](https://github.com/cdgriffith/FastFlix/files/11256043/fastflix_yaml.txt)

**Comment by cdgriffith** [comment]
So for some reason cannot parse the output of QSVEnc, could you run this command and share the output? 

```
D:\FastFlix\QSVEncC_7.37\QSVEncC64.exe --check-features
```

**Comment by zedfreak** [comment]
[QSVEncC_checkfeatures.txt](https://github.com/cdgriffith/FastFlix/files/11256425/QSVEncC_checkfeatures.txt)
Run as regular user, not admin.  See attached.
Perhaps the CPU is too dated?

**Comment by cdgriffith** [comment]
Thanks! It is showing that should have at least AVC listed. I will use that file to figure out what's going wrong with the parsing. In 5.4.0 added a way for it to try and detect only what is supported, but looks to have failed finding anything in this case.

**Comment by zedfreak** [comment]
I thought it might be with #389 but I was not smart enough to trace through the code to help pinpoint it further.  Let me know how else I might be of help.  Thanks for checking!

**Comment by pat-e** [comment]
Same for me. 
I have Intel Arc A380, but none of the QSV is available:

[QSVEncC_checkfeatures.txt](https://github.com/cdgriffith/FastFlix/files/11259920/QSVEncC_checkfeatures.txt)

I went back to v.5.3.0 and even the QSV AV1 is working there fine.

PS: I didn't want to complain, I just wanted to provide the Output of "QSVEncC64.exe --check-features " with an Intel Arc - Card instead of the integrated iGPU.

**Comment by rbjtech-github** [comment]
I guess a known issue - but the _check feature_ output for a UHD 770 attached if required.

Thanks !

[QSVEncC-check-features-uhd770.txt](https://github.com/cdgriffith/FastFlix/files/11260739/QSVEncC-check-features-uhd770.txt)

**Comment by cdgriffith** [comment]
Turns out wasn't a parsing error of that at all, just a stupid internal boolean switch state I didn't catch it testing. Fixed in 5.4.1 (hopefully) https://github.com/cdgriffith/FastFlix/releases/tag/5.4.1

**Comment by rbjtech-github** [comment]
Thanks - can confirm 5.4.1 is now picking up my UHD770/QSV. :)
