### ISSUE TITLE
Fastflix 5.40  failed to use-unknown command --seekto For Nvencc

### ISSUE THREAD

**Issue by Genine-Collin** [cdgriffith/FastFlix#461]
FastFlix Version:*5.40*

**Windows 11 Ent**

**Describe the bug**
.

**To Reproduce**
Using like before nvencc for encoding mkv and getting error --seekto  no additional options entered all in default older vervions no problems
Also when updating to new version you lose all your settings and profiles so please make a note or warning to take an backup of  fastflix.yaml glad i did  added log seems to be problem with the command seems to be auto added for this mkv
**Test it with the previous version of fastflix and it uses the --trim command**

Example:
"C:\Users\Genuine\Downloads\*******\nvenc\NVEncC64.exe" -i "C:\Users\Genuine\Documents\******\*****.mkv" --trim 0:159260 --crop 0,264,0,264 --video-metadata clear --metadata clear --chapter-copy -c hevc --cqp 21 --bref-mode disabled --preset quality --tier high --lookahead 32 --aq-temporal --aq-strength 0 --level 5.1 --colormatrix bt2020nc --transfer smpte2084 --colorprim bt2020 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --max-cll "1000,567" --output-depth 10 --multipass 2pass-full --mv-precision Auto --chromaloc auto --colorrange auto --avsync cfr  --audio-metadata 1?language=eng --audio-stream 1?:5.1 --audio-codec 1?eac3 --audio-bitrate 1?1536  --audio-metadata 1?clear   -m default_mode:infer_no_subs --preset P3 -o "C:\Users\Genuine\Documents\********-fastflix-4ab5"

Nvencc info command 
--seekto [<int>:][<int>:]<int>[.<int>]
The format is hh:mm:ss.ms. "hh" or "mm" could be omitted.

Set encode finish time. This might be inaccurate, so if you require exact number of frames to encode, use [--trim](https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--trim-intintintintintint).

Examples
Example 1: --seekto 0:01:15.400
Example 2: --seekto 1:15.4
Example 3: --seekto 75.4

**Screenshots**

![Fastflix](https://user-images.githubusercontent.com/99371909/232902537-c592998a-c0b4-4db2-ac25-91c376ab69bd.jpg)

**Logs**
[log.txt](https://github.com/cdgriffith/FastFlix/files/11266430/log.txt)

**Comment by cdgriffith** [comment]
> Also when updating to new version you lose all your settings and profiles so please make a note or warning to take an backup of fastflix.yaml glad i did added log seems to be problem with the command seems to be auto added for this mkv

That should definitely not happen, will have to look into that as it's own issue, thanks for the warning! 

For the `--seekto` please update to the latest version of `Nvencc` from https://github.com/rigaya/NVEnc/releases , looks like `seekto` was added more recently than I realized in December with version 7.07 so I imagine a few people are going to run into this, thanks for heads up!

**Comment by Genine-Collin** [comment]
@cdgriffith thx for the quick fix ;-) indeed it works again but the problem that I have when updating to a newer version of 
nvencc is than i'm loosing the HLG.
 Normal when i'm using the command of nvenc dolby vision 8.4 it's getting the HLG option and then i add the  atc-sei bt2020-10 with works perfect 
When updating to a newer one it won't work anymore i don't know if its related to your program or rigaya's

![hlg prob](https://user-images.githubusercontent.com/99371909/233867510-61306a88-4901-4416-9b68-bf4caf02cca4.png)


![hlg Prob2](https://user-images.githubusercontent.com/99371909/233867527-d442f424-114f-4e4b-bab5-0c77f802a6ac.png)

**Comment by cdgriffith** [comment]
Good spot catch, not something I think FastFlix interferes with at all. I don't send different params for different versions or anything like that. 

Would definitely open an issue with rigaya directly for that! https://github.com/rigaya/NVEnc/issues

**Comment by Genine-Collin** [comment]
@cdgriffith Hi, Talked to Rigaya this is the respond 
**Previously --dolby-vision-profile has overwritten values of --colormatrix, --colorprim, and --transfer, but now it is the opposite due to user request. Now, --colormatrix, --colorprim, and --transfer will overwrite --dolby-vision-profile.**


So this was fixed in version 7.13 "changes behavior handling"  so in other words you need to add the --transfer arib-std-b67 and you get the Hybrid log gamma back that's why i  did not update afther v5.43.
Glad this is the fix for me 
Greetz

Genine Collin
