### ISSUE TITLE
Resize Ignores Custom Resolution

### ISSUE THREAD

**Issue by GT500org** [cdgriffith/FastFlix#468]
**FastFlix Version:**
5.5.1

**Operating System:**
Win 10 x64 (22H2)

**Describe the bug**
When I enter a custom resolution to resize a video, it ignores the resolution I enter manually and keeps the original resolution of the video in the command. After converting the video, no resizing will have taken place. I have verified this with both width:height and just height.

**Comment by cdgriffith** [comment]
Thank you for the information! 

Few things that have gone wrong I am addressing in next release:

1. https://trac.ffmpeg.org/wiki/Scaling some versions of ffmpeg when using filter_complex don't apply the same defaults, aka will always keep aspect ratio the same. Fixing
2. no trigger to update the command on the page after changing the text on the custom field. Fixing
3. The thumbnail would ignore custom resolutions. Now will build full size thumbnail if set to a custom resolution. 
4. Fixing large preview wouldn't use the scale

**Comment by cdgriffith** [comment]
Hopefully all fixed in 5.5.2 https://github.com/cdgriffith/FastFlix/releases/tag/5.5.2

**Comment by GT500org** [comment]
I was able to resize videos without issue (changing the aspect ratio or maintaining it) using custom resolutions in 5.5.2. Thanks for the quick fix.

**Comment by cdgriffith** [comment]
Awesome, thanks for the confirmation!
