### ISSUE TITLE
Encoder settings mess up when editing from queue

### ISSUE THREAD

**Issue by veldspar** [cdgriffith/FastFlix#474]
Just a tiny bug report, using latest release for Ubuntu 22 on debian bookworm:

My selected preset uses svt av1 with CPU used 2 and a single pass custom Bitrate at 1200kbps for 1080p content(the content seems upscaled so I can get away with that Bitrate). When I add it to the queue for encoding and the hit the edit button to double check it will load the file back in but remove the single pass checkmark and sometimes set the Bitrate to a 1080p profile at 3000 kbps

**Comment by cdgriffith** [comment]
Thanks for the ticket! Fixing the single pass missing option in next release. Can't get the bitrate custom bug to happen, but will keep an eye on it.

**Comment by cdgriffith** [comment]
Fixing the single pass issues in 5.5.4, will keep open for now to look for bitrate flip issues as well https://github.com/cdgriffith/FastFlix/releases/tag/5.5.4

**Comment by cdgriffith** [comment]
The bitrate bug should also be fixed and have not had other reports
