### ISSUE TITLE
Autocrop can break with index error

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#475]
Brought up by  No Name on discord

Hi, i got error (cannot cropping video) when use FFmpeg with VVC(H266) codec support

**Screenshots**
![image](https://user-images.githubusercontent.com/3275435/235309902-7e5c50f3-bdba-44cd-9683-7ad93f626091.png)

**Comment by phanluchoaofficial1152** [comment]
Thanks for posting, as I mention before, this error is only occur when change ffmpeg have VVC (H266) only (no others codec) but with normal official ffmpeg is not get that error. It get auto-crop normally.

I have a ffmpeg with only have VVC (H266) for u to test after fix it:

https://drive.google.com/drive/folders/1Y-_hSP6omCZzOn9Swr2NgRm8Nz6LCK2y?usp=sharing

**Comment by cdgriffith** [comment]
Running the command itself I see this error: 

```
[AVFilterGraph @ 00000291dc3e5480] No such filter: 'cropdetect'
Error reinitializing filters!
Failed to inject frame into filter network: Filter not found
Error while processing the decoded data for stream #0:0
```

So I am adding a case that it will just log a warning instead that it's not supported if the ffmpeg doesn't have that filter.

**Comment by cdgriffith** [comment]
Warning added in 5.5.4 https://github.com/cdgriffith/FastFlix/releases/tag/5.5.4

**Comment by phanluchoaofficial1152** [comment]
thanks

Vào Th 5, 4 thg 5, 2023 lúc 07:17 Chris Griffith ***@***.***>
đã viết:
