### ISSUE TITLE
HDR10+ getting  **AttributeError: 'NVENCC' object has no attribute 'ffmpeg_level'

### ISSUE THREAD

**Issue by Genine-Collin** [cdgriffith/FastFlix#477]
**FastFlix 5.5.3:**

**Windows 11 Ent**

When extracting HDR10+ getting  **AttributeError: 'NVENCC' object has no attribute 'ffmpeg_level'
Traceback (most recent call last):
  File "fastflix\encoders\nvencc_hevc\settings_panel.py", line 153, in <lambda>
    self.hdr10plus_ffmpeg_signal.connect(lambda x: self.ffmpeg_level.setText(x))**  
after generating metadata getting a new error

**Traceback (most recent call last):
  File "fastflix\encoders\common\setting_panel.py", line 312, in done_hdr10plus_extract
    self.ffmpeg_level.setText("")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NVENCC' object has no attribute 'ffmpeg_level'**
Also it is not displaying the time it takes to extract

**To Reproduce**
Steps to reproduce the behavior
extract HDR10+

![HDR10+ pannel error](https://user-images.githubusercontent.com/99371909/236058894-1114251e-d00e-4751-a014-5ae7298100f2.jpg)
[flix_gui_2023-05-03T23.33.17.log](https://github.com/cdgriffith/FastFlix/files/11391521/flix_gui_2023-05-03T23.33.17.log)

**Comment by cdgriffith** [comment]
Thank you for the details! Going to change all the rigaya encoders to use the copy capabilities instead of needing to extract it.

**Comment by cdgriffith** [comment]
Fixed / changed in 5.5.4 https://github.com/cdgriffith/FastFlix/releases/tag/5.5.4

**Comment by Genine-Collin** [comment]
Strange thing is that when doing so i'm loosing the normal hdr10
![loosing hdr10](https://user-images.githubusercontent.com/99371909/236085693-4c19f2ec-4afc-462c-bb3c-44ccd020753f.jpg)
