### ISSUE TITLE
AOM AV1 corrupted video

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#483]
From sn6op

Videos are corrupting for the last few updates while using AOM AV1, most obvious at start or end credits. 

**FastFlix Version:** 5.5.4

**Describe the bug**
The two-pass settings I use for AOM AV1 are as follows;
-aom-params enable-dnl-denoising=0:film-grain-test=1:sharpness=1:sb-size=64:enable-qm=1:qm-min=1:deltaq-mode=0:enable-restoration=0:arnr-strength=1:arnr-maxframes=3:aq-mode=1:enable-chroma-deltaq=1:quant-b-adapt=1:disable-trellis-quant=0:enable-keyframe-filtering=0 -lag-in-frames 48
Also on the GUI the Keyframe box is clicked.

**Comment by sn6op** [comment]
"qm-min=1", "enable-keyframe-filtering=0" and probably "enable-chroma-deltaq=1" params cause an error. should not be played with default values. You can close the ticket.

**Comment by sn6op** [comment]
> What settings do not corrupt the video ? I get also "broken" keyframes with: **pass1**: `ffmpeg -i '/mnt/ramdisk/inputvideo.mp4' -vf scale=1920:1080:flags=lanczos,setsar=1:1 -pix_fmt yuv420p10le -c:v libaom-av1 -threads 32 -aom-params sb-size=64:enable-qm=1:enable-dnl-denoising=0:deltaq-mode=0:aq-mode=1:enable-chroma-deltaq=1:disable-trellis-quant=0:quant-b-adapt=1:enable-keyframe-filtering=1:arnr-strength=1:arnr-maxframes=3:sharpness=3 -cpu-used 2 -b:v 1814400 -tiles 2x1 -auto-alt-ref 1 -lag-in-frames 48 -pass 1 -passlogfile '/mnt/ramdisk/av1_FHDP_04_log' -an -f null /dev/null > /dev/null ` **pass2**: `ffmpeg -i '/mnt/ramdisk/inputvideo.mp4' -vf scale=1920:1080:flags=lanczos,setsar=1:1 -pix_fmt yuv420p10le -c:v libaom-av1 -threads 32 -aom-params sb-size=64:enable-qm=1:enable-dnl-denoising=0:deltaq-mode=0:aq-mode=1:enable-chroma-deltaq=1:disable-trellis-quant=0:quant-b-adapt=1:enable-keyframe-filtering=1:arnr-strength=1:arnr-maxframes=3:sharpness=3 -cpu-used 2 -b:v 1814400 -tiles 2x1 -g 200 -auto-alt-ref 1 -lag-in-frames 48 -pass 2 -passlogfile '/mnt/ramdisk/av1_FHDP_04_log' -map 0 -acodec copy '/mnt/ramdisk/output_av1_FHDP_04.mkv'`

you don't need to add "enable-keyframe-filtering=1" on params set... instead tick the Keyframe Box on GUI... also "deltaq-mode=0:enable-chroma-deltaq=1" params are not so useful... try to leave as default... these will solve the problem...
