### ISSUE TITLE
Cannot Restore Queue Containing HDR10+ Entries

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#485]
Version: 5.5.5
Operating System: Windows 10

**Describe the bug**
When trying to restore a queue with HDR10+ media errors occur and the queue cannot be processed.

Steps to recreate issue:
- Add Source
- Extract HDR10+ Metadata
- Add To Queue
- Save Queue
- Load Queue

Log:
[flix_gui_2023-05-13T12.58.42.log](https://github.com/cdgriffith/FastFlix/files/11469645/flix_gui_2023-05-13T12.58.42.log)

**Comment by cdgriffith** [comment]
Will have hotfix in for next release, but honestly this needs a better solution to make the save queue semi-portable. 

Right now it "hides" the covers and hdr10 data in the appdata folder (problem was I got over zealous with cleanup and those started to get deleted on startup). Need to make it add all that to a zip file or something alongside the queue

**Comment by mrdav1** [comment]
﻿As I have a lot queued I tend to manually edit the queue to move priority items to the top and then reload.  This had been working perfectly until the last release.  An enhancement to FastFlix would be to add functionality to move a queue item to the top.  Keep me posted with your thoughts.On 14 Jun 2023, at 04:20, Chris Griffith ***@***.***> wrote:﻿
Will have hotfix in for next release, but honestly this needs a better solution to make the save queue semi-portable.
Right now it "hides" the covers and hdr10 data in the appdata folder (problem was I got over zealous with cleanup and those started to get deleted on startup). Need to make it add all that to a zip file or something alongside the queue

**Comment by cdgriffith** [comment]
Hopefully at least fixed the queue restore issues: https://github.com/cdgriffith/FastFlix/releases/tag/5.5.6

Will open another issue for the feature requests!
