### ISSUE TITLE
Can't open Setting in Chinese upgraded from old version

### ISSUE THREAD

**Issue by tantiancai** [cdgriffith/FastFlix#491]
**FastFlix Version:**
v5.5.5

**Operating System:**
Windows 11 10.0.22621.1778（Chinese Version）

**Describe the bug**
After opening the software, the interface changes to English, and clicking the "File-Settings" menu does not respond.
The console prompts "WARNING: zho is not a supported language, defaulting to eng" and "ValueError: 'Chinese' is not in list"

**To Reproduce**
Install v4.10.0, set the interface language to Chinese, upgrade to v5.5.5.

**Screenshots**
<img width="866" alt="image" src="https://github.com/cdgriffith/FastFlix/assets/5001174/6c02d1de-d713-4093-9df4-1f7d4d60586e">

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.
[FastFlix.zip](https://github.com/cdgriffith/FastFlix/files/11575384/FastFlix.zip)

**Comment by cdgriffith** [comment]
Thanks for the heads up, would never have tried that myself!
https://github.com/cdgriffith/FastFlix/releases/tag/5.5.6
