### ISSUE TITLE
QTGMC As Deinterlace Option

### ISSUE THREAD

**Issue by sturmen** [cdgriffith/FastFlix#492]
I find that QTGMC is the best deinterlacer, even beating out proprietary ones like the "neural engine" of Davinci Resolve Studio. I would love to see it integrated into FastFlix!

**Comment by forart** [comment]
...but it's an Avisynth script: http://avisynth.nl/index.php/QTGMC

**Comment by cdgriffith** [comment]
As that is outside ffmpeg or one of rigaya's hardware encoders, can't add it to this project
