### ISSUE TITLE
Batch Mode not using Original Date and time

### ISSUE THREAD

**Issue by micron888** [cdgriffith/FastFlix#493]
**FastFlix Version:**
5.5.5
**Operating System:**
Windows 11
**Describe the bug**
Original date/time not working in batch mode

**To Reproduce**
Single File mode, uncheck remove metadata, add to queue. Ok
Batch mode, apply profile with metadata false, add to queue. file using current date/time

**Comment by cdgriffith** [comment]
Thank you for raising this issues! 

This actually digs deeper than just that it seems, that the options for those checkmarks are totally ignored by the profile on load (they are saved as part of profile, but never applied.)

**Comment by cdgriffith** [comment]
Fixed that metadata, chapters and remove hdr are now preserved properly with the profile. 

Will need to add a  way to "Force deinterlace" or force off in the profiles, will open separate issues for that https://github.com/cdgriffith/FastFlix/releases/tag/5.5.6

**Comment by micron888** [comment]
Great. I will test it out again
