### ISSUE TITLE
Frame rate change in 2 pass mode ("Bitrate" mode) results in error for AVC x264 encoder

### ISSUE THREAD

**Issue by ivan-gorin** [cdgriffith/FastFlix#494]
**FastFlix Version:** 5,5,5

**Operating System:** Windows 10

**Describe the bug**
When using AVC x264 encoder in 2 pass mode, changing the output frame rate results in error after first pass.
**To Reproduce**
1. Choose the AVC x264 encoder.
2. Choose the "Bitrate" mode in the "Quality" tab (This will use the 2 pass encoding method, where the first pass generates a log file and the second pass uses it to closely match the desired bitrate).
3. In the "Advanced" tab, uncheck the "Same as Source" option to the right of "Output FPS" and then enter fps number into the box to the box. **Choose a number different to the source file frame rate.**
4. Start the encoding. Wait until the first pass finishes, right after that the error will happen.

**Screenshots**
![error](https://github.com/cdgriffith/FastFlix/assets/43433603/ddc90b45-82bf-4807-97f8-11fee61bd85c)

**Logs**
The problem is that FastFlix applies the `-r` frame rate option only to the second pass. Here you can see the command FastFlix runs for the first pass:
```
Running command: "C:\Ffmpeg\bin\ffmpeg.exe"   -y  -to 605.2    -i "<input_file>"   -max_muxing_queue_size 1024 -map 0:0   -c:v libx264 -pix_fmt yuv420p      -color_primaries bt709 -color_trc bt709 -colorspace bt709  -pass 1 -passlogfile "C:\Users\<username>\AppData\Roaming\FastFlix\temp_527689e7bd50dcfbb96cf489\pass_log_file_04347fffe2c2ab34e06f" -b:v 5000k -preset:v ultrafast  -an -sn -dn -f mp4 NUL
```

The bug can be worked around by putting the option `-r <desired frame rate>` in the "Custom ffmpeg options" box in the "Quality" tab, however that is not ideal since it puts the option twice in the second pass, and in general the frame rate selection field should work without this.

**Comment by ivan-gorin** [comment]
I think the bug is [here](https://github.com/cdgriffith/FastFlix/blob/a4f71bd4c6e1bb414d636e8d5be8d3079b18b718/fastflix/encoders/avc_x264/command_builder.py#LL25C1-L25C1), the `output_fps` information is part of the `ending` string generated by `generate_all` function but it is not concatenated to the first pass command.

**Comment by cdgriffith** [comment]
Good call on the fix! Re-did that logic hopefully everwhere it was used https://github.com/cdgriffith/FastFlix/releases/tag/5.5.6
