### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by strarsis** [cdgriffith/FastFlix#495]
I want to use FastFlix for minifying a single image (JPEG; PNG or TIFF source image) using AVIF.
AVIF encoding takes a long time with `Squoosh`. probably because it is only using the CPU.

How can I use FastFlix to encode the input image to AVIF on a NVIDIA GPU?

**Comment by cdgriffith** [comment]
FastFlix is only designed for videos, so not something really possibly with the encoders it uses behind the scenes. 

Squoosh is handy to use but slow, can run `avifenc` on your computer to make it a lot faster https://web.dev/compress-images-avif/#encoding-avif-images-with-avifenc

I do not know of any GPU based image encoder software wrapper. Would be cool if found, but not something in scope for FastFlix.

**Comment by cdgriffith** [comment]
[Animated AVIF can either be a sequence of images or a video file](https://github.com/fdintino/pillow-avif-plugin/issues/14#issuecomment-1207326854), just without audio. The video converters - like SVT-AV1 - will convert it into a video and then put it in an AVIF container. 

If one did convert it to a sequence of images, it would still be like the case of a GIF, where it's animated and not a single image.
