### ISSUE TITLE
Add custom x265-params field

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#50]
Right now it is possible to add commands specific to the entire ffmpeg string, but need to add a way to specifically add x265 params.

**Comment by cdgriffith** [comment]
Added in 3.3.0

**Comment by ecarriau** [comment]
Hi,
Sorry to add a comment on a closed issue (hope you'll see it), as I am a new user of FastFlix can you describe how to add additional parameters. for example I would need to add "colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc" or change yuv420p10le to yuv444p.

Thanks for help.
regards,
Emmanuel.

**Comment by cdgriffith** [comment]
Hi Emmanuel, 

The color primary / transfer / matrix stuff should be automatically transferred as a heads up. (Just recently came across issues when the video track is not track 0 for that, fixing in future release) However you can add custom x265  options on the line "Additional x265 params". 

![x265_par](https://user-images.githubusercontent.com/3275435/106909049-7f951800-66c5-11eb-8039-3663b6dfc616.PNG)

Currently FastFlix only supports 4:2:0 videos, not studio grade 4:4:4, can change between `yuv420p`, `yuv420p10e` and `yuv420p12le`  via the "Bit Depth" option on the left.

 You can always make the command as you want it, go to the "Raw Commands" tab and click "Save commands" on the top right, it will give you an editable file you can change that pixel format with and then run that script file by hand.

**Comment by ecarriau** [comment]
Thanks a lot, I managed to perform the modifications I needed !!
Meanwhile, thanks too for your great GUI FastFlix !
