### ISSUE TITLE
Replace -qp with -crf

### ISSUE THREAD

**Issue by ignace72** [cdgriffith/FastFlix#503]
Hello everyone.
On the command line, I use -crf 30 which allows me to have rather light files.
I'm trying FastFlix, and it's forcing me to use -qt 30.
Even if I specify -crf 30 as an additional parameter, FastFlix continues to set the -qt 30 option?
If FastFlix can't adapt to my choices, it's useless by definition.
Thank you in advance.

**Comment by cdgriffith** [comment]
With which encoder? And I assume you mean it's switching to `-qp` not `-qt`?

**Comment by ShubhamVimal** [comment]
@cdgriffith SVT-AV1 encoder. Replace 'QP' with 'CRF'. SVT-AV1 official docs also recommends to use 'CRF'. Do it as soon as possible.
Thank you.

**Comment by cdgriffith** [comment]
There was a drop down for this previously that was accidentally removed at some pointed. Added back in 5.5.7
