### ISSUE TITLE
Problems processing some files with complex paths

### ISSUE THREAD

**Issue by mrdav1** [cdgriffith/FastFlix#505]
**FastFlix Version:** 5.5.6

**Operating System:** Windows 10 x64

**Describe the bug**
Unable to burn-in subtitles for files with complex path

**To Reproduce**
Add media with complex file path
Enable burn-in for subtitles

**Logs**
[flix_conversion_01 Final Call (2160p HD)_2023-06-29T15.36.44.log](https://github.com/cdgriffith/FastFlix/files/11907069/flix_conversion_01.Final.Call.2160p.HD._2023-06-29T15.36.44.log)

**Comment by mrdav1** [comment]
Just remembered that this is very similar to an old bug I reported (#350)

**Comment by cdgriffith** [comment]
What I'm confused about is there is somehow a space after the drive letter, which...can't be there

```
-filter_complex "[0:0]subtitles='D\ :\\Users\\Maddie\\...
```

I *think* if it's removed so it's `D\:\\` instead it should work, but I honestly don't know how it got to that point to start with (somehow in FastFlix, not something you did). Looking at it but is tricky

**Comment by mrdav1** [comment]
It only started happening sometime after v5.5.4 if that’s of any help to you.On 15 Jul 2023, at 19:02, Chris Griffith ***@***.***> wrote:﻿
What I'm confused about is there is somehow a space after the drive letter, which...can't be there
-filter_complex "[0:0]subtitles='D\ :\\Users\\Maddie\\...

I think if it's removed so it's D\:\\ instead it should work, but I honestly don't know how it got to that point to start with (somehow in FastFlix, not something you did). Looking at it but is tricky

**Comment by mrdav1** [comment]
Just discovered that this problem is not limited to subtitles.  If seems that any pathname with "\\" qualifiers that that "wrap" across lines is affected.

For example:
D\:
\\PathName\\File

Becomes "D\: \\PathName\\File" (which equates to "D: \PathName\File" during processing.

**Comment by mrdav1** [comment]
I think that I've found the "Perfect Storm" that causes the issue...

1: Pathname is long and contains sub-directories
2: Pathname has "\\" qualifiers that that "wrap" across lines
3: Usually HDR10+ source (but not always)

This happens frequently when the queue is saved and re-loaded.

I hope this is of some help.

**Comment by cdgriffith** [comment]
Hopefully this issue has been resolved as of the 5.7.X versions? If not please let me know!
