### ISSUE TITLE
Don't rename target?

### ISSUE THREAD

**Issue by Sailing74** [cdgriffith/FastFlix#510]
Is there a way to stop FastFlix from adding random characters to the end of the target file? I've set a default of different folders for source and target. It would be great if there was a way for me not to have to remove the random chars from the target file name for each file I'm converting with FastFlix.

Thanks.

**Comment by rowley71** [comment]
Start fastflix 
go to settings, change the config file to
output_name_format: '{source}'

**Comment by Sailing74** [comment]
Works indeed. There are also some further nice things which can be configured directly with an editor in the config file. Nice, thanks!
