### ISSUE TITLE
rigaya's encoders are not listed, but only after FastFlix version 5.3.0

### ISSUE THREAD

**Issue by CptnFluffy** [cdgriffith/FastFlix#519]
**FastFlix Version:**
5.3.0, 5.4.1, 5.5.7 (most likely everything after 5.3.0)

**Operating System:**
Windows 10 Pro 22H2 19045.3324
7900XTX

**Describe the bug**
All of rigaya's video encoders don't show up in the encoder list, but only after FastFlix 5.3.0. I even installed the Nvidia and Intel versions and they show up in 5.3.0, despite not having the hardware for those, but after 5.3, none of them show up in the encoder list.  I also have a VM set up on my Unraid server with an Arc A380 with FastFlix 5.5.6 and that works just fine. It's only on my AMD system that the encoders don't show up. 

I noticed this sounded very similar to issue #460. The only difference is that that issue was about QSVEncC and not VCEEncC. 

**To Reproduce**
Version 5.3.0 works fine but all other versions after that I tested don't work. (This may be specific to AMD / VCEEncC.)

**Screenshots**
5.3.0:
![fastflix53](https://github.com/cdgriffith/FastFlix/assets/83141053/c0e5f130-e675-44cb-82f6-f4a09a85c370)

5.4.1 (This is the version where issue #460 was fixed):
![fastflix541](https://github.com/cdgriffith/FastFlix/assets/83141053/1f6d9d9f-0918-4665-987e-bd8ffac57ef8)

5.5.7:
![fastflix557](https://github.com/cdgriffith/FastFlix/assets/83141053/0a52e355-8548-4fdc-9ac2-966ada8a494a)

5.5.6 on my A380 VM works fine:
![FastflixVM5 5 6](https://github.com/cdgriffith/FastFlix/assets/83141053/b4b47db4-766a-4e44-8835-c9a0746ceddb)

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.
This is the yaml from 5.3
[fastflix.yaml.txt](https://github.com/cdgriffith/FastFlix/files/12448721/fastflix.yaml.txt)

This is the --check-features command from VCEEncC64:
[check features.txt](https://github.com/cdgriffith/FastFlix/files/12448733/check.features.txt)

**Comment by cdgriffith** [comment]
Removed "Advanced" feature that tried to detect these...as it didn't work, thanks for heads up! https://github.com/cdgriffith/FastFlix/releases/tag/5.6.0
