### ISSUE TITLE
fastflix always opens in texteditor on mac ventura 13.5.1

### ISSUE THREAD

**Issue by tas231** [cdgriffith/FastFlix#521]
**FastFlix Version:**
5.5.7

**Operating System:**
macos ventura 13.5.1

**Describe the bug**
always opens in texeditor instead running the application

**To Reproduce**
double click on fastflix

**Screenshots**

<img width="769" alt="Bildschirmfoto 2023-08-31 um 21 35 21" src="https://github.com/cdgriffith/FastFlix/assets/121641139/6521886b-b12b-4cfe-8417-053a04a8244b">

<img width="732" alt="Bildschirmfoto 2023-08-31 um 21 35 56" src="https://github.com/cdgriffith/FastFlix/assets/121641139/557f8843-5c25-433c-8aa4-41af76c2ad3f">

**Comment by cdgriffith** [comment]
Did you make sure to: 

> Please extract the FastFlix file and set it to executable (i.e. chmod +x FastFlix) then to run it ./FastFlix

https://github.com/cdgriffith/FastFlix/releases/tag/5.5.7

**Comment by tas231** [comment]
thank you!
Sorry, I totally overlooked that manual required step

It is working now.
