### ISSUE TITLE
Set a default max_queue?

### ISSUE THREAD

**Issue by 2600box** [cdgriffith/FastFlix#53]
To make it work, I need to add the following option:

`-max_muxing_queue_size 1024`

Could this be added as the default or set as an option?

**Comment by cdgriffith** [comment]
On the "HEVC" panel for "Quality" there is a drop down for "Max Muxing Queue Size", is that the encoder you were having issues with or one of the other ones?

**Comment by cdgriffith** [comment]
in [3.0.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.0.0) the max muxing queue size has been set to 1024 by default for all video formats except AVC, where it is less likely to encounter an issue.
