### ISSUE TITLE
Trying to crop spams crop error

### ISSUE THREAD

**Issue by gendalv** [cdgriffith/FastFlix#532]
**FastFlix Version:**
5.5.7 portable

**Operating System:**
Windows 11

**Describe the bug**
Changing any of the crop numbers on a 2160x3840 video file. Spams like 5 of those messages. (including by pressing 'auto' button)
If crop is non-zero - changing any setting or codec will spam another crop message.
As a result crop isn't applied.

Wasn't an issue in 5.3.0 with the same file.

**Screenshots**
![2](https://github.com/cdgriffith/FastFlix/assets/10047774/5f675fb9-2d2b-4c42-a091-74ee0335213a)
![1](https://github.com/cdgriffith/FastFlix/assets/10047774/a90e292c-42d5-470d-bff7-0331f36d153f)

**Comment by cdgriffith** [comment]
Changed it in 5.6.0 so instead the colors will just turn red and remove the annoying popups entirely. Thanks for pointing this out! 

https://github.com/cdgriffith/FastFlix/releases/tag/5.6.0
