### ISSUE TITLE
SvtAv1EncApp Standalone

### ISSUE THREAD

**Issue by IlluminatiWave** [cdgriffith/FastFlix#534]
To be able to use the SVT-AV1 executable standalone to FFMPEG. 

The latest version of SVT-AV1 (v1.7.0-4-gba13fac2) brings performance and quality improvements (faster, more efficient, better quality). Unlike FFMPEG, whose latest available version (N-110169-g1b7dbf4604-g97c95961f0+2), libsvtav1, is stuck on version 1.4 (v1.4.1-110-g45acb876).

More information here
https://github.com/AmusementClub/SVT-AV1/blob/mod/Docs/Ffmpeg.md#piping-from-ffmpeg-into-the-standalone-encoder

**Comment by cdgriffith** [comment]
This is something that I don't ever see being added to FastFlix as a feature, as the "real" solution is just compile FFmpeg with the version of SVT-AV1 you want if you need bleeding edge. 

Can use repos that help you build it like: 
https://github.com/m-ab-s/media-autobuild_suite
https://github.com/rdp/ffmpeg-windows-build-helpers
