### ISSUE TITLE
FF not starting due QT reason

### ISSUE THREAD

**Issue by dacorsa** [cdgriffith/FastFlix#535]
hi all,
i use FF from latest build of GH on my ubuntu mantic 23.10, but when starting tells me this error:
14:36:16 dacorsa@NanoKDE /home/dacorsa $ cd /app/FastFlix/ ; . venv/bin/activate  ; venv/bin/python -m fastflix
2023-11-21 14:36:18 NanoKDE fastflix-core[1371203] INFO Starting FastFlix 5.6.0
Cannot mix incompatible Qt library (6.5.3) with this library (6.6.0)
2023-11-21 14:36:19 NanoKDE fastflix-core[1371203] DEBUG Conversion worker shutting down
(venv) 14:36:19 dacorsa@NanoKDE /app/FastFlix master$ 

do you know how solve it?
thanks, best regards

**Comment by dacorsa** [comment]
How to solve

Exec=env LD_LIBRARY_PATH=:/usr/lib/x86_64-linux-gnu/qt6 ; cd /app/FastFlix/ ; . venv/bin/activate ; venv/bin/python -m fastflix

**Comment by cdgriffith** [comment]
Thank you for providing the solution! Added to the wiki https://github.com/cdgriffith/FastFlix/wiki/Common-questions-and-problems#cannot-mix-incompatible-qt-library--with-this-library-
