### ISSUE TITLE
Improve Profiles

### ISSUE THREAD

**Issue by CelticTaonga** [cdgriffith/FastFlix#536]
When using a custom created Profile, if you created it with Bitrate = Custom and a bitrate value,
selecting the profile later never sets the bitrate to Custom with that value.

It'd be nice if it did.

**Comment by DCNerds** [comment]
I have a similar issue, I have a profile with the color space set to bt709, but it never loads.

**Comment by cdgriffith** [comment]
I have hopefully addressed both these issues! Let me know if you are seeing them with the newest beta: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
