### ISSUE TITLE
Inconsistencies in NVENC capitalization and typos

### ISSUE THREAD

**Issue by L0Lock** [cdgriffith/FastFlix#539]
**FastFlix Version:** 5.6.0  
**Operating System:** Windows 11

**Describe the bug**

It's a two-step issue. First being, Rigaya's NVENC all seem to have a doubled letter typo at the end:

![image](https://github.com/cdgriffith/FastFlix/assets/16049822/325cf9d7-806e-4359-8c58-5ae5fac83528)

Secondly, there is no consistency in the capitalization of NVENC in the codecs list. It would look tidier if it was written the same all the time.

IMHO it would make the most sense to just use the official one. In both official and many third party documentations, Nvidia's encoder is named `NVENC` in full cases:

- [Nvidia NVENC - Wikiwand](https://www.wikiwand.com/en/Nvidia_NVENC)
- [Video Codec SDK | NVIDIA Developer](https://developer.nvidia.com/video-codec-sdk)
- [NVIDIA NVENC Obs Guide | GeForce News | NVIDIA](https://www.nvidia.com/en-us/geforce/guides/broadcasting-guide/)

Sometimes we also find with PascalCase: `NvEnc`, which also makes sense as it's the short of "Nvidia Encoder", but it's unofficial. Other writings such as lower case or Nvenc are not as relevent IMHO.

**Comment by cdgriffith** [comment]
This to make the clear distinction between the NVIDIA encoder itself, and NVEncC which is what rigaya's app's executable is named.  As the items in the parentheses are shorthand encoder names.

For example the windows download file is named `NVEncC_7.40_Win32.7z` 

* https://github.com/rigaya/NVEnc/releases/tag/7.40
* https://github.com/rigaya/NVEnc#usage-and-options-of-nvencc
