### ISSUE TITLE
Unchanged Output Filenames

### ISSUE THREAD

**Issue by Mel-chan** [cdgriffith/FastFlix#553]
Hello ^^
Your encoder is working really well for me and could save me a lot of time in my workflows<3

However, I ran into the issue that it always adds a tag to my filenames, especially when bulk encoding. 
I can't seem to find any way to disable this?
Having to rename the output file every single time, is a huge task I would rather avoid. 
So if there is anything that can be done about this, please let me know.
Thank you for your help and time, I greatly appreciate it.

**Comment by cdgriffith** [comment]
Hello @Mel-chan yes it is possible to set that to what you want, but is a "hidden" option currently. You will need to modify the config file. 

In FastFlix go to File > Settings and find the Config File line and click the white document icon on the right, this should open the config file in a text editor. 

You will see a line that you can modify like: 

`output_name_format: '{source}-fastflix-{rand_4}'`

Supported variables (anything in {} brackets) for output_name_format currently are:

    source - original file name
    datetime - "near" iso filename safe datetime (ex. 2021-05-11T3-27-00)
    rand_4 - 4 random characters
    rand_8 - 8 random characters
