### ISSUE TITLE
Subtitles all show as English in FastFlix subtitles screen

### ISSUE THREAD

**Issue by DJJS2021** [cdgriffith/FastFlix#561]
**FastFlix Version:**
5.7.0

**Operating System:**
Windows 11

**Describe the bug**
When loading a ripped MKV for conversion, the subtitles screen shows all subs as English language instead of the actual language

**To Reproduce**
Load any MKV with multiple language Bluray subtitles.

**Screenshots**
![image](https://github.com/cdgriffith/FastFlix/assets/32646588/072ea4b4-b8d8-4a2d-ab37-ff5b1c3d259b)

**Comment by cdgriffith** [comment]
Thank you for reporting this issue, should be fixed in 5.7.1! https://github.com/cdgriffith/FastFlix/releases/tag/5.7.1
