### ISSUE TITLE
Audio conversion window defaults channel layout to stereo

### ISSUE THREAD

**Issue by DJJS2021** [cdgriffith/FastFlix#562]
**FastFlix Version:**
5.7.0

**Operating System:**
Windows 11

**Describe the bug**
When using the new audio conversion window the channel layout always defaults to stereo even if the source is 5.1 or 7.1 channels.

**To Reproduce**
Load MKV with 5.1 or 7.1 channels and open audio conversion window.

**Screenshots**
![image](https://github.com/cdgriffith/FastFlix/assets/32646588/6fdf4f99-f539-4d44-90a3-09cf3dea0bfa)

**Comment by cdgriffith** [comment]
Thank you for reporting this issue, should be fixed in 5.7.1! https://github.com/cdgriffith/FastFlix/releases/tag/5.7.1
