### ISSUE TITLE
No Thumbnails When Importing Video

### ISSUE THREAD

**Issue by Damundai** [cdgriffith/FastFlix#563]
**FastFlix Version:**  5.7.0

**Operating System:**  Windows 11 Home

**Describe the bug**
No thumbnails provided by program when drag / drop master video file to program.
DOS windows shows "**WARNING ERROR trying to use OpenCL for thumbnail generation**"
I have installed the latest NVIDIA driver (555.99 released on 6/4/24) to no avail.

**To Reproduce**
Unknown
![Screenshot 2024-06-21 060417](https://github.com/cdgriffith/FastFlix/assets/125940892/cac41bd3-26e4-49d9-b27a-c35b05f490a4)

Hopefully, this is an easy fix on my end, but I am stumped.  Please advise.

**Comment by Hoedi1030** [comment]
I have had a similar issue a few months ago. Have you recently updated your ffmpeg as well?

Reverting to an older ffmpeg version did the trick for me IIRC.
If you updated it recently, the old log files might help by identifying the prior version number of ffmpeg...

**Comment by CJRomix** [comment]
Same here but only on 5.7.0 version, revert to 5.6.0 no problem.

**Comment by GeZorTenPlotZ** [comment]
Same issue for me. Back to 5.6.0.

**Comment by Damundai** [comment]
> I have had a similar issue a few months ago. Have you recently updated your ffmpeg as well?
> 
> Reverting to an older ffmpeg version did the trick for me IIRC. If you updated it recently, the old log files might help by identifying the prior version number of ffmpeg...

Yes, downlaoded the most recent version....  BtbN, build 31add5f

**Comment by CJRomix** [comment]
I just downloaded the most recent version @ gyan.dev FFmpeg v7.0.1 (2024-05-26) and 5.7.0 worked well.

**Comment by cdgriffith** [comment]
Thank you for reporting this issue, not sure root cause with the different ffmpeg versions but I have a workaround now to properly disable using opencl for thumbnail creation when it fails in 5.7.1 https://github.com/cdgriffith/FastFlix/releases/tag/5.7.1
