### ISSUE TITLE
Audio custom bitrate box shows units in kilobits/second but passes bits/second as the parameter

### ISSUE THREAD

**Issue by tcmbackwards** [cdgriffith/FastFlix#564]
**FastFlix Version:**
5.7.0
**Operating System:**
Windows 10 Pro
**Describe the bug**
When  using custom bitrate in the new audio conversion dialog box, the label for the units is "kb/s", but the contents of the box are passed raw to the encoder, so if I enter "96" in the bitrate box libopus gives an error

**To Reproduce**
Enable conversion on an audio track
Set the codec to libopus
Enter "96" for custom bitrate
Begin encoding, libopus gives an error
Changing "96" to "96k" works

**Logs** (If applicable) In FastFlix you can go to Help > Open Log Directory and sort by latest to find the newest log file to add here.

Stream mapping:
  Stream #0:0 (h264) -> crop:default
  crop:default -> Stream #0:0 (libsvtav1)
  Stream #0:1 -> #0:1 (dts (dca) -> opus (libopus))
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[libopus @ 000001c650730c00] Bitrate 96 is extremely low, maybe you mean 96k
[libopus @ 000001c650730c00] The bit rate 96 bps is unsupported. Please choose a value between 500 and 1536000.
[aost#0:1/libopus @ 000001c6502d4880] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[af#0:1 @ 000001c6502ee9c0] Error sending frames to consumers: Invalid argument
[af#0:1 @ 000001c6502ee9c0] Task finished with error code: -22 (Invalid argument)
[af#0:1 @ 000001c6502ee9c0] Terminating thread with return code -22 (Invalid argument)

**Comment by cdgriffith** [comment]
Thank you for reporting this issue, should be fixed in 5.7.1! https://github.com/cdgriffith/FastFlix/releases/tag/5.7.1
