### ISSUE TITLE
Windows defender deleting execuatable after install (5.7.0) - shows up as Trojan

### ISSUE THREAD

**Issue by mikeSGman** [cdgriffith/FastFlix#565]
Just happened to me on the latest version (5.7.0). I checked the cert, and it shows as valid with your name and address. The install occurs, but the .exe file is deleted a few seconds after a successful installation.

![image](https://github.com/cdgriffith/FastFlix/assets/398394/b5ac581b-6ca0-409f-be73-1c1493330625)

![image](https://github.com/cdgriffith/FastFlix/assets/398394/90786300-9cb4-474d-81f6-0fba050f2926)

_Originally posted by @mikeSGman in https://github.com/cdgriffith/FastFlix/issues/274#issuecomment-2185146977_

**Comment by cdgriffith** [comment]
I sadly have 0 control over this, only thing to do is manually mark it as safe and report it as a false positive to hopefully help others. Main thread for this https://github.com/cdgriffith/FastFlix/issues/527

**Comment by mikeSGman** [comment]
Understood, only raised for your awareness. I'll try that, thanks!

**Comment by mikeSGman** [comment]
I sent it off, with a description of the program, along with a URL to this repo and an explanation of the Root Cause. Hopefully it'll help others.

![image](https://github.com/cdgriffith/FastFlix/assets/398394/27cb2c17-1515-4987-ac4e-0ab604a264c4)
