### ISSUE TITLE
Profiles saved with WebP output only load default settings

### ISSUE THREAD

**Issue by jpert** [cdgriffith/FastFlix#567]
**FastFlix Version:**
5.7.1

**Operating System:**
Win 11 Pro 22631.3737

**Describe the bug**
Any profile using the WebP output module doesn't actually recall saved settings for that module. Regardless of what parameters are saved in GUI with a new profile it only loads the module defaults for the 4 changeable parameters (lossless, compression level, preset and qscale)

**To Reproduce**
Load a source, load the WebP output module, modify the output parameters from default and save a new profile. Now change the output module to anything else. Finally, load your newly created WebP profile and see that it only loads the module defaults and not the modified settings you saved

**Comment by cdgriffith** [comment]
Thank you for the details of this issues! Found multiple causes with this and also affected some other items, so was able to fix up a lot with this brought to my attention. 

Will be fixed in 5.8.0, currently in beta if you can test: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0

**Comment by jpert** [comment]
a 47 hour beta to release turnaround? Amazing. Didn't get a chance to test though but I'll put the webp module through it's paces and let you know if all look well
