### ISSUE TITLE
[UI] Obscuring of Main FastFlix Window 

### ISSUE THREAD

**Issue by vitduck** [cdgriffith/FastFlix#568]
**FastFlix Version:**
5.7.0, 5.7.1 

**Operating System:**
Windows 11 21H1, 24H2 

**Describe the bug**
FastFlix main window is always offset to right side of the screen on startup

**Screen resolution** 
1920x1080 

**Screenshots**
![Fastflix](https://github.com/cdgriffith/FastFlix/assets/575950/9ec71dce-968f-41fc-bfa5-2d05561791b0)

Hello, 

I am not sure whether this can be classified as a bug since it does not hinder operation, and is just a minor inconvenience. 

As shown in the screenshot: 
- FastFlix main window always offset itself to the right side of the screen, obscuring about 15% of its windows. 
- User has to manually drag the window to center it on the screen 

At first, I thought that 24H2 is trying to act smart. But the same issue was observed with older version 21H1. 
I also tested with dual monitor setup where FastfFlix main window also 'bleeds' into the second monitor as well. 

Perhaps coordinates of the main window is currently calculated relatively w.r.t console's ones, causing excessive off set.

**Comment by cdgriffith** [comment]
Thanks for the improvement idea, never even thought of that to be honest. Should be centered in next version, beta: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by vitduck** [comment]
@cdgriffith 

Thanks for consider the suggestion. 
I would like to confirm that the main UI is now properly centered on my screen. 

Can I give a feed back on the beta here instead of opening a new thread ? 

![fastflix](https://github.com/user-attachments/assets/cc97d865-2688-4a72-aa6f-58a8a3132d63)

There is an issue with `pandetic_core` which prevents applying changes to video / audio settings. 
I can confirm that `5.7.4` does not show this error. 

Thanks.

**Comment by cdgriffith** [comment]
Thanks for the confirm and the error details! Fix is pushed to prod so won't affect the main version release :)

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
