### ISSUE TITLE
[QSVEnc] Inconsistent Behavior with avi files 

### ISSUE THREAD

**Issue by vitduck** [cdgriffith/FastFlix#569]
**FastFlix Version:**
5.7.0

**Operating System:**
Windows 11 21H1 

**Specs
- Intel Core i5 7500 (Kaby Lake) 
- Intel HD Graphics 630 
- https://github.com/rigaya/QSVEnc?tab=readme-ov-file#supported-hw-encoder--windows-os

**Describe the bug**
There are two issues observed when transcoding avi files using rigaya's QSVEnc 
- Audio not muxed in 
- Failed to decode avi file / failed to initialize file reader(s) 

**To Reproduce**
-  Audio not muxed in
    - Download sample avi file: https://file-examples.com/wp-content/storage/2018/04/file_example_AVI_1280_1_5MG.avi 
    - Raw command:
    ```
    "D:\QSVEncC_7.66_x64\QSVEncC64.exe" 
        -i "D:\file_example_AVI_1280_1_5MG.avi" 
        --video-metadata clear --metadata clear --chapter-copy 
        -c hevc --cqp 28 --quality best --la-depth 10 --level auto --output-depth 8 --avsync cfr  
       --audio-copy 1 --audio-disposition 1?unset   
       -m default_mode:infer_no_subs 
       -o "D:file_example_AVI_1280_1_5MG-fastflix-fab0.mp4"
   ```
   - Metadata for original sample file and transcoded one showing the later with missing audio
       - [file_example_AVI_1280_1_5MG.avi.txt](https://github.com/user-attachments/files/16007865/file_example_AVI_1280_1_5MG.avi.txt)
      - [file_example_AVI_1280_1_5MG-fastflix-fab0.mp4.txt](https://github.com/user-attachments/files/16007897/file_example_AVI_1280_1_5MG-fastflix-fab0.mp4.txt)
   - Log file
       - [flix_conversion_file_example_AVI_1280_1_5MG-fastflix-fab0_2024-06-27T13.22.56.log](https://github.com/user-attachments/files/16008041/flix_conversion_file_example_AVI_1280_1_5MG-fastflix-fab0_2024-06-27T13.22.56.log)

- Failed to decode avi file / failed to initialize file reader(s) 
    - The x264vfw codec was installed in advance following previous issue on rigaya's repo: https://github.com/rigaya/NVEnc/issues/162 
    - Download sample avi file: https://filesamples.com/samples/video/avi/sample_1280x720_surfing_with_audio.avi
    - Raw command: 
    ```
   "D:\QSVEncC_7.66_x64\QSVEncC64.exe" 
       -i "D:\sample_1280x720_surfing_with_audio.avi" 
       --video-metadata clear --metadata clear --chapter-copy 
       -c hevc --cqp 28 --quality best --la-depth 10 --level auto --output-depth 8 --avsync cfr  
       --audio-copy 1 --audio-disposition 1?unset   -m default_mode:infer_no_subs 
       -o "D:sample_1280x720_surfing_with_audio-fastflix-b9d3.mp4"
   ```
   - Log file
       -  [flix_conversion_sample_1280x720_surfing_with_audio-fastflix-b9d3_2024-06-27T13.42.07.log](https://github.com/user-attachments/files/16008076/flix_conversion_sample_1280x720_surfing_with_audio-fastflix-b9d3_2024-06-27T13.42.07.log)

**Comment by cdgriffith** [comment]
Hi @vitduck, as these are errors with QSVEncC itself, please report these to that tool! https://github.com/rigaya/QSVEnc/issues

**Comment by vitduck** [comment]
Thanks, I will. 

Please close this ticket as you see fit.
