### ISSUE TITLE
Feature Request: Actions on Completion

### ISSUE THREAD

**Issue by TGMais** [cdgriffith/FastFlix#57]
Not sure if this is reasonable with the current command line setup, but it would be nice to be able to tell the computer to shutdown or run some other commands when complete.

**Comment by cdgriffith** [comment]
This could actually be expanded into its own tab and just have "Actions" for "pre" and "post" conversion. 

Then can have a way to use common ones or save your own to the config file as well.

**Comment by cdgriffith** [comment]
I am working on adding this for next release. Currently I don't think a whole tab for it makes sense, so have reduced it to a drop down. However, I also am adding the idea of custom commands that can be configured via the config file. 

For example: 
```
  "custom_after_run_scripts": {"test": "echo 'test'"}
```

It's added to the command tab in the UI: 

![command to run](https://user-images.githubusercontent.com/3275435/94630139-72d16500-028a-11eb-89a8-ed3ee1f9bd40.PNG)

**Comment by cdgriffith** [comment]
The initial version of this is out in https://github.com/cdgriffith/FastFlix/releases/tag/3.1.0. I do not know if permissions for the running user will always be appropriate to complete said command actions, so I would consider this "experimental" for now. 

I an not planning closing this ticeket until I add documentation on how to add custom commands via the config file.

**Comment by cdgriffith** [comment]
Basic guide added to [the wiki](https://github.com/cdgriffith/FastFlix/wiki/Config-File)
