### ISSUE TITLE
Changing audio language does not work

### ISSUE THREAD

**Issue by danielly2020** [cdgriffith/FastFlix#570]
**FastFlix Version:**
5.7.0/5.7.1
**Operating System:**
Windows 10 Professional Edition
**Describe the bug**
If I change the audio language but it doesn't take effect, the result will still be the original language.
But in version 5.6.0, it is OK.

**Comment by cdgriffith** [comment]
Thanks for bringing that up! Should be fixed https://github.com/cdgriffith/FastFlix/releases/tag/5.7.2
