### ISSUE TITLE
Windows Security Detected: Trojan:Win32/Wacatac.B!ml on installed FastFlix.exe, No Digital Signature present, v5.7.3

### ISSUE THREAD

**Issue by samkatakouzinos** [cdgriffith/FastFlix#578]
**FastFlix Version:** v5.7.3

**Operating System:** Windows 10 

Device Specifications  
Device name	xxxx
Processor	AMD Ryzen 7 3800X 8-Core Processor                4.20 GHz
Installed RAM	32.0 GB
Device ID	xxxx
Product ID	00330-80000-00000-AA726
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

Windows specifications  
Edition	Windows 10 Pro
Version	22H2
Installed on	‎23/‎06/‎2024
OS build	19045.4651
Experience	Windows Feature Experience Pack 1000.19060.1000.0

**Describe the bug:**
1. Even though the downloaded installer has a Digital Signature, the installed executable does not.
2. Windows Security Detected: Trojan:Win32/Wacatac.B!ml on installed FastFlix.exe.

**To Reproduce:**
1. Install from FastFlix_5.7.3_installer.exe

**Screenshots:**
![OMfbqvZSlH](https://github.com/cdgriffith/FastFlix/assets/1305871/b17be528-9893-4e01-aaf0-dcf061545741)
![ApplicationFrameHost_v1NqjRwhxY](https://github.com/cdgriffith/FastFlix/assets/1305871/f0515b57-dbb4-4737-9cb2-442f4c5abf4e)

**Logs:** No logs attached.

**Comment by Hankuuuu** [comment]
![Replay](https://github.com/user-attachments/assets/62493e22-0dda-4c5f-bcb8-0b13287ddc52)

**Comment by cdgriffith** [comment]
Thank you for bringing it to my attention that the internal exe was not also signed, I have fixed that, hopefully AVs get a little less sensitive! https://github.com/cdgriffith/FastFlix/releases/tag/5.7.4

**Comment by samkatakouzinos** [comment]
Post Feedback: Installing from https://github.com/cdgriffith/FastFlix/releases/tag/5.7.4 stopped raising issues from Windows Security.
Thank you for adressing this issue.
