### ISSUE TITLE
Missing Infos and no Mouse-Over info in Subs-Panel since 5.7

### ISSUE THREAD

**Issue by GeZorTenPlotZ** [cdgriffith/FastFlix#579]
As title says. 
5.6.0
![5 6 0](https://github.com/user-attachments/assets/328edee7-28cb-4d6d-b0e5-5e12e22c4a26)

5.7.x
![5 7 3](https://github.com/user-attachments/assets/94ea43d8-f906-450a-9e3f-3dc5087b2388)

**Comment by cdgriffith** [comment]
Thanks for the report, fixed in https://github.com/cdgriffith/FastFlix/releases/tag/5.7.4 !
