### ISSUE TITLE
Request - Attachment files tab

### ISSUE THREAD

**Issue by L0Lock** [cdgriffith/FastFlix#58]
I'd love to see a new tab for managing attachment files such as thumbnails or custom fonts.

I tried to add a custom thumbnail, whith I usually do using this kind of command:

```batch
ffmpeg -i video.mp4 -i cover.jpg -map 0 -map 1 -c copy -disposition:v:1 attached_pic video_covered.mp4
```
I tried to play with the custom ffmpeg options input in the Quality tab but never achieved what I wanted.

**Comment by cdgriffith** [comment]
Excellent idea, and amazing timing beating me to opening this exact ticket by a day! I personally was thinking of just having a thumbnail option upload filed for now, but would be nice to have an entire extra panel to manage adding extra files (such as combining another audio file or attachments.)

**Comment by L0Lock** [comment]
Glad to hear that! 😀

As I did some more digging around the subject of thumbnails, I discovered that the method to use is not always the same. The additional video stream + disposition argument is for most files (apparently), including MP4.

But some others like MKV use metadatas instead :

```batch
ffmpeg -i video.mp4 -attach cover.jpg -metadata:s:t mimetype=image/jpeg -c copy video_covered.mkv
```
I don't have the exact list of which containers support which method, but that's a start I guess.

I often make some ffmpeg bat script files and I published two just for that. I'm nowhere near to be an expert but if you are interested into some examples you can check my `ADD_Cover_to_XXX.bat` files on my repo:

https://github.com/L0Lock/FFmpeg-bat-collection/

**Comment by cdgriffith** [comment]
Just want to record down that attaching a cover to MKV does not always seem to show in windows. 

Also that the filename must be "cover.jpg" (or other [allowed variant](https://www.matroska.org/technical/attachments.html)) and can be set via `-metadata:s:t filename="cover.jpg"`. It also has recommeneded resolutions for each name. 

filename | Image Orientation | Pixel Length of Smallest Side
-- | -- | --
cover.jpg | Portrait or square | 600
small_cover.png | Portrait or square | 120
cover_land.png | Landscape | 600
small_cover_land.jpg | Landscape | 120

**Comment by cdgriffith** [comment]
Figured it out for Windows at least. You can view MKV file cover art by installing [ICAROS](https://www.videohelp.com/software/Icaros), setting up the Thumbnails, and explicitly checking the "Use embedded Cover Art for thumbnails" option. 

![icaros](https://user-images.githubusercontent.com/3275435/92636930-cbba6880-f29d-11ea-9099-d3cc1ccc7bb0.PNG)

**Comment by L0Lock** [comment]
I use Icaros already, maybe that's why I see them well 😯  
I couldn't use windows without it, I use many file formats for my work that windows don't support out of the box.

I tried the "mp4 thumbnail method" (if i can call it this way) on MKVs, and it never worked well. Depending on the order of arguments, there was either no custom thumbnail at all, or a custom thumbnail but then I couldn't see the video stream when playing (tested on VLC, Pot Player and HPC, both actual video stream & thumbnail streams are there and can be selected but the result is pure black). Weird stuff. So far only the "mkv thumbnail method" gives good results from the first attempt.

**Comment by cdgriffith** [comment]
Covers for `mkv` files have been added in  [3.0.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.0.0). 

I have items in the project for being able to add / passthrough fonts for subtitles and trying covers on more formats.  https://github.com/cdgriffith/FastFlix/projects/1

Also wrote up a quick guide on being able to see said thumbnails on each major system and linked it on cover page https://codecalamity.com/guides/video-thumbnails/
