### ISSUE TITLE
KeyError: no downmix

### ISSUE THREAD

**Issue by Hankuuuu** [cdgriffith/FastFlix#580]
Thank you, Chris, for your hard work and for releasing the new version 5.7.3. You are wonderful! 👍 
Here's a minor bug report. Hope it can help. Thank you again, Chris! 💚

![downmix](https://github.com/user-attachments/assets/586c467e-897f-4db1-9c10-721224ca90a8)

**Comment by cdgriffith** [comment]
Thanks for the details, fixed / workarounds in place in https://github.com/cdgriffith/FastFlix/releases/tag/5.7.4
