### ISSUE TITLE
Fastflix could not recognize hevc video containing hdr10plus metadata with recent ffmpeg build.

### ISSUE THREAD

**Issue by alpha-0** [cdgriffith/FastFlix#581]
**FastFlix Version:**
5.7.2 and earlier version

**Describe the bug**
Fastflix could not recognize any hevc video containing hdr10plus metadata with recent ffmpeg build (ENABLE_HDR10_PLUS=ON).

That is because recent ffmpeg has vbsf option deprecated.

For example to verify hdr10plus metadata from old version to the recent version of ffmpeg:
`ffmpeg -loglevel warning -i input.mkv -map 0:v:0 -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_tool --verify extract -`

should be changed to:
`ffmpeg -loglevel warning -i input.mkv -map 0:v:0 -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | hdr10plus_tool --verify extract -`

**Comment by cdgriffith** [comment]
Appreciate the updated command and details, makes life easy to update ! https://github.com/cdgriffith/FastFlix/releases/tag/5.7.4
