### ISSUE TITLE
Allow conversions of audio without a video output

### ISSUE THREAD

**Issue by zeus81** [cdgriffith/FastFlix#584]
Sometimes it is good to encode video and audio separately, for example when using Avisynth scripts.
While we can encode a video without audio the opposite is not true.
We can still copy the video without encoding it but it'll add a lot of useless disc writes.
And if a file (eg mka) don't have a video track it will straight prevent you from opening it.
Currently I edit the raw command to remove the video track from here when needed so it's not a huge deal but if fastflix could handle it automatically that'd be great.

**Comment by cdgriffith** [comment]
Hi @zeus81 , thanks for the idea, but as FastFlix is completely video centric it would basically be a new tool to write to make that possible. 

I do think a good step would be allow import of second file to add audio tracks / subtitle tracks. 

I would consider a Pull Request of a new window that was basically it's own audio only tool, but not something I would have time to code.
