### ISSUE TITLE
AAC coding error on profile save (v5.7.4)

### ISSUE THREAD

**Issue by Hankuuuu** [cdgriffith/FastFlix#586]
😁 A minor bug, hope it helps.

![AAC Profile](https://github.com/user-attachments/assets/d71fadd2-5396-4485-9784-2ea6353388f8)

▶️
This issue occurs with **FastFlix 5.7.4** when choosing **AAC**. 
Other codecs work without problems, such as **AC3, eAC3, Flac, Libfdk_aac, LibMP3Lame**.

▶️
After switching different FFMpeg, the situation remains the same: 
[Official FFMpeg N-116339-g7dabad079b-20240719] [VVCEasy FFMpeg 2.7.0]

▶️
When I switch **Profile** back to **Standard Profile** and manually select **AAC** under **Audio**, 
this issue does not occur.

.

**Comment by cdgriffith** [comment]
Should be fixed in 5.8.0, beta to test with: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Fixed in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
