### ISSUE TITLE
5.7.4 audio and subs tab still broken

### ISSUE THREAD

**Issue by GeZorTenPlotZ** [cdgriffith/FastFlix#588]
Mouse hoover is fixed but settings from within the source are not set automatically (forced, etc.)
And even when you set them manually they are not shown.

5.6.0 Audio
![5 6 0 audio](https://github.com/user-attachments/assets/83e665d8-0139-4f70-9e97-7e7b077ebe97)

5.7.4 Audio
![5 7 4 audio](https://github.com/user-attachments/assets/0a098e28-177d-4370-be91-ee77dff87093)

5.6.0 Subs
![5 6 0 subs](https://github.com/user-attachments/assets/d4da6035-6f60-44aa-992d-91eb701e1fb8)

5.7.4 Subs
![5 7 4 subs](https://github.com/user-attachments/assets/3a4f5e12-d53f-4103-9851-ecb58890e25e)

So, for me 5.7.x should be pulled. To much borked here.
Best news is, that i can update ffmpeg and hdr10+ is still recognized.
Port back to 5.6.0 and i'm very happy.

**Comment by cdgriffith** [comment]
Fixed in 5.8.0, beta to test with: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Fixed in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
