### ISSUE TITLE
Add support for pydantic 2.x ?

### ISSUE THREAD

**Issue by marillat** [cdgriffith/FastFlix#589]
**FastFlix Version:**
5.7.4
**Operating System:**
Linux amd64 Debian unstable Python 3.12
**Describe the bug**
FastFlix fail to start with (python3-pydantic 2.4.2 and python3-pydantic-core 2.11.0)
```
File "/usr/lib/python3/dist-packages/pydantic/_internal/_generate_schema.py", line 415, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'box.Box'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type
```

**Comment by marillat** [comment]
I forgot to read the pyproject.toml
I changed the bug title.

**Comment by cdgriffith** [comment]
Hi @marillat, sounds like you are trying to use only system packages? 

I would recommend setting up a `venv` for any python projects you are running, detailed in the release: 

```
git clone https://github.com/cdgriffith/FastFlix.git
cd FastFlix
python3.12 -m pip install --upgrade pip
python3.12 -m venv venv
. ./venv/bin/activate  
pip install .
```

**Comment by marillat** [comment]
> Hi @marillat, sounds like you are trying to use only system packages?

Yes.

> I would recommend setting up a `venv` for any python projects you are running, detailed in the release:

As I'm a Debian maintainer I try to not use venv, composer or npm and I don't want to build appimage.
Also, old code are not always maintainer and you can introduce more or less serious security issue.

Feel free to close this issue.

**Comment by cdgriffith** [comment]
Curious why you would shy away from venvs? They purposefully isolate an environment so you don't have to worry about the system's overall security when using packages for a specific program. 

And can keep ticket open as I will have to migrate to pydantic 2 anyways!

**Comment by cdgriffith** [comment]
Decided to jump to new version with next release. It may cause errors with some people's old save profiles, so currently in beta: https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0

**Comment by marillat** [comment]
Thanks.
