### ISSUE TITLE
[Feature Request] Queue System

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#59]
This would be very "dumb" compared to other solutions. Aka nothing like handbrake's awesome subtitle / audio track detection mechanisims. Simply always using the same tracks.

**Comment by cdgriffith** [comment]
Updating this to be a little bit more usable instead of just a dumb operation, just send the commands you want to a queue. First take won't be as smooth as other solutions where you could send it back off the queue and edit it, but still would be handy.

**Comment by malcolmradelet** [comment]
Would this allow setting some default options like the Preset and CRF for all the files? Hope so :)

**Comment by cdgriffith** [comment]
Currently in heavy dev, but yes! Working on Queue + Profiles are the big additions for 4.0. 

![queue_and_presets](https://user-images.githubusercontent.com/3275435/100459856-c47c4d00-308b-11eb-92eb-76e2771562a6.PNG)

**Comment by cdgriffith** [comment]
Added https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0
