### ISSUE TITLE
ruamel.yaml is missing in pyproject.toml

### ISSUE THREAD

**Issue by marillat** [cdgriffith/FastFlix#590]
**FastFlix Version:**
5.7.4
**Operating System:**
Debian amd64 unstable
**Describe the bug**
FastFix call `ruamel.yaml` in two places but declaration is missing in pyproject.toml

`fastflix/entry.py:            import ruamel.yaml`
`fastflix/ff_queue.py:from ruamel.yaml import YAMLError`

**Comment by cdgriffith** [comment]
Hi @marillat it is pulled in as part of `python-box[all]` that's what the "extra requires" does with the `all`. 

Can see in that project what that brings in: 

https://github.com/cdgriffith/Box/blob/master/setup.py#L70
