### ISSUE TITLE
Add alpha channel

### ISSUE THREAD

**Issue by subof** [cdgriffith/FastFlix#592]
Add a setting for the alpha channel for VP9, AV1 and STV-AV1, please.

**Comment by cdgriffith** [comment]
AV1 spec does not support transparency to my knowledge (AVIF does but not the video encoders), and a quick look at the encoders in ffmpeg they don't support `yuva420p` like VP9 does. 

I have tried several times to pass through transparency from one `webm` to another encoded `vp9` video without luck. 
What would we have to do other than `ffmpeg -i in.webm -c:v libvpx-vp9 -pix_fmt yuva420p -b:v 0 -crf:v 31 -quality:v good out.webm` to get it working?

**Comment by subof** [comment]
Perhaps it should be a separate layer in the format.webm, not in the codec itself.

**Comment by cdgriffith** [comment]
I am adding that format to VP9 options just to have it in case it can work for you or others. Currently in beta https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0b0 if you want to test!

**Comment by cdgriffith** [comment]
Added in 5.8.0! https://github.com/cdgriffith/FastFlix/releases/tag/5.8.0
