### ISSUE TITLE
Enable mulòtilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [cdgriffith/FastFlix#596]
Thanks for your program-.

Please consider to enable multilanguage GUI.
Your program is based on Python then you can setup it easiliy to use multilanguage strings.

Thanks.

Please use Discussions for new Features! They can be voted upon, and that way I can work in the most demanded features first.

Don't forget to first search for the feature you want, as well as upvote others you would like to see!

**Comment by cdgriffith** [comment]
hI @bovirus, It is multi-lingual! You can change the language in File > Settings (or Ctrl+S).

![Screenshot 2024-08-11 084358](https://github.com/user-attachments/assets/356d4ea9-d6a6-4c06-b7ad-06de8052c653)

**Comment by bovirus** [comment]
@cdgriffith 

Thanks I found the language file

https://github.com/cdgriffith/FastFlix/blob/master/fastflix/data/languages.yaml

I found some issues regarding Italian language.

I believe tht it's quite complex to post the changes for a apsecfic language because the file contains all languages then could be an overlap of changes by different translator.

Thanks.

**Comment by bovirus** [comment]
@cdgriffith 

Thanks.
Italian language revsied.
