### ISSUE TITLE
It does not start

### ISSUE THREAD

**Issue by Chikitano** [cdgriffith/FastFlix#608]
Hello

I have been use FastFlix for long time, suddenly (without any change) since yesterday it does not star. When I execute the progran it shows <removed> mensaje and close down.

I tryed to uninstall and reinstall (with the last  version 5.8.1 and older versions) with the same result. I run it on win 11 x64.

Waiting for your help

Thanks

**Comment by cdgriffith** [comment]
Hi @Chikitano please upload the error image here, not on other site (when trying to access it said service unavailable.)

**Comment by Chikitano** [comment]
Hello

After a couple of days traying I I formatted the PC. After that fastflix work well. I assume was a problem of my system not the fastflix.

thanks for your attention.
