### ISSUE TITLE
VVenc: Unrecognized option levelidc

### ISSUE THREAD

**Issue by zyrill** [cdgriffith/FastFlix#615]
**FastFlix Version:**
5.8.1
**Operating System:**
Win11 Enterprise 23H2, v22631.4317
**Describe the bug**
Tried to encode clip with VVC, but encoder exits with "Unrecognized option 'levelidc'". Raw command follows:
`ffmpeg.exe -y -i clip.mkv -metadata title="clip" -filter_complex "[0:0]yadif,crop=3840:1608:0:276[v]" -map "[v]" -c:v libvvenc -pix_fmt yuv420p10le -metadata:s:v:0 title="clip" -tier:v high -levelidc 6.3 -qp:v 17 -b:v 0 -preset:v slow -map_metadata -1-map_chapters 0 -map 0:1 -metadata:s:1 title="EN" -metadata:s:1 handler="TrueHD 7.1 Atmos" -metadata:s:1 language=eng -c:1 copy -disposition:1 default -default_mode infer_no_subs "clip.mkv"`

**To Reproduce**
Load clip, set encoder to VVC, set tier and IDC level and hit "Convert"

**Log**
`ffmpeg version N-117612-gc98810ab47-20241019 Copyright (c) 2000-2024 the FFmpeg developers

  built with gcc 14.2.0 (crosstool-NG 1.26.0.120_4d36f27)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-lzma --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-libzmq --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libvvenc --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs=-lgomp --extra-ldflags=-pthread --extra-ldexeflags= --cc=x86_64-w64-mingw32-gcc --cxx=x86_64-w64-mingw32-g++ --ar=x86_64-w64-mingw32-gcc-ar --ranlib=x86_64-w64-mingw32-gcc-ranlib --nm=x86_64-w64-mingw32-gcc-nm --extra-version=20241019
  libavutil      59. 44.100 / 59. 44.100
  libavcodec     61. 22.100 / 61. 22.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.100 / 10.  6.100
  libswscale      8.  6.100 /  8.  6.100
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
Unrecognized option 'levelidc'.
Error splitting the argument list: Option not found`

**Comment by zyrill** [comment]
I think I found the solution, pls check https://github.com/cdgriffith/FastFlix/pull/616

**Comment by cdgriffith** [comment]
Should be fixed with your code in 5.8.2!
