### ISSUE TITLE
Multitask encode support to maximize cpu utilization

### ISSUE THREAD

**Issue by eikixsh** [cdgriffith/FastFlix#625]
For x265 4k encode, my 8core cpu utilization is around 40% at 1st pass and 80% at 2nd pass. Fastflix only do 1 job each time, others are in the quene.
Is it possible to add multitask encoding so that it may utilize the cpu maximumly?

**Comment by cdgriffith** [comment]
I just gave an update of my thoughts on this on the first issue about this, so closing this ticket but will copy response for ease. https://github.com/cdgriffith/FastFlix/issues/401

> Thought about trying this a few times over the years, but the idea of a single encode is very integral to the way FastFlix operates to the point it would probably be easier to write a new program than modify FastFlix as is to do multiple encodes reliably.
