### ISSUE TITLE
Feature Request: get the CRF suggestions back D:

### ISSUE THREAD

**Issue by L0Lock** [cdgriffith/FastFlix#63]
I see in this [commit](https://github.com/cdgriffith/FastFlix/pull/61/commits/b2c1620e0ecfb40c5dbc1c37bac34a11d8c15cb8#diff-d6c3ba571f9aea829b5a08b2d31d6e85) you added more CRF values. Which is neat!

But I also see you removed the little resolutions parentheses. IMHO these were neat as well. I mean, even though I know how to choose the proper CRF values, I'm always a little ~~lazy~~ concerned about the time I spend prevaricating instead of hitting the Convert button.

On a more serious tone, I think these indications are a good thing for anyone a bit new to ffmpeg or just in need for tools that are quick and easy to understand.

So... Maybe it would be nice to add them back ?

**Comment by cdgriffith** [comment]
The problem with them was they were especially clear, and with more CRFs didn't want to have too much confusion, but I think you are right. I am adding them back with a bit more details in the tool tip.

**Comment by cdgriffith** [comment]
Added again in https://github.com/cdgriffith/FastFlix/releases/tag/2.6.1, thanks!
