### ISSUE TITLE
Feature Request: Add audio meta tag "language"

### ISSUE THREAD

**Issue by HannesJo0139** [cdgriffith/FastFlix#69]
Thanks again for your work! I just noticed that Fastflix adds no language tag to audio streams. In most cases, I have an english and a german audio stream and convert them. Fasflix adds a title and a handler meta tag. Could you add a language tag? Some Players like Plex just grab that one and they just show Language: UNDEFINED then. Thanks!

**Comment by cdgriffith** [comment]
Added in [3.0.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.0.0)
