### ISSUE TITLE
Removing subtitles doesn't seem to work.

### ISSUE THREAD

**Issue by trenthaynes** [cdgriffith/FastFlix#78]
It could be user error, but I can't seem to remove subtitles. The red "x" doesn't do anything and I can't see any other way of removing them from the list.

![image](https://user-images.githubusercontent.com/5551080/95410816-962f8c00-08ea-11eb-8348-f89d0f259627.png)

**Comment by cdgriffith** [comment]
The "Preserve" checkbox is what tells it to copy or remove the subtitles. The red X indicates it won't be copied over.  (If you have a scenario where they still are being copied even when they have that red X, that's a bug)

**Comment by trenthaynes** [comment]
Good to know.  Chalk it up to user error.
