### ISSUE TITLE
Thumbnail Appearing as a Black Screen

### ISSUE THREAD

**Issue by zsumie** [cdgriffith/FastFlix#80]
Tested with multiple different video sources, and versions

![image](https://user-images.githubusercontent.com/72701017/95682901-f7d74b00-0bb5-11eb-9ed1-5704d79d5284.png)

**Comment by cdgriffith** [comment]
It is currently based off the "start" position of the video. So if the video starts with a black screen, it will be black. Changing it to 30 seconds in should show it properly. 

In upcoming 3.1.0 if the video starts at 0 seconds it will jump to 10% into the video as a lot of videos start black which makes it unclear it's a thumbnail as you are experiencing.

**Comment by mfraser** [comment]
I'm just seeing "Error Updating Thumbnail"

**Comment by cdgriffith** [comment]
@mfraser do the logs show an traceback?

**Comment by mfraser** [comment]
Generating thumbnail: "/usr/bin/ffmpeg"  -loglevel error -i "/home/mfraser/Videos/Birds of Prey.mkv"  -vf zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p,scale="min(320\,iw):-1" -map 0:0 -an -y -map_metadata -1 -vframes 1 "/home/mfraser/.local/share/FastFlix/thumbnail_preview.png"
ERROR Could not generate thumbnail: b"[AVFilterGraph @ 0x55f852d32580] No such filter: 'zscale'\nError reinitializing filters!\nFailed to inject frame into filter network: Invalid argument\nError while processing the decoded data for stream #0:0\n"

**Comment by cdgriffith** [comment]
Ah, some versions of FFmpeg are built with outdated versions of zimg. Are you using latest `ffmpeg` 4.3+ static build from https://johnvansickle.com/ffmpeg/ ?  (I put that [gotcha in the readme](https://github.com/cdgriffith/FastFlix#macos-and-linux) but is an easy detail to miss. )

**Comment by cdgriffith** [comment]
Adding error message that is more clear in 3.1.0

```
020-10-15 18:10:25 jvm fastflix[4420] ERROR Could not generate thumbnail because you are using an outdated FFmpeg! Please use FFmpeg 4.3+ built against the latest zimg libraries. Static builds available at https://ffmpeg.org/download.html (Linux distributions are often slow to update)
```

**Comment by cdgriffith** [comment]
The new error message has been added to https://github.com/cdgriffith/FastFlix/releases/tag/3.1.0

And while it may still perform most actions with outdated FFmpeg versions, I won't explicitly support them so not adding backwards compatability for them at this point.  (For example, without the zscale filter, Remove HDR would also not work)
