### ISSUE TITLE
[Feature Request] Add external subtitle files

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#85]
Extension of https://github.com/cdgriffith/FastFlix/issues/75

**Comment by leonardyan** [comment]
IMO multilingual support is better to be postponed, and needn't to be listed as a high-priority task. We can start it after all the features and UI texts get basically stable.

**Comment by cdgriffith** [comment]
Now discussion https://github.com/cdgriffith/FastFlix/discussions/445
