### ISSUE TITLE
[Feature Request] Offer deeper audio encoder options 

### ISSUE THREAD

**Issue by I-Iawk** [cdgriffith/FastFlix#88]
Was wondering how hard would it be to extend the current functionality of the **Audio** tab at this time? Looking to be able to set channels and custom options that are listed here:  [https://ffmpeg.org/ffmpeg-codecs.html#Option-Mapping](url)

If it is not feasible due to the lack of API hooks, what about letting us create and save presets for the time being so we don't need to add them manually via the Custom ffmpeg options section?

**Comment by cdgriffith** [comment]
Hi @I-Iawk this seems to be in the same ballpark as #45 so I would suggest we throw the conversation over there. Custom audio options are a long term goal but not something I was planning on tackling for a bit.
