### ISSUE TITLE
hdr-opt to hdr10-opt

### ISSUE THREAD

**Issue by SlashX** [cdgriffith/FastFlix#89]
Hello again,

I found that in the recent build of x265 and FFmpeg hdr-opt has changed from 
   --[no-]hdr-opt                Add luma and chroma offsets for HDR/WCG content. Default disabled. Now deprecated.
to
   --[no-]hdr10-opt              Block-level QP optimization for HDR10 content. Default disabled.

When select a HDR10 video, in command line, it shows that is using 'hdr-opt' so it should use the new command 'hdr10-opt'
Screenshot
![Fără titlu](https://user-images.githubusercontent.com/29688/96976557-ac615d00-1524-11eb-9422-2ab8519edb92.jpg)

**Comment by cdgriffith** [comment]
Great catch! As x265 seems to ignore "bad" options I will brute-force it for the time being by sending both old and new versions going forward.

**Comment by SlashX** [comment]
I just did some research on x265 and I don't think is necessary to send both commands:
For hdr-opt
    - [no-] hdr-opt Add Luma and Chroma offsets for HDR / WCG content. Default disabled. Now obsolete.
    - [no-] hdr10-opt Block-level QP optimization for HDR10 content. Default disabled.

And for also hdr
   - [no-] hdr Force signalling of HDR parameters in SEI packets. Enabled. Now obsolete.
    -[no-]-hdr10 Force signalling of HDR parameters in SEI packets. Enabled. Default disabled.

The change was made 9 moths ago and ffmpeg 4.3 is using the new commands: here are the commits:
http://hg.videolan.org/x265/rev/3780f7544794
http://hg.videolan.org/x265/rev/fe9d36ccb331

But is your decision, I was thinking of make it less hardcoded and provide you the info on this situation faster.

**Comment by cdgriffith** [comment]
[3.3.0](https://github.com/cdgriffith/FastFlix/releases/tag/3.3.0) now has both so it will work with both newer and older ffmpeg compiles. For a nice feature would be good to have another panel with a lot of x265 specific params including those options, but that is more far off.
