### ISSUE TITLE
[Feature Request] Ability to save default settings

### ISSUE THREAD

**Issue by robchap79** [cdgriffith/FastFlix#94]
Hi, love this program, just two little niggles (other one in separate thread):-

Is there a way to set default settings so when I open the program it's automatically set to CFR 20, auto crop and Main10 profile? I'm fairly useless with python (aside from some home automation scripting), but I'm happy to poke around in it if you could point me in the right direction.

Thanks

**Comment by cdgriffith** [comment]
There is currently not a way to do that, however something I have been considering how to implement is presets, and then being able to have a default preset. 

Personally I consider the code right now rather low quality, as I have been working on it quite rapidly to get features out without much time to re-factor as needed, so please don't feel the need to get lost it in. 

Off the top of my head how I would implement it is have a string representation of settings for each panel, and then the panels themselves look at the current preset (saved via the config file) when running their "new_source" functions.

**Comment by vpil** [comment]
Hello I would also appreciate any way how to store at least default custom values (if not multiple user presets) - x265 params, x265 preset, CRF. Thank you.

**Comment by cdgriffith** [comment]
That is actually in the works via "Profiles" aka presets / saved settings for 4.0!

![queue_and_presets](https://user-images.githubusercontent.com/3275435/100459856-c47c4d00-308b-11eb-92eb-76e2771562a6.PNG)

**Comment by vpil** [comment]
Looking forward for 4.0, thank you.

**Comment by cdgriffith** [comment]
Added a "profile" option in 4.0.0 https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0
