### ISSUE TITLE
UnicodeDecode Error: 'charmap'

### ISSUE THREAD

**Issue by robchap79** [cdgriffith/FastFlix#95]
![Capture](https://user-images.githubusercontent.com/73415839/97099455-fb4df480-16d4-11eb-93cf-896c5a654bea.PNG)

Hi, love fastflix, have an issue though - I have a lot of files that have russian characters in the metadata I believe the issue with this is that I get the following error when I try to encode them:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2045: character maps to <undefined>

Which I think is a python issue, but would have no idea where to specify character encoding of a file to make this work.

**Comment by cdgriffith** [comment]
That's me being an idiot. FFmpeg outputs in UTF-8 and I didn't specify encoding to read it as, and windows defaults to Windows-1252. Thanks for the report, will get out a point release soon!

**Comment by cdgriffith** [comment]
Fixed in [3.3.1](https://github.com/cdgriffith/FastFlix/releases/tag/3.3.1)

**Comment by robchap79** [comment]
Awesome thank you
