### ISSUE TITLE
[Feature Request]Accepting *.webm file input?

### ISSUE THREAD

**Issue by leonardyan** [cdgriffith/FastFlix#96]
I want to re-encode a VP9 WebM HDR clip that I downloaded from YouTube, into an HEVC MP4 one. However, FastFlix doesn't accept webm in its input file selection window. For a workaround I repackaged the source video into a VP9 MP4 one with command line ffmpeg(-c copy foo.mp4). Could FastFlix be made to accept WebM directly?

**Comment by leonardyan** [comment]
Also is it able to add some l10n framework(like gnu gettext) to this python-written GUI? Maybe I could contribute some Chinese translation.

**Comment by cdgriffith** [comment]
Could you try just dropping the file onto the main window? It should pick it up that way as a workaround for now. However I will also add support via selection box!

Adding support for multiple language has been on my [backlog](https://github.com/cdgriffith/FastFlix/projects/1) for a bit, so when I get a solution in place to handle it I would love contributions!

**Comment by cdgriffith** [comment]
Fixed in [3.3.1](https://github.com/cdgriffith/FastFlix/releases/tag/3.3.1)

Adding separate ticket #98 to capture multilingual support
