### ISSUE TITLE
[Feature Request] Add support for multiple languages

### ISSUE THREAD

**Issue by cdgriffith** [cdgriffith/FastFlix#98]
As requested by @leonardyan in #96

**Comment by leonardyan** [comment]
IMO multilingual support is better to be postponed, and needn't to be listed as a high-priority task. We can start it after all the features and UI texts get basically stable.

**Comment by cdgriffith** [comment]
In 4.0.0b2 I have selection between a few languages from ML translations (Chinese, German, Spanish, French, Italian), so a lot is probably wrong, but wanted to get started on multi-lingual support https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0b2

**Comment by leonardyan** [comment]
Thanks a lot! I've been busy on my personal affairs previously and didn't check my inbox for about a month. I'll try improving the Chinese translation recently.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chris Griffith"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 中午12:05
收件人: "cdgriffith/FastFlix"<FastFlix@noreply.github.com&gt;; 
抄送: "/南北大街/东西走/"<2530568239@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [cdgriffith/FastFlix] [Feature Request] Add support for multiple languages (#98)





 
In 4.0.0b2 I have selection between a few languages from ML translations (Chinese, German, Spanish, French, Italian), so a lot is probably wrong, but wanted to get started on multi-lingual support https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0b2

**Comment by leonardyan** [comment]
Also how to submit my translation improvements? Pull requests?

**Comment by cdgriffith** [comment]
PRs, posts on this thread, or just as feedback on discord all good!  I will probably create a general "Language Feedback" issue at some point after this release it out for future fixes.

**Comment by cdgriffith** [comment]
Initial support in https://github.com/cdgriffith/FastFlix/releases/tag/4.0.0. Not a huge selection of lanaguages but the framework to support them is now there! Will create a new issue for voting / suggesting other languages.
